### ISSUE TITLE
Jedi: AttributeError: 'Operator' object has no attribute 'get_definition'

### ISSUE THREAD

**Issue by bibsian** [jorgenschaefer/elpy#1007]
Hello,
I encountered a bug so I'm posting it here.

Thanks,
Andrew

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........:  (c:/Users/MillerLab/Envs/lter/)
RPC Python........: 3.4.0 (c:/Users/MillerLab/Envs/lter/Scripts/python.exe)
Interactive Python: python (c:/Users/MillerLab/Envs/lter/Scripts/python.exe)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.5 (0.1.7 available)
Autopep8..........: 0.1.5 (0.1.7 available)
Syntax checker....: flake8.exe (c:/Users/MillerLab/Envs/lter/Scripts/flake8.exe)

Traceback

Traceback (most recent call last):
  File "c:\home\.emacs.d\elpa\elpy-1.10.0\elpy\jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "c:\Python34\lib\site-packages\jedi\api\__init__.py", line 197, in completions
    for p in call_sig.params:
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\home\.emacs.d\elpa\elpy-1.10.0\elpy\jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "c:\Python34\lib\site-packages\jedi\api\__init__.py", line 197, in completions
    for p in call_sig.params:
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\evaluate\cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "c:\Python34\lib\site-packages\jedi\api\classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

Jedi Debug Information

[N] dbg: Parsed c:\Users\MillerLab\Desktop\database-development\test\logiclayer\scratch.py, with 0 parsers in 1 splits.
[W] warning: No statement under the cursor.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
[N] dbg: eval_element Node(power, [<Name: pr@12,0>, Node(trailer, [<Operator: .>, <Name: pprint@12,3>])])@(12, 0)
[N] dbg: finder.filter_name "<Name: pr@12,0>" in (<ModuleWrapper: <fast.FastModule: scratch@1-14>>): '[<Name: pr@2,17>]'@(12, 0)
[N] dbg: search_module 'pprint' in 'c:\\Users\\MillerLab\\Desktop\\database-development\\test\\logiclayer\\scratch.py'
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: pprint@11-417>>]
[N] dbg: finder._names_to_types: [<Name: pr@2,17>] -> [<ModuleWrapper: <fast.FastModule: pprint@11-417>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: pprint@12,3>]) in scope <ModuleWrapper: <fast.FastModule: pprint@11-417>>
[N] dbg: finder.filter_name "<Name: pprint@12,3>" in (<ModuleWrapper: <fast.FastModule: pprint@11-417>>): '[<Name: pprint@46,4>]'@None
[N] dbg: finder._names_to_types: [<FakeName: pprint@46,4>] -> [<eFunction of <Function: pprint@46-54>>]

```

Reproduction:

```Python
import jedi

source = '''\
from collections import OrderedDict, namedtuple
import pprint as pr

structure = namedtuple('structure', 'checked type unit')

structure_dict = OrderedDict((
    ('structured_type_1', structure(True, 'size', 'cm')),
    ('structured_type_2', structure(False, '', '')),
    ('structured_type_3', structure(False, '', ''))
))

pr.pprint(str

'''

script = jedi.Script(encoding='utf-8', source=source, line=12, path='c:/Users/MillerLab/Desktop/database-development/test/logiclayer/scratch.py', column=13)
script.completions()
```

**Comment by gopar** [comment]
I believe this is a problem with [Jedi](https://github.com/davidhalter/jedi). Should probably be reported there. :P

**Comment by bibsian** [comment]
That's what I was thinking. I just put it here since the bug tracker linked me to elpy, I'll move it over to Jedi.

**Comment by jorgenschaefer** [comment]
Thank you for the report – indeed, it's better to report it with Jedi, but it's never wrong to report here just in case. :-)
