### ISSUE TITLE
Elpy Error: attribute `int` not found 

### ISSUE THREAD

**Issue by asberk** [jorgenschaefer/elpy#1013]
```
Error Message

Attribute int not found

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/Users/myUserName/anaconda/bin/python)
Interactive Python: python (/Users/myUserName/anaconda/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Syntax checker....: pyflakes (/Users/myUserName/anaconda/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/myUserName/.emacs.d/elpa/elpy-1.8.0/elpy/ropebackend.py", line 99, in call_rope
    **kwargs)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 66, in pyname_at
    return new_pyname()
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 64, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 112, in get_primary_and_pyname_at
    return eval_str2(holding_scope, name)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 46, in eval_str2
    return eval_node2(holding_scope, node)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 187, in _Call
    pyobject=_get_returned(pyfunction))
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 168, in _get_returned
    return pyobject.get_returned_object(args)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 72, in get_returned_object
    return self.returned.get(args)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 44, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/oi/soi.py", line 21, in infer_returned_object
    result = object_info.get_exact_returned(pyfunction, args)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/oi/objectinfo.py", line 90, in get_exact_returned
    path, key, self._args_to_textual(pyobject, args))
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/oi/objectinfo.py", line 96, in _args_to_textual
    arguments = args.get_arguments(parameters)[:len(parameters)]
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/arguments.py", line 20, in get_arguments
    for pyname in self.get_pynames(parameters):
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/arguments.py", line 33, in get_pynames
    result[index] = self._evaluate(arg)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/arguments.py", line 41, in _evaluate
    return rope.base.evaluate.eval_node(self.scope, ast_node)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 195, in _Num
    self.result = self._get_builtin_name(type_name)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 198, in _get_builtin_name
    pytype = rope.base.builtins.builtins[type_name].get_object()
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/Users/myUserName/anaconda/lib/python3.5/site-packages/rope/base/pyobjects.py", line 20, in get_attribute
    'Attribute %s not found' % name)
rope.base.exceptions.AttributeNotFoundError: Attribute int not found

Rope Debug Information

```

Reproduction:

``` Python

redacted_code

project = rope.base.project.Project(
    "/path/to/data/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/path/to/data/project/data_import.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 785, resource, maxfixes=5, remove_self=True
)
```

**Comment by ChillarAnand** [comment]
Thanks for the report. 

> Elpy..............: 1.8.0

You are using an old version of elpy. Can you upgrade to latest version and try again?
