### ISSUE TITLE
No attribute 'get_subscope_by_name' when entering argument to lambda function

### ISSUE THREAD

**Issue by Nyle** [jorgenschaefer/elpy#1065]
I was switching from storing a result in a variable to having a lambda function calculate the value (`i_present `-> `get_i_present`, `present` -> `get_present`). When typing `(vals)` after `get_i_present` it freezes up when I hit the s key. Below is the error message given after it unfroze.

Error Message

'Lambda' object has no attribute 'get_subscope_by_name'

Configuration

Virtualenv........: None
RPC Python........: 2.7.11 (/Library/Frameworks/Python.framework/Versions/2.7/bin/python)
Interactive Python: python (/Library/Frameworks/Python.framework/Versions/2.7/bin/python)
Emacs.............: 24.4.50.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2 (1.2.4 available)
Yapf..............: 0.7.1 (0.15.2 available)
Syntax checker....: flake8 (/Library/Frameworks/Python.framework/Versions/2.7/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/nyle/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/Users/nyle/Library/Python/2.7/lib/python/site-packages/jedi-0.9.0-py2.7.egg/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/Users/nyle/Library/Python/2.7/lib/python/site-packages/jedi-0.9.0-py2.7.egg/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/nyle/Library/Python/2.7/lib/python/site-packages/jedi-0.9.0-py2.7.egg/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/Users/nyle/Library/Python/2.7/lib/python/site-packages/jedi-0.9.0-py2.7.egg/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'

Jedi Debug Information

[N] dbg: While parsing '/Users/nyle/work/coremicro/src/core/parse_inputs.py', line 54 slowed down the fast parser.
[N] dbg: While parsing '/Users/nyle/work/coremicro/src/core/parse_inputs.py', line 59 slowed down the fast parser.
[N] dbg: Parsed /Users/nyle/work/coremicro/src/core/parse_inputs.py, with 1 parsers in 8 splits.
[W] warning: No statement under the cursor.
[N] dbg: execute: <CompiledObject: <class 'future.types.newstr.newstr'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <CompiledObject: <slot wrapper '__init__' of 'object' objects>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <CompiledObject: <slot wrapper '__init__' of 'object' objects>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'future.types.newstr.newstr'>>(<Arguments: ()>)>] in <CompiledObject: <class 'future.types.newstr.newstr'>>
[N] dbg: eval_element <Name: get_i_present@69,35>@(69, 35)
[N] dbg: finder.filter_name "<Name: get_i_present@69,35>" in (<eFunction of <Function: summarize_otu_data@48-76>>): u'[<Name: get_i_present@57,4>]'@(69, 35)
[N]  dbg: eval_statement <ExprStmt:     get_i_present = lambda vals: len([v for i, v in enumerate(vals)                                       if i in i_indexes and v > min_abundance])@57,4> (<Name: get_i_present@57,4>)
[N]  dbg: eval_element <Lambda@(57, 20)>@(57, 20)
[N]  dbg: eval_statement result [<eLambdaWrapper of <Lambda@(57, 20)>>]
[N] dbg: finder._names_to_types: [<Name: get_i_present@57,4>] -> [<eLambdaWrapper of <Lambda@(57, 20)>>]

```

Reproduction:

```Python
import jedi

source = '''\
# Copyright 2016, 2017 Richard Rodrigues, Nyle Rodgers, Mark Williams,
# Virginia Tech
#
# This file is part of Coremic.
#
# Coremic is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Coremic is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Coremic. If not, see <http://www.gnu.org/licenses/>.


from biom.parse import parse_biom_table
from biom.table import table_factory, SparseOTUTable

import run_config


def read_table(table_file):
    """Read in the input datafile and combine any doubled OTUs
    """
    parsed_table = parse_biom_table(table_file)
    sample_ids = parsed_table.SampleIds
    original_otus = len(parsed_table.ObservationIds)
    otu_data = dict()
    for vals, id, md in parsed_table.iterObservations():
        otu = md['taxonomy']
        if(isinstance(otu, type(list()))):
            otu = ';'.join(otu)
        if otu_data.get(otu) is not None:
            otu_data[otu] = vals + otu_data[otu]  # both are numpy arrays
        else:
            otu_data[otu] = vals

    observation_ids = otu_data.keys()
    data = [otu_data[o] for o in observation_ids]
    return table_factory(data, sample_ids, observation_ids,
                         constructor=SparseOTUTable), original_otus


def summarize_otu_data(table, mapping_dict, i_group, min_abundance):
    """Gives a summary of the data for each otu to use in processing
    """
    # column number of interest samples
    i_indexes = [i for i, id in enumerate(table.SampleIds)
                 if id in samples(mapping_dict, i_group)]
    interest = len(i_indexes)
    total = sum([len(mapping_dict[group]) for group in mapping_dict])
    otu_data = list()
    get_i_present = lambda vals: len([v for i, v in enumerate(vals)
                                      if i in i_indexes and v > min_abundance])
    get_present = lambda vals: len([v for v in vals if v > min_abundance])
    for vals, otu, md in table.iterObservations():
        otu_data.append({
            'otu': otu,
            'total': total,
            'present': present,
            'absent': total - present,
            'interest': interest,
            'out': total - interest,
            'i_present': get_i_present(vals),
            'i_absent': interest - get_i_present(val,
            'o_present': present - i_present,
            'o_absent': total - present - (interest - i_present),
        })
    return otu_data


def samples(mapping_dict, group):
    return [otu for g in group for otu in mapping_dict[g]]


def parse_groupfile(groupfile, factor):
    """Turn the groupfile in to a dictionary from factor labels to sample ids
    """
    # It is assumed that the first line is the header
    labels = groupfile[0].strip().strip('#').split(run_config.DELIM)
    if 'SampleID' not in labels:
        raise ValueError('"SampleID" not in the headers of the groupfile')
    if factor not in labels:
        raise ValueError('"%s" not in the headers of the groupfile' % factor)

    index_sampleid = labels.index('SampleID')
    index_categ = labels.index(factor)
    local_dict = dict()
    for l in groupfile:
        if not l or l.strip()[0] == '#':  # Line is blank or comment
            continue
        key, val = map(l.strip().split(run_config.DELIM).__getitem__,
                       [index_categ, index_sampleid])
        if key in local_dict:
            local_dict[key].append(val)
        else:
            local_dict[key] = [val]
    return local_dict


def parse_inputs(params, groupfile, data):
    """Validate that the given inputs are usable and parse them into usable
    formats"""

    errors_list = list()

    try:
        mapping_dict = parse_groupfile(groupfile, params['factor'])
    except ValueError as e:
        errors_list.append(e.message)
    for l in params['group']:
        if l not in mapping_dict.keys():
            errors_list.append(
                'Interest group label %s is not in groupfile' % l)

    out_group = mapping_dict.keys()
    [out_group.remove(l) for l in params['group']]

    try:
        filtered_data, original_otus = read_table(data)
    except ValueError as e:
        errors_list.append('Datafile could not be read: %s' % e.message)

    if params['max_p'] < 0 or params['max_p'] > 1:
        errors_list.append('Maximum p-value must be in the range zero to one')
    if params['min_frac'] < 0 or params['min_frac'] > 1:
        errors_list.append('Minimum interest group presence must be in range' +
                           ' zero to one')
    if params['max_out_presence'] < 0 or params['max_out_presence'] > 1:
        errors_list.append('Maximum out-group presence must be in range' +
                           ' zero to one')
    # Should verify p-value-adjust is valid value

    return (errors_list, mapping_dict, out_group, filtered_data, original_otus)
'''

script = jedi.Script(column=52, source=source, line=69, encoding='utf-8', path=u'/Users/nyle/work/coremicro/src/core/parse_inputs.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! This is a problem in Jedi, could you file this on their github repo?
