### ISSUE TITLE
elpy-auto-pep8 error. 

### ISSUE THREAD

**Issue by groceryheist** [jorgenschaefer/elpy#1072]
```
Error Message

'module' object has no attribute 'fix_code'

Configuration

Virtualenv........: None
RPC Python........: 2.7.13 (/usr/bin/python)
Interactive Python: ipython3 (/usr/local/bin/ipython3)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: Not found (0.10.0 available)
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3 (0.1.7 available)
Autopep8..........: 0.9.1 (1.2.4 available)
Yapf..............: Not found (0.16.0 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 256, in rpc_fix_code
    return fix_code(source)
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/auto_pep8.py", line 21, in fix_code
    return autopep8.fix_code(code, apply_config=True)
AttributeError: 'module' object has no attribute 'fix_code'
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> `Autopep8..........: 0.9.1 (1.2.4 available)`

Could you try to upgrade to the latest version and try again?
