### ISSUE TITLE
Hitting an error whenever Elpy encounters method call on an instance created from imported library

### ISSUE THREAD

**Issue by mkrahal** [jorgenschaefer/elpy#1128]
Hello Jorgen,

I've been hitting a brick wall, where Elpy bugs out and returns an error, whenever i create an instance of a class and then try to use a method from said class on the instance I've created. Concretely, Elpy throws out an error whenever i type instance_name"."  As soon as the "dot" is typed, elpy returns a backend error. 

Im unsure but i believe this has something to do with the way in which elpy is attempting to lookup the method in the said class. I have reproduced the error below using BeautifulSoup as an example and included the error log.

Please advise on potential resolution options.

Thank you in advance for your input,
Regards,
Mike.

----------------------------------------------------------------------------------------------------------------------------------
`Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message



Configuration

Virtualenv........: global.venv (/home/xxx/yyy/virtualenvs/global.venv)
RPC Python........: 2.7.9 (/home/xxx/yyy/virtualenvs/global.venv/bin/python)
Interactive Python: python (/home/xxx/yyy/virtualenvs/global.venv/bin/python)
Emacs.............: 24.4.1
Elpy..............: 1.8.0
Jedi..............: 0.10.2
Rope..............: 0.10.5
Importmagic.......: 0.1.7
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/xxx/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 179, in completions
    completions = completion.completions()
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/api/completion.py", line 101, in completions
    return sorted(completions, key=lambda x: (x.name.startswith('__'),
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/api/completion.py", line 40, in filter_names
    len(like_name)
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/api/classes.py", line 407, in __init__
    super(Completion, self).__init__(evaluator, name)
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/api/classes.py", line 67, in __init__
    self._module = name.get_root_context()
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/evaluate/filters.py", line 23, in get_root_context
    return self.parent_context.get_root_context()
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/evaluate/instance.py", line 295, in parent_context
    return self._instance.create_instance_context(self.class_context, self.tree_name)
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/evaluate/instance.py", line 158, in create_instance_context
    parent_context = self.create_instance_context(class_context, scope)
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/xxx/yyy/virtualenvs/global.venv/local/lib/python2.7/site-packages/jedi/evaluate/instance.py", line 169, in create_instance_context
    raise NotImplementedError
NotImplementedError

Jedi Debug Information

[?]  dbg: eval_element <Name: soup@9,7>@(9, 7)
[?]   dbg: finder.filter_name "u'soup'" in (<ModuleContext: testing@1-11>): [<TreeNameDefinition: soup@(7, 0)>]@(9, 7)
[?]    dbg: eval_statement <ExprStmt: soup = BeautifulSoup(page.content, "html.parser")@7,0> (<Name: soup@7,0>)
[?]     dbg: eval_element PythonNode(power, [<Name: BeautifulSoup@7,7>, PythonNode(trailer, [<Operator: ( start=(7, 20)>, PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>]), <Operator: ) start=(7, 48)>])])@(7, 7)
[?]      dbg: finder.filter_name "u'BeautifulSoup'" in (<ModuleContext: testing@1-11>): [<TreeNameDefinition: BeautifulSoup@(2, 16)>]@(7, 0)
[?]      dbg: search_module 'bs4' in u'/home/xxx/testing.py'
[?]       dbg: finder.filter_name "u'BeautifulSoup'" in (<ModuleContext: bs4@1-530>): [<TreeNameDefinition: BeautifulSoup@(55, 6)>]@None
[?]       dbg: finder._names_to_types: [<TreeNameDefinition: BeautifulSoup@(55, 6)>] -> set([<ClassContext: <Class: BeautifulSoup@55-502>>])
[?]      dbg: after import: set([<ClassContext: <Class: BeautifulSoup@55-502>>])
[?]      dbg: finder._names_to_types: [<TreeNameDefinition: BeautifulSoup@(2, 16)>] -> set([<ClassContext: <Class: BeautifulSoup@55-502>>])
[?]     dbg: eval_trailer: PythonNode(trailer, [<Operator: ( start=(7, 20)>, PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>]), <Operator: ) start=(7, 48)>]) in scope <ClassContext: <Class: BeautifulSoup@55-502>>
[?]      dbg: execute: <ClassContext: <Class: BeautifulSoup@55-502>> <TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>
[?]      dbg: execute result: set([<TreeInstance of <ClassContext: <Class: BeautifulSoup@55-502>>(<TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>)>]) in <ClassContext: <Class: BeautifulSoup@55-502>>
[?]     dbg: eval_element result set([<TreeInstance of <ClassContext: <Class: BeautifulSoup@55-502>>(<TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>)>])
[?]    dbg: eval_statement result set([<TreeInstance of <ClassContext: <Class: BeautifulSoup@55-502>>(<TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>)>])
[?]   dbg: finder._names_to_types: [<TreeNameDefinition: soup@(7, 0)>] -> set([<TreeInstance of <ClassContext: <Class: BeautifulSoup@55-502>>(<TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>)>])
[?]  dbg: eval_element result set([<TreeInstance of <ClassContext: <Class: BeautifulSoup@55-502>>(<TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>)>])
[?] dbg: trailer completion contexts: set([<TreeInstance of <ClassContext: <Class: BeautifulSoup@55-502>>(<TreeArguments: PythonNode(arglist, [PythonNode(power, [<Name: page@7,21>, PythonNode(trailer, [<Operator: . start=(7, 25)>, <Name: content@7,26>])]), <Operator: , start=(7, 33)>, <String: "html.parser" start=(7, 35)>])>)>])
[?]  dbg: eval_element <Name: Tag@55,20>@(55, 20)
[?]   dbg: finder.filter_name "u'Tag'" in (<ClassContext: <Class: BeautifulSoup@55-502>>): [<TreeNameDefinition: Tag@(48, 4)>]@(55, 20)
[?]   dbg: search_module 'bs4.element' in paths ['/home/xxx/yyy/virtualenvs/global.venv/lib/python2.7/site-packages/bs4']
[?]    dbg: finder.filter_name "u'Tag'" in (<ModuleContext: element@3-1756>): [<TreeNameDefinition: Tag@(802, 6)>]@None
[?]    dbg: finder._names_to_types: [<TreeNameDefinition: Tag@(802, 6)>] -> set([<ClassContext: <Class: Tag@802-1565>>])
[?]   dbg: after import: set([<ClassContext: <Class: Tag@802-1565>>])
[?]   dbg: finder._names_to_types: [<TreeNameDefinition: Tag@(48, 4)>] -> set([<ClassContext: <Class: Tag@802-1565>>])
[?]  dbg: eval_element result set([<ClassContext: <Class: Tag@802-1565>>])
[?]  dbg: eval_element <Name: PageElement@802,10>@(802, 10)
[?]   dbg: finder.filter_name "'PageElement'" in (<ClassContext: <Class: Tag@802-1565>>): [<TreeNameDefinition: PageElement@(126, 6)>]@(802, 10)
[?]   dbg: finder._names_to_types: [<TreeNameDefinition: PageElement@(126, 6)>] -> set([<ClassContext: <Class: PageElement@126-685>>])
[?]  dbg: eval_element result set([<ClassContext: <Class: PageElement@126-685>>])
[?]  dbg: eval_element <Name: object@126,18>@(126, 18)
[?]   dbg: finder.filter_name "'object'" in (<ClassContext: <Class: PageElement@126-685>>): [<CompiledName: (<CompiledContextName: __builtin__>).object>]@(126, 18)
[?]   dbg: finder._names_to_types: [<CompiledName: (<CompiledContextName: __builtin__>).object>] -> set([<CompiledObject: <type 'object'>>])
[?]  dbg: eval_element result set([<CompiledObject: <type 'object'>>])
[?]  dbg: eval_element <Name: PY3K@1086,7>@(1086, 7)
[?]   dbg: finder.filter_name "'PY3K'" in (<ClassContext: <Class: Tag@802-1565>>): [<TreeNameDefinition: PY3K@(13, 0)>]@(1086, 7)
[?]    dbg: eval_statement <ExprStmt: PY3K = (sys.version_info[0] > 2)@13,0> (<Name: PY3K@13,0>)
[?]     dbg: eval_element PythonNode(atom, [<Operator: ( start=(13, 7)>, PythonNode(comparison, [PythonNode(atom_expr, [<Name: sys@13,8>, PythonNode(trailer, [<Operator: . start=(13, 11)>, <Name: version_info@13,12>]), PythonNode(trailer, [<Operator: [ start=(13, 24)>, <Number: 0 start=(13, 25)>, <Operator: ] start=(13, 26)>])]), <Operator: > start=(13, 28)>, <Number: 2 start=(13, 30)>]), <Operator: ) start=(13, 31)>])@(13, 7)
[?]      dbg: eval_element PythonNode(comparison, [PythonNode(atom_expr, [<Name: sys@13,8>, PythonNode(trailer, [<Operator: . start=(13, 11)>, <Name: version_info@13,12>]), PythonNode(trailer, [<Operator: [ start=(13, 24)>, <Number: 0 start=(13, 25)>, <Operator: ] start=(13, 26)>])]), <Operator: > start=(13, 28)>, <Number: 2 start=(13, 30)>])@(13, 8)
[?]       dbg: eval_element PythonNode(atom_expr, [<Name: sys@13,8>, PythonNode(trailer, [<Operator: . start=(13, 11)>, <Name: version_info@13,12>]), PythonNode(trailer, [<Operator: [ start=(13, 24)>, <Number: 0 start=(13, 25)>, <Operator: ] start=(13, 26)>])])@(13, 8)
[?]        dbg: finder.filter_name "'sys'" in (<ModuleContext: element@3-1756>): [<TreeNameDefinition: sys@(8, 7)>]@(13, 0)
[?]        dbg: search_module 'sys' in '/home/xxx/yyy/virtualenvs/global.venv/lib/python2.7/site-packages/bs4/element.py'
[?]        dbg: after import: set([<CompiledObject: <module 'sys' (built-in)>>])
[?]        dbg: finder._names_to_types: [<TreeNameDefinition: sys@(8, 7)>] -> set([<CompiledObject: <module 'sys' (built-in)>>])
[?]       dbg: eval_trailer: PythonNode(trailer, [<Operator: . start=(13, 11)>, <Name: version_info@13,12>]) in scope <CompiledObject: <module 'sys' (built-in)>>
[?]        dbg: finder.filter_name "'version_info'" in (<CompiledObject: <module 'sys' (built-in)>>): [<CompiledName: (<CompiledContextName: sys>).version_info>]@None
[?]        dbg: finder._names_to_types: [<CompiledName: (<CompiledContextName: sys>).version_info>] -> set([<CompiledObject: sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)>])
[?]        dbg: eval_element <Number: 0 start=(13, 25)>@(13, 25)
[?]        dbg: eval_element result set([<CompiledObject: 0>])
[?]       dbg: eval_element result set([])
[?]       dbg: eval_element <Number: 2 start=(13, 30)>@(13, 30)
[?]       dbg: eval_element result set([<CompiledObject: 2>])
[?]       dbg: execute: <CompiledObject: <type 'int'>> <ValuesArguments: []>
[?]       dbg: execute result: set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>]) in <CompiledObject: <type 'int'>>
[?]      dbg: calculate_children types set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>])
[?]      dbg: eval_element result set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>])
[?]     dbg: eval_element result set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>])
[?]    dbg: eval_statement result set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>])
[?]   dbg: finder._names_to_types: [<TreeNameDefinition: PY3K@(13, 0)>] -> set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>])
[?]  dbg: eval_element result set([<CompiledInstance of <CompiledObject: <type 'int'>>(<ValuesArguments: []>)>])

```

Reproduction:

```Python
import jedi

source = '''\
import requests
from bs4 import BeautifulSoup

url = "http://google.com"
page = requests.get(url)

soup = BeautifulSoup(page.content, "html.parser")

rows = soup.   <=============  This is where it systematically throws an error message

'''

script = jedi.Script(column=12, source=source, line=9, enyyy='utf-8', path=u'/home/xxx/testing.py')
script.completions()
```
`

**Comment by jorgenschaefer** [comment]
Thank you for the report! This is a problem with Jedi – if you can, try to use the development version of Jedi and see if the problem persists. I'm afraid I can not reproduce this locally, so it's likely a weird interaction with various installed libraries :-(

**Comment by gopar** [comment]
Jedi issue, not related to elpy. Closing
