### ISSUE TITLE
Flymake Configuration Error emacs termux

### ISSUE THREAD

**Issue by nubol23** [jorgenschaefer/elpy#1131]
hi, I'm using emacs on termux, i have no issues with running the code and the auto-comlete works perfect, however, every time I open a .py file i get the following error:
flymake configuration error has occurred while running (flake 8 /data/data/com.term
and unfortunately I can't see the full message.

i typed M-x elpy-config and in the syntax checker field it says
(/data/data/com.termux/files/usr/bin/flake8)

hope you could help me with this issue. 
Thanks.
Keep up the excellent work

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Does `C-c C-v` work, or produce any more legible error?

**Comment by nubol23** [comment]
C-c C-v produced the following error

-*- mode: compilation; default-directory: "~/Desktop/Python/" -*-
Compilation started at Wed May 17 00:46:07

flake8 /data/data/com.termux/files/home/Desktop/Python/a.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/synchronize.py", line 29, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/flake8/main/application.py", line 328, in run
    self._run(argv)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/flake8/main/application.py", line 315, in _run
    self.initialize(argv)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/flake8/main/application.py", line 303, in initialize
    self.make_file_checker_manager()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/flake8/main/application.py", line 229, in make_file_checker_manager
    checker_plugins=self.check_plugins,
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/flake8/checker.py", line 89, in init
    self.pool = multiprocessing.Pool(self.jobs, _pool_init)
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/pool.py", line 150, in init
    self._setup_queues()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/pool.py", line 243, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/queues.py", line 324, in init
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/synchronize.py", line 34, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

Compilation exited abnormally with code 1 at Wed May 17 00:46:08

**Comment by jorgenschaefer** [comment]
Well, that looks like as if `flake8` does not work on your platform or in that configuration. This is unrelated to Elpy, isn't it? Could you see why flake8 is failing there?
