### ISSUE TITLE
Elpy breaks with variables inside anonymous functions

### ISSUE THREAD

**Issue by Eskatrem** [jorgenschaefer/elpy#1148]
The following was automatically generated by Elpy

```
Error Message

u'x'

Configuration

Virtualenv........: None
RPC Python........: 2.7.12 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 25.2.2
Elpy..............: 1.8.0
Jedi..............: 0.9.0 (0.10.2 available)
Rope..............: 0.10.4 (0.10.5 available)
Importmagic.......: 0.1.7
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/samuel/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 515, in call_signatures
    stmt = self._get_under_cursor_stmt(call_txt, start_pos)
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 309, in _get_under_cursor_stmt
    user_stmt = self._parser.user_stmt()
  File "/usr/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/usr/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/usr/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/usr/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/usr/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'x'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
def test_function(my_list):
    return map(lambda x: my_list'''

script = jedi.Script(column=25, source=source, line=2, encoding='utf-8', path=u'/home/samuel/test.py')
script.call_signatures()

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> `Jedi..............: 0.9.0 (0.10.2 available)`

Could you try upgrading to the latest version of Jedi and see if the problem persists?

**Comment by Eskatrem** [comment]
Hi! Thanks for the quick reply!

I upgraded jedi (and rope, while I was at it), and now it's breaking because of the `map` keyword.

```
Error Message

u'map'

Configuration

Virtualenv........: None
RPC Python........: 2.7.12 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 25.2.2
Elpy..............: 1.8.0
Jedi..............: 0.10.2
Rope..............: 0.10.5
Importmagic.......: 0.1.7
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/samuel/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 515, in call_signatures
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 309, in _get_under_cursor_stmt
  File "/usr/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
  File "/usr/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 293, in user_stmt
  File "/usr/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 339, in module
  File "/usr/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
  File "/usr/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 283, in _parser
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 109, in __call__
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 257, in update
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 383, in _parse
  File "/usr/lib/python2.7/dist-packages/jedi/parser/fast.py", line 435, in _get_node
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 155, in __init__
  File "/usr/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 106, in parse
  File "/usr/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 269, in error_recovery
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 304, in _stack_removal
  File "/usr/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 298, in clear_names
KeyError: u'map'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
def test_function(my_list):
    return map(lambda x: x+1,my_list)


def test_function2(my_list):
    return map(lambda x: x+2, my_list)

def test_function3(my_list):
    return map(lambda my_var: my_var + 


'''

script = jedi.Script(column=39, source=source, line=9, encoding='utf-8', path=u'/home/samuel/test.py')
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Did you restart the RPC process (or Emacs)? E.g. using `M-x elpy-rpc-restart`?

**Comment by Eskatrem** [comment]
OK, it works fine after running `elpy-rpc-restart`. Thanks a lot for coming back to me so quickly, and for developing elpy.

Best,
Sam

**Comment by jorgenschaefer** [comment]
You are very welcome! Glad it works now, and enjoy Elpy :-)
