### ISSUE TITLE
Flake8 has an AttributeError.

### ISSUE THREAD

**Issue by dineshadepu** [jorgenschaefer/elpy#1485]
# Summary
When I try to open a python file in Emacs, I get 
```
Flymake: Configuratoin error has occured. Flymake will be switched off.
```

# Steps to reproduce
I don't know. Suddenly this problem started.

# My Configuration
Ubuntu 16.04

## Result of `(elpy-config)`
```
Virtualenv........: None
RPC Python........: 3.5.2 (/home/dinesh/.virtualenvs/sph3/bin/python)
Interactive Python: python (/home/dinesh/.virtualenvs/sph3/bin/python)
Emacs.............: 25.1.1
Elpy..............: 1.17.0
Jedi..............: 0.12.1 (0.13.1 available)
Rope..............: Not found (0.11.0 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: 1.4 (1.4.2 available)
Yapf..............: 0.24.0
Syntax checker....: flake8 (/home/dinesh/.virtualenvs/sph3/bin/flake8)
```

## Elpy configuration in my init.el
```
  (use-package elpy
    ;; :load-path "~/.emacs.d/elisp/elpy/"
    :ensure t
    :diminish elpy-mode
    :config(progn
	     ;; (setq elpy-rpc-python-command "python3")
	     ;; (setq 'python-indent-offset 4)
	     (setq company-minimum-prefix-length 1)
	     (setq python-shell-completion-native-enable nil)
	     (setq elpy-rpc-timeout 10)
	     (setq elpy-rpc-backend "jedi")
	     ;; (elpy-use-ipython)
	     ;; (elpy-clean-modeline)
	     (elpy-enable)))
  (use-package virtualenv
    :ensure)
  (let ((virtualenv-workon-starts-python nil))
    (virtualenv-workon "sph3"))
  (delete `elpy-module-highlight-indentation elpy-modules)
```
## Some additional information

```
(sph3)  
 
 --------------------------------------
 dinesh@Personal /home/dinesh $  
|  Personal desktop => flake8 --v
Traceback (most recent call last):
  File "/home/dinesh/.virtualenvs/sph3/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/flake8/main/application.py", line 17, in <module>
    from flake8.plugins import manager as plugin_manager
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/flake8/plugins/manager.py", line 5, in <module>
    import pkg_resources
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/dinesh/.virtualenvs/sph3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
(sph3)  
```

**Comment by dineshadepu** [comment]
I am able to solve it. I have to upgrade my `pip` and `setuptools`

```
pip install --upgrade pip
pip install --upgrade setuptools
```

**Comment by gopar** [comment]
Out of curiousity, what version was your pip and setuptools at?

**Comment by dineshadepu** [comment]
> Out of curiousity, what version was your pip and setuptools at?

OK. I tried again.

Verson of `pip` is `9.0.1` and `setuptools` is at `28.8.0`

**Comment by gopar** [comment]
Nice, Thanks!
