### ISSUE TITLE
Flake 8 invalid continuation error

### ISSUE THREAD

**Issue by dineshadepu** [jorgenschaefer/elpy#1642]
# Summary
I am working on this configuration for a long time. Suddenly I started getting this error. 

```

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/utils.py", line 201, in _stdin_get_value_py3
    return io.StringIO(stdin_value.decode(coding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 2839: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/main/application.py", line 393, in run
    self._run(argv)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/main/application.py", line 381, in _run
    self.run_checks()
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/main/application.py", line 298, in run_checks
    self.file_checker_manager.start(files)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/checker.py", line 344, in start
    self.make_checkers(paths)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/checker.py", line 242, in make_checkers
    checker for checker in checkers if checker.should_process
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/checker.py", line 242, in <listcomp>
    checker for checker in checkers if checker.should_process
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/checker.py", line 239, in <genexpr>
    if should_create_file_checker(filename, argument)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/checker.py", line 379, in __init__
    self.processor = self._make_processor()
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/checker.py", line 394, in _make_processor
    return processor.FileProcessor(self.filename, self.options)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/processor.py", line 60, in __init__
    self.lines = self.read_lines()
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/processor.py", line 300, in read_lines
    lines = self.read_lines_from_stdin()
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/processor.py", line 333, in read_lines_from_stdin
    return utils.stdin_get_value().splitlines(True)
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/utils.py", line 214, in stdin_get_value
    stdin_value = _stdin_get_value_py3()
  File "/home/dinesh/.virtualenvs/sph3/local/lib/python3.6/site-packages/flake8/utils.py", line 203, in _stdin_get_value_py3
    return io.StringIO(stdin_value.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 2839: invalid continuation byte

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```
# Steps to reproduce
I don't know, this was all of a sudden

# My configuration
## OS
Ubuntu 18.04

## Result of `(elpy-config)`
```
Elpy Configuration

Virtualenv........: sph3 (/home/dinesh/.virtualenvs/sph3)
RPC Python........: 3.6.5 (/home/dinesh/.virtualenvs/sph3/bin/python)
Interactive Python: python (/home/dinesh/.virtualenvs/sph3/bin/python)
Emacs.............: 26.1
Elpy..............: 1.28.0
Jedi..............: 0.15.1
Rope..............: 0.14.0
Autopep8..........: 1.4.4
Yapf..............: 0.28.0
Black.............: Not found (19.3b0 available)
Syntax checker....: flake8 (/home/dinesh/.virtualenvs/sph3/bin/flake8)

The black package is not available. Commands using this will not work.
```

## Elpy configuration in my init.el
```
(use-package virtualenvwrapper
  :config
  (venv-initialize-interactive-shells) ;; if you want interactive shell support
  (venv-initialize-eshell) ;; if you want eshell support
  (setq venv-location "~/.virtualenvs")
  )
(use-package elpy
  :diminish elpy-mode
  :config(progn
           ;; (setq elpy-rpc-python-command "python3")
           ;; (setq 'python-indent-offset 4)
           (setq company-minimum-prefix-length 1)
           (setq python-shell-completion-native-enable nil)
           (setq elpy-rpc-timeout 10)
           ;; (elpy-use-ipython)
           ;; (elpy-clean-modeline)
           (elpy-enable)))
(use-package virtualenv)

(let ((virtualenv-workon-starts-python nil))
  (virtualenv-workon "sph3"))
(delete `elpy-module-highlight-indentation elpy-modules)

(when (require 'elpy nil t)
  (elpy-enable))

```

**Comment by dineshadepu** [comment]
This got solved by installing `flake8` globally using `pip`. It was failing on the first hand while installing through `apt`.

Closing.
