### ISSUE TITLE
Output from Backend  There was some unexpected output from the Elpy backend....

### ISSUE THREAD

**Issue by sidipia** [jorgenschaefer/elpy#1651]
Good weekend,
This window appears when I start "elpy-mode" in a Python file:

**Steps to reproduce:**
1. Emacs clean
2. Add melpa repository
3. Install elpy
4. Open python file and run elpy-mode
5. Move cursor some characters

`Output from Backend

There was some unexpected output from the Elpy backend. This is
usually not a problem and should usually not be reported as a bug with
Elpy. You can safely hide this buffer and ignore it. You can also see
the output below in case there is an actual problem.

Output
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sidipia/.emacs.d/elpa/elpy-20190906.2246/elpy/__main__.py", line 16, in <module>
    from elpy.server import ElpyRPCServer
  File "/home/sidipia/.emacs.d/elpa/elpy-20190906.2246/elpy/server.py", line 16, in <module>
    from elpy.blackutil import fix_code as fix_code_with_black
  File "/home/sidipia/.emacs.d/elpa/elpy-20190906.2246/elpy/blackutil.py", line 6, in <module>
    from pkg_resources import parse_version
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2033, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2095, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
OSError: [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/lazy_object_proxy-1.4.2.dist-info'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sidipia/.emacs.d/elpa/elpy-20190906.2246/elpy/__main__.py", line 16, in <module>
    from elpy.server import ElpyRPCServer
  File "/home/sidipia/.emacs.d/elpa/elpy-20190906.2246/elpy/server.py", line 16, in <module>
    from elpy.blackutil import fix_code as fix_code_with_black
  File "/home/sidipia/.emacs.d/elpa/elpy-20190906.2246/elpy/blackutil.py", line 6, in <module>
    from pkg_resources import parse_version
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2033, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2095, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
OSError: [Errno 13] Permission denied: '/usr/lib64/python2.7/site-packages/lazy_object_proxy-1.4.2.dist-info'
`
**My configuration:**

**.emacs:**

`(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (elpy))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
`
**elpy-config:**

`Elpy Configuration

Emacs.............: 26.2
Elpy..............: 1.31.0
Virtualenv........: None
Interactive Python: python 2.7.16 (/usr/bin/python)
RPC Python........: python 2.7.16 (/usr/bin/python)
 Jedi.............: 0.14.1 (0.15.1 available)
 Rope.............: Not found (0.14.0 available)
 Autopep8.........: 1.4.4
 Yapf.............: 0.28.0
 Black............: Not found (19.3b0 available)
Syntax checker....: flake8 (/home/sidipia/.local/bin/flake8)

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.

There is a newer version of Jedi available.

[run] easy_install --user jedi

The black package is not available. Commands using this will not work.

[run] easy_install --user black`

Thanks for your time

**Comment by galaunay** [comment]
Hi, 

Elpy fails to import the `pkg_resources` package, and It looks like a permission problem.

Could you try importing the `pkg_resources` and `lazy_object_proxy` packages from a python interpreter (outside of Emacs) ?
``` python
>>> import pkg_resources
>>> from pkg_resources import parse_version
>>> import lazy_object_proxy
```

If it fails, I would suggest reinstalling the `lazy_object_proxy` packages from pip:
``` bash
sudo pip install --force-reinstall lazy-object-proxy 
```

Another solution would be to use a virtualenv, it will avoid permission problems.
