### ISSUE TITLE
Failing at setting up jypter as repl

### ISSUE THREAD

**Issue by gsime1** [jorgenschaefer/elpy#1842]
I am trying to get jupyter to be the default REPL, but I am getting errors. 

I installed prelude, and I want to actually change the python settings to the tutorial described here in realpython (I want to use `elpy` and not `anaconda-mode`): https://realpython.com/emacs-the-best-python-editor/

So I go ahead and as described in the instructions I create a `.el` file in `~/.emacs.d/personal` and call it `my_python_init.el`. 

In this config file I add these lines:

```
;; Use IPython for REPL

(setq elpy-rpc-python-command "python3")

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")
```
 
But I get this error:
```
Traceback (most recent call last):
  File "/home/gabri/.local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/home/gabri/.local/lib/python3.8/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/home/gabri/.local/lib/python3.8/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-console` not found.
1
```
So i run elpy-config and to check - but the paths look fine to me. 
```
Elpy Configuration

Emacs.............: 26.3
Elpy..............: 1.34.0
Virtualenv........: None
Interactive Python: jupyter 4.6.3 (/home/gabri/.local/bin/jupyter)
RPC virtualenv....: rpc-venv (/home/gabri/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.8.5 (/home/gabri/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.17.2
 Rope.............: 0.18.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: flake8 (/home/gabri/.local/bin/flake8)

Warnings

You have not activated a virtual env. While Elpy supports this, it is
often a good idea to work inside a virtual env. You can use M-x
pyvenv-activate or M-x pyvenv-workon to activate a virtual env.
```

If you got to the end i appreciate your time already! :) And if anyone knows what I am missing I would be really grateful. 

My config:
```
;; .emacs.d/personal/my_python_init.el

;; ===================================
;; MELPA Package Support
;; ===================================
;; Enables packaging support
(require 'package)

;; Adds the Melpa archive to the list of available repositories
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)

;; Initializes the package infrastructure
(package-initialize)

;; If there are no archived package contents, refresh them
(when (not package-archive-contents)
  (package-refresh-contents))

;; Installs packages
;;
;; myPackages contains a list of package names
(defvar myPackages
  '(better-defaults                 ;; Setup some better Emacs defaults
    elpy                            ;; Emacs Lisp Python Environment
    ein                             ;; Emacs iPython Notebook
    flycheck                        ;; On the fly syntax checking
    py-autopep8                     ;; Run autopep8 on save
    blacken                         ;; Black formatting on save
    magit                           ;; Git integration
    material-theme                  ;; Theme
    solarized-theme 
    jedi                            ;; Better auto completion
    )
  )

;; Scans the list in myPackages
;; If the package listed is not already installed, install it
(mapc #'(lambda (package)
          (unless (package-installed-p package)
            (package-install package)))
      myPackages)

;; ====================================
;; Basic Customization
;; ====================================

(setq inhibit-startup-message t)  ;; Hide the startup message
(load-theme 'solarized-dark t)    ;; Load theme
(global-linum-mode t)             ;; Enable line numbers globally

;; ====================================
;; DEVELOPMENT SETUP
;; ====================================

;; Enable elpy

(setq elpy-rpc-python-command "python3")

(elpy-enable)

;; Use IPython for REPL // cannot get this to work

(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
  (add-to-list 'python-shell-completion-native-disabled-interpreters 
 	      "jupyter")

(defalias 'workon 'pyvenv-workon)

;; Enable Flycheck
(when (load "flycheck" t t)
  (setq elpy-modules (delq 'elpy-module-flymake elpy-modules))
  (add-hook 'elpy-mode-hook 'flycheck-mode))

;; enable emacs 26 flymake indicators in an otherwise light mode-line
(setq elpy-remove-modeline-lighter t)

(advice-add 'elpy-modules-remove-modeline-lighter
	    :around (lambda (fun &rest args)
		      (unless (eq (car args) 'flymake-mode)
			(apply fun args))))

;; elpy autoformatting upon saving. 
(add-hook 'elpy-mode-hook (lambda ()
			    (add-hook 'before-save-hook
				      'elpy-format-code nil t)))
;; Enable jedi
 (require 'jedi)
 (add-hook 'elpy-mode-hook 'jedi:setup)

;; User-Defined init.el ends here

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
    (quote
      (blacken flycheck elpy solarized-theme material-theme better-defaults jedi magit py-autopep8 ein ))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by galaunay** [comment]
It looks like `jupyter-console` is not installed.
You should see the same message when running `jupyter console` in a terminal (if not, then it is a proper bug in Elpy).

Depending on you OS, you may have a way to install jupyter-console from your package manager. You can also install it with pip:`pip install jupyter-console`.

**Comment by gsime1** [comment]
Thanks - sorry for posting such trivial q. :/
