### ISSUE TITLE
Auto complete incorrect!!

### ISSUE THREAD

**Issue by chenyidao110** [jorgenschaefer/elpy#1871]
# Summary
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

__init__() got an unexpected keyword argument 'source'

Configuration

Emacs.............: 27.1
Elpy..............: 1.35.0
Virtualenv........: None
Interactive Python: python 3.9.1 (/usr/bin/python)
RPC virtualenv....: rpc-venv (/home/xiaobai/.emacs.d/elpy/rpc-venv)
 Python...........: python 3.9.1 (/home/xiaobai/.emacs.d/elpy/rpc-venv/bin/python)
 Jedi.............: 0.18.0
 Rope.............: 0.18.0
 Autopep8.........: 1.5.4
 Yapf.............: 0.30.0
 Black............: 20.8b1
Syntax checker....: Not found (flake8)

Traceback

Traceback (most recent call last):
  File "/home/xiaobai/.emacs.d/elpa/elpy-1.35.0/elpy/jedibackend.py", line 368, in run_with_debug
    script = jedi.Script(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaobai/.emacs.d/elpa/elpy-1.35.0/elpy/jedibackend.py", line 401, in run_with_debug
    script = jedi.Script(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

# Steps to reproduce


# My configuration
debian sid
kernel: 5.9.0-5-amd64

## Result of `(elpy-config)`
Elpy Configuration
  2 
  3 Emacs.............: 27.1
  4 Elpy..............: 1.35.0
  5 Virtualenv........: None
  6 Interactive Python: python 3.9.1 (/usr/bin/python)
  7 RPC virtualenv....: rpc-venv (/home/xiaobai/.emacs.d/elpy/rpc-venv)
  8  Python...........: python 3.9.1 (/home/xiaobai/.emacs.d/elpy/rpc-venv/bin/python)
  9  Jedi.............: 0.18.0
 10  Rope.............: 0.18.0
 11  Autopep8.........: 1.5.4
 12  Yapf.............: 0.30.0
 13  Black............: 20.8b1
 14 Syntax checker....: Not found (flake8)
 15 
 16 Warnings
 17 
 18 You have not activated a virtual env. It is not mandatory but often a
 19 good idea to work inside a virtual env. You can use `M-x
 20 pyvenv-activate` or `M-x pyvenv-workon` to activate one.
 21 
 22 The configured syntax checker (flake8) could not be found. Elpy uses
 23 this program to provide syntax checks of your code. You can either
 24 install it, or select another one using `elpy-syntax-check-command`.
 25 
 26 [Install flake8]
 27 
 28 Options
 29 
 30 Square brackets indicate buttons; type RET or click mouse-1 on a
 31 button to invoke its action.  Invoke [+] to expand a group, and [-] to
 32 collapse an expanded group.  Invoke the [Group], [Face], and [Option]
 33 buttons below to edit that item in another window.
 34 
 35 [+]-- [Group] Elpy
 36 [+]-- [Group] Python
 37 [+]-- [Group] Virtual Environments (Pyvenv)
 38 [+]-- [Group] Completion (Company)
 39 [+]-- [Group] Call Signatures (ElDoc)
 40 [+]-- [Group] Inline Errors (Flymake)
 41 [+]-- [Group] Code folding (hideshow)
 42 [ ]-- [Group] Snippets (YASnippet)
 43 [+]-- [Group] Directory Grep (rgrep)
 44 [+]-- [Group] Search as You Type (ido)
 45 [+]-- [Group] Django extension
 46 [+]-- [Group] Autodoc extension

## Elpy configuration in my init.el
(with-eval-after-load 'python
  ;; run command `pip install jedi flake8 importmagic` in shell,
  ;; or just check https://github.com/jorgenschaefer/elpy
  (unless (or (is-buffer-file-temp)
              (not buffer-file-name)
              ;; embed python code in org file
              (string= (file-name-extension buffer-file-name) "org"))
    (elpy-enable)
    ;; If you don't like any hint or error report from elpy,
    ;; set `elpy-disable-backend-error-display' to t.
    (setq elpy-disable-backend-error-display nil))
  ;; http://emacs.stackexchange.com/questions/3322/python-auto-indent-problem/3338#3338
  ;; emacs 24.4+
  (setq electric-indent-chars (delq ?: electric-indent-chars)))

(provide 'init-python)

**Comment by sten0** [comment]
@galaunay to me this looks like the Jedi 0.17 -> 0.18 compat break.  For reference, here is iPython's issue on the topic: https://github.com/ipython/ipython/issues/12740

**Comment by rlbr** [comment]
I am experiencing this issue as well. Downgrading jedi fixed it for me.
