### ISSUE TITLE
error in process sentinel: elpy-rpc--default-error-callback: peculiar error: "exited abnormally with code 1"

### ISSUE THREAD

**Issue by ItsNilDev** [jorgenschaefer/elpy#1936]
# Summary
Whenever I open any python file this error shows up and emacs freezes for like ~1.5 seconds and it happens when I move the cursor.

# Steps to reproduce
Open a python file.
Move around.

# My configuration
A pretty minimum one: 
```
  (use-package elpy
     :ensure t
     :init
     (elpy-enable))
```
     
I also added this that I found in other issues but they didn't help.
```
  (add-to-list 'process-coding-system-alist '("python" . (utf-8 . utf-8)))
  (setq elpy-rpc-python-command "python3")
```
## OS
Arch linux with lts-kernel which is (Linux 5.10.66-1-lts)

## Result of `(elpy-config)`
```
Emacs.............: 27.2
Elpy..............: 1.35.0
Virtualenv........: None
Interactive Python: python 3.9.7 (/usr/bin/python)
RPC virtualenv....: rpc-venv (/home/pouridev/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.9.7 (/home/pouridev/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: Not found (0.18.0 available)
 Autopep8.........: Not found (1.5.7 available)
 Yapf.............: Not found (0.31.0 available)
 Black............: Not found (21.9b0 available)
Syntax checker....: Not found (flake8)
```
Emacs is complaining that `~/.local.bin/` is not in my path but it actually is.
I added it via `export PATH=~/.local/bin:$PATH` in my zshrc.

**Comment by PaulRudin** [comment]
I'm getting this as well - fresh install of ubuntu 20.04 with emacs 27.1. elpy-config:
```
Elpy Configuration

Emacs.............: 27.1
Elpy..............: 1.35.0
Virtualenv........: None
Interactive Python: python3 3.9.5 (/usr/bin/python3)
RPC virtualenv....: rpc-venv (/home/paul/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.9.5 (/home/paul/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: Not found (0.18.0 available)
 Autopep8.........: Not found (1.5.7 available)
 Yapf.............: Not found (0.31.0 available)
 Black............: Not found (21.9b0 available)
Syntax checker....: Not found (flake8)
```
I tried adding the following to init.el (suggested elsewhere) but it doesn't make any difference:
```
(setenv "PYTHONIOENCODING" "utf-8")
(add-to-list 'process-coding-system-alist '("python" . (utf-8 . utf-8)))
(add-to-list 'process-coding-system-alist '("elpy" . (utf-8 . utf-8)))
(add-to-list 'process-coding-system-alist '("flake8" . (utf-8 . utf-8)))
```

**Comment by PaulRudin** [comment]
Here's the backtrace with debug on error turned on:
```
Debugger entered--Lisp error: (process-sentinel "exited abnormally with code 1")
  signal(process-sentinel ("exited abnormally with code 1"))
  elpy-rpc--default-error-callback((process-sentinel "exited abnormally with code 1"))
  elpy-promise-reject([*elpy-promise* #f(compiled-function (result) #<bytecode 0x158401890879>) elpy-rpc--default-error-callback #<buffer  *elpy-rpc [project:~/Dropbox/xxx/tools/ environment:/usr]*> nil] (process-sentinel "exited abnormally with code 1"))
  #f(compiled-function (call-id promise) #<bytecode 0x158401670abd>)(1 [*elpy-promise* #f(compiled-function (result) #<bytecode 0x158401890879>) elpy-rpc--default-error-callback #<buffer  *elpy-rpc [project:~/Dropbox/xxx/tools/ environment:/usr]*> nil])
  maphash(#f(compiled-function (call-id promise) #<bytecode 0x158401670abd>) #<hash-table equal 2/65 0x15840166721d>)
  elpy-rpc--sentinel(#<process  *elpy-rpc [project:~/Dropbox/xxx/tools/ environment:/usr]*> "exited abnormally with code 1\n")
```

**Comment by FloraSun9101** [comment]
[possible solution] I encountered the same issue, it seems that it is because rpc is not started properly. I run the following command and it fixes the problem for me:
`M-x elpy-rpc-reinstall-virtualenv`
Previously my config is pretty much like PaulRudin's, with Jedi, Autopep8, Yapf, Black and Syntax checher not found. And this is my config after running the command:
`Elpy Configuration

Emacs.............: 27.2
Elpy..............: 1.35.0
Virtualenv........: py37 (/Users/flora/.python_venv/py37/)
Interactive Python: python3 3.7.4 (/Users/flora/.python_venv/py37/bin/python3)
RPC virtualenv....: rpc-venv (/Users/flora/.emacs.d/elpy/rpc-venv)
 Python...........: python3 3.7.3 (/Users/flora/.emacs.d/elpy/rpc-venv/bin/python3)
 Jedi.............: 0.18.0
 Autopep8.........: 1.6.0
 Yapf.............: 0.31.0
 Black............: 21.9b0
Syntax checker....: pyflakes (/Library/Frameworks/Python.framework/Versions/3.7/bin/pyflakes)`
worth trying!

**Comment by ghosh-r** [comment]
https://github.com/jorgenschaefer/elpy/issues/1936#issuecomment-954994911 solves my problem, but not directly.

When I ran  `M-x elpy-rpc-reinstall-virtualenv` , it did not solve my problem, it showed that I needed virtualenv or venv in my system. So, I quit, and installed the `python3-venv` package through `apt`. Then I ran the same, and this time, I was asked if I wanted to automatically install all the dependencies for RPC. I chose yes, and I do not see the error anymore.

**Comment by ghosh-r** [comment]
This can be marked as close now.

**Comment by exarkun** [comment]
If you look at `*Elpy Output*` then you'll often find more detailed information.  For example, I just discovered that (as far as I can tell) you need `pkg_resources` (from `setuptools`) before elpy can discover the installed version of anything.  If it is missing, you'll get the error from the issue summary.

**Comment by ItsNilDev** [comment]
This issue has been fixed for me, but I got bunch of other problems to deal with apparently..

**Comment by CadeMichael** [comment]
Whenever using a virtual environment with elpy I get this error almost as soon as i activate the env.

**Comment by canicola** [comment]
Hi all, I still have a problem regarding this issue. Not sure if I should open a new one or follow up here.
I try to setup Emacs / Elpy in a working environment which makes it a bit harder. I don't have any admin rights and on top it is a Windows machine. I'm running Emacs / Elpy at home on Linux without any issue.

**My configuration / Setup**

- Windows 10 Pro
- Emacs 28.1
- Elpy 20220627.1416

```
(elpy-enable)
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")
(setq elpy-shell-use-project-root nil)

;;;; PYENV
;; pyenv package to support virtual env within elpy
(pyenv-mode)
(setq elpy-shell-unbuffered nil)
```

**ELPY Config**
After activating the desired virtualenv my elpy-config looks like this

```
Elpy Configuration

 

Emacs.............: 28.1

Elpy..............: 1.35.0

Virtualenv........: srv_phd (c:/Users/ca/.conda/envs/srv_phd/)

Interactive Python: ipython 8.4.0 (c:/Program Files/Python39/Scripts/ipython.exe)

RPC virtualenv....: rpc-venv (c:/Users/ca/AppData/Roaming/.emacs.d/elpy/rpc-venv)

Python...........: c:/Windows/py.exe 3.9.7 (c:/Windows/py.exe)

Jedi.............: Not found

Autopep8.........: Not found

Yapf.............: Not found

Black............: Not found

Syntax checker....: Not found (flake8)
```

which seems already weird as jedi, auto-complete etc is installed (list-packages)

 ```
 auctex                         13.1.3         installed             Integrated environment for *TeX*

  auto-complete                  20220105.439   installed             Auto Completion for GNU Emacs

  elpy                           20220627.1416  installed             Emacs Python Development Environment

  flymd                          20160617.1214  installed             On the fly markdown preview

  iedit                          20220216.717   installed             Edit multiple regions in the same way simultaneously.

  jedi                           20191011.1750  installed             a Python auto-completion for Emacs

  markdown-mode                  20220708.6     installed             Major mode for Markdown-formatted text

  material-theme                 20210904.1226  installed             A Theme based on the colors of the Google Material Design

  multi-term                     20200514.428   installed             Managing multiple terminal buffers in Emacs.

  org-trello                     20210314.1901  installed             Minor mode to synchronize org-mode buffer and trello board

  pyenv-mode-auto                20180620.1252  installed             Automatically activates pyenv version if .python-version file exists.

  company                        20220702.1935  dependency            Modular text completion framework

  concurrent                     20161229.330   dependency            Concurrent utility functions for emacs lisp

  ctable                         20210128.629   dependency            Table component for Emacs Lisp

  dash                           20220608.1931  dependency            A modern list library for Emacs

  deferred                       20170901.1330  dependency            Simple asynchronous functions for emacs lisp

  epc                            20140610.534   dependency            A RPC stack for the Emacs Lisp

  f                              20220608.943   dependency            Modern API for working with files and directories

  highlight-indentation          20210221.1418  dependency            Minor modes for highlighting indentation

  jedi-core                      20210503.1315  dependency            Common code of jedi.el and company-jedi.el

  popup                          20211231.1823  dependency            Visual Popup User Interface

  pyenv-mode                     20200518.1521  dependency            Integrate pyenv with python-mode

  python-environment             20150310.853   dependency            virtualenv API for Emacs Lisp

  pythonic                       20210122.1247  dependency            Utility functions for writing pythonic emacs package.

  pyvenv                         20211014.707   dependency            Python virtual environment interface

  request                        20220614.1604  dependency            Compatible layer for URL request

  request-deferred               20220614.1604  dependency            Wrap request.el by deferred

  s                              20210616.619   dependency            The long lost Emacs string manipulation library.

  yasnippet                      20200604.246   dependency            Yet another snippet extension for Emacs
```

Now as soon as I want to execute a python statement I get the error message

```
error in process sentinel: elpy-rpc--default-error-callback: peculiar error: "exited abnormally with code 1"

error in process sentinel: peculiar error: "exited abnormally with code 1"
```

If I try to run the proposed `M-x elpy-rpc-reinstall-virtualenv` I'm getting asked to automatically install the RPC dependencies from PyPI. Clicking yes leads to an error as I can't install via PyPI. I would need to pass somehow a ZScaler certificate we need to use at work:

```
Elpy is creating the RPC virtualenv (’c:/Users/camenzindn/AppData/Roaming/.emacs.d/elpy/rpc-venv’)

Automatically install the RPC dependencies from PyPI (needed for completion, autoformatting and documentation) ? (y or n) y

Elpy is installing the RPC dependencies...

Elpy failed to install some of the RPC dependencies, please use ‘elpy-config’ to install them.

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jedi/

WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jedi/

WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jedi/

WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jedi/

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jedi/

Could not fetch URL https://pypi.org/simple/jedi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Max retries exceeded with url: /simple/jedi/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

ERROR: Could not find a version that satisfies the requirement jedi (from versions: none)

ERROR: No matching distribution found for jedi

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='[pypi.org](http://pypi.org/)', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

```
How can I resolve this issue? I'm not very familiar with windows but spent alread too much time and want to get it work. Any help / insight would be very much appreciated!

**Comment by FloraSun9101** [comment]
According to exarkun's [comment](https://github.com/jorgenschaefer/elpy/issues/1936#issuecomment-1010038552), rpc cannot be properly setup because of lacking setuptools from python. So if u cannot `rpc-reinstall`, then maybe try install the setuptools(a package of python) and see if it can solve the problem?

**Comment by canicola** [comment]
@FloraSun9101 thanks for the comment. I've tried this already. I have installed the `setuptools` in the virtualenv I want to work on (via conda)

**Comment by FloraSun9101** [comment]
Should the setuptools be in the local python or virtualenv? I somehow feels that the setuptools should be local but definitely no experts in os/emacs...

**Comment by badbob** [comment]
For some reason Python installation installed by `elpy-rpc-reinsall-virtualenv` are broken. pip3 doesn't work:
```
~/.emacs.d/elpy/rpc-venv/bin$ ./pip3              
Traceback (most recent call last):                                                                   
  File "/home/badbob/.emacs.d/elpy/rpc-venv/bin/./pip3", line 5, in <module>
    from pip._internal.cli.main import main                                                          
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser                                                                                                                                           
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions                                                                                                                                                               
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/cli/parser.py", line 12, in <module>                                      
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/configuration.py", line 20, in <module>
    from pip._internal.exceptions import (                                                           
  File "/home/badbob/.emacs.d/elpy/rpc-venv/lib/python3.10/site-packages/pip/_internal/exceptions.py", line 13, in <module>
    from pip._vendor.requests.models import Request, Response             
ModuleNotFoundError: No module named 'pip._vendor.requests' 
```
This can be fixed by:
```
~/.emacs.d/elpy/rpc-venv/bin$ curl -sS https://bootstrap.pypa.io/get-pip.py | ./python3                                   
Collecting pip                                                                                       
  Downloading pip-22.2.2-py3-none-any.whl (2.0 MB) 
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 1.4 MB/s eta 0:00:00
Installing collected packages: pip                                                                                                                                                                         
  Attempting uninstall: pip                                                                          
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:                                                                         
      Successfully uninstalled pip-22.0.2                                                            
Successfully installed pip-22.2.2                        
```

**Comment by wenijinew** [comment]
After manually installed all dependencies which were not found in elpy config list, this problem disappeared.
` Jedi.............: Not found
 Autopep8.........: Not found
 Yapf.............: Not found
 Black............: Not found`

`Jedi.............: 0.18.2                                                                                                                                                                                                                                              Autopep8.........: 2.0.2                                                                                                                                                                                                                                               Yapf.............: 0.32.0                                                                                                                                                                                                                                              Black............: 23.1.0`
