### ISSUE TITLE
error when opening new buffer

### ISSUE THREAD

**Issue by laydros** [jorgenschaefer/elpy#382]
This popped up when I opened a new buffer with a python 

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

Error Message

__abstractmethods__

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.5.1
Jedi..............: 0.8.1-final0
Rope..............: 0.9.2
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/laydros/.emacs.d/elpa/elpy-20140810.7/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/laydros/.emacs.d/elpa/elpy-20140810.7/elpy/server.py", line 81, in rpc_get_calltip
    get_source(source), offset)
  File "/home/laydros/.emacs.d/elpa/elpy-20140810.7/elpy/server.py", line 46, in _call_backend
    return meth(*args, **kwargs)
  File "/home/laydros/.emacs.d/elpa/elpy-20140810.7/elpy/ropebackend.py", line 159, in rpc_get_calltip
    remove_self=True)
  File "/usr/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 98, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/usr/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 448, in get_calltip
    pyobject = pyobject['__init__'].get_object()
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 27, in __getitem__
    return self.get_attribute(key)
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 17, in get_attribute
    if name not in self.get_attributes():
  File "/usr/lib/python2.7/dist-packages/rope/base/utils.py", line 10, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/usr/lib/python2.7/dist-packages/rope/base/builtins.py", line 81, in get_attributes
    result = _object_attributes(self.builtin, self)
  File "/usr/lib/python2.7/dist-packages/rope/base/builtins.py", line 111, in _object_attributes
    child = getattr(obj, name)
AttributeError: __abstractmethods__

**Comment by jorgenschaefer** [comment]
Any update on this?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I will close this issue. Please do not hesitate to re-open this or a open a new one if you have further problems. Enjoy Elpy!
