### ISSUE TITLE
Django test runner

### ISSUE THREAD

**Issue by Chedi** [jorgenschaefer/elpy#387]
Hi,

I had a minor issue when running the tests with the default runner set to Django discover.

```shell
-*- mode: compilation; default-directory: "/var/www/zeus/" -*-
Compilation started at Fri Oct 31 18:49:54

django-admin.py test --noinput
Traceback (most recent call last):
  File "/var/www/ve/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/var/www/ve/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/commands/test.py", line 8, in <module>
    from django.test.utils import get_runner
  File "/var/www/ve/lib/python2.7/site-packages/django/test/__init__.py", line 5, in <module>
    from django.test.client import Client, RequestFactory
  File "/var/www/ve/lib/python2.7/site-packages/django/test/client.py", line 11, in <module>
    from django.contrib.auth import authenticate, login, logout, get_user_model
  File "/var/www/ve/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 6, in <module>
    from django.middleware.csrf import rotate_token
  File "/var/www/ve/lib/python2.7/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/var/www/ve/lib/python2.7/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import get_cache
  File "/var/www/ve/lib/python2.7/site-packages/django/core/cache/__init__.py", line 69, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/var/www/ve/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/var/www/ve/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Compilation exited abnormally with code 1 at Fri Oct 31 18:49:54
```
Even after setting DJANGO_SETTINGS_MODULE  I still get an error

```shell
-*- mode: compilation; default-directory: "/var/www/zeus/" -*-
Compilation started at Fri Oct 31 18:52:01

django-admin.py test --noinput
Traceback (most recent call last):
  File "/var/www/ve/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/var/www/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/var/www/ve/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/var/www/ve/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/www/ve/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'zeus.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named zeus.settings

Compilation exited abnormally with code 1 at Fri Oct 31 18:52:01
```

I'm not familiar with the lisp language or the elpy internals but after looking in the code I overwrited the default django test runner as this in my init.el configuration

```lisp
(defun elpy-test-django-runner (top file module test)
  (interactive (elpy-test-at-point))
  (if module
      (elpy-test-run top
                     "./manage.py" "test"
                     (if test (format "%s.%s" module test) module))
    (elpy-test-run top "./manage.py" "test")))
(put 'elpy-test-django-runner 'elpy-test-runner-p t)
```

And now everything works perfectly. My question is why do you use the django-admin.py for running the test while there is this the manage.py script that sets the environment variables and the sys.path ? May be I'm doing it wrong and there is a step I missed but I don't see how you can use the default test runner with django.

I also tried switching to the other python test runner without any sucess.

**Comment by jorgenschaefer** [comment]
Now tracked in #425
