### ISSUE TITLE
name t_matrix not found

### ISSUE THREAD

**Issue by hugo-pH** [jorgenschaefer/elpy#399]
I've got the following error message:

Error Message

name t_matrix not found

Configuration

Virtualenv........: None
RPC Python........: 2.7.3 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.50.1
Elpy..............: 1.5.1
Jedi..............: Not found
Rope..............: 0.10.2
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

Traceback

Traceback

Traceback (most recent call last):
  File "/home/hugo/.emacs.d/elpa/elpy-20140810.7/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/hugo/.emacs.d/elpa/elpy-20140810.7/elpy/server.py", line 81, in rpc_get_calltip
    get_source(source), offset)
  File "/home/hugo/.emacs.d/elpa/elpy-20140810.7/elpy/server.py", line 46, in _call_backend
    return meth(*args, **kwargs)
  File "/home/hugo/.emacs.d/elpa/elpy-20140810.7/elpy/ropebackend.py", line 159, in rpc_get_calltip
    remove_self=True)
  File "/usr/local/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 92, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/usr/local/lib/python2.7/dist-packages/rope/contrib/fixsyntax.py", line 61, in pyname_at
    return new_pyname()
  File "/usr/local/lib/python2.7/dist-packages/rope/contrib/fixsyntax.py", line 59, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/usr/local/lib/python2.7/dist-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/evaluate.py", line 102, in get_primary_and_pyname_at
    return (None, holding_scope.parent[name])
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyscopes.py", line 30, in __getitem__
    return self.get_name(key)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyscopes.py", line 122, in get_name
    raise exceptions.NameNotFoundError('name %s not found' % name)
NameNotFoundError: name t_matrix not found
```

**Comment by jorgenschaefer** [comment]
I _think_ this problem should already be fixed in a current version of Elpy. Could you upgrade to 1.6 and see if that solves the problem?

(Sorry for the long delay in realizing this…)

**Comment by jorgenschaefer** [comment]
Lacking any updates, I'll close this issue. Please do not hesitate to file a new issue if you have any more problems, and enjoy Elpy!
