### ISSUE TITLE
Can't find shared object file on PYTHONPATH

### ISSUE THREAD

**Issue by ccann** [jorgenschaefer/elpy#411]
```
Error Message

libqipython.so: cannot open shared object file: No such file or directory

Configuration

Virtualenv........: None
RPC Python........: 2.7.8 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1-final0
Rope..............: Not found (0.10.2 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ccanning/.emacs.d/elpa/elpy-20141031.945/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/ccanning/.emacs.d/elpa/elpy-20141031.945/elpy/server.py", line 87, in rpc_get_completions
    get_source(source), offset)
  File "/home/ccanning/.emacs.d/elpa/elpy-20141031.945/elpy/server.py", line 45, in _call_backend
    return meth(*args, **kwargs)
  File "/home/ccanning/.emacs.d/elpa/elpy-20141031.945/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 501, in type
    followed = self.follow_definition()
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 533, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 518, in _follow_statements_imports
    i._importer.module).follow(self._evaluator)
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 338, in follow
    scope, rest = self.follow_file_system()
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469, in _follow_sys_path
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 527, in _load_module
    return load(source) if cached is None else cached.module
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 520, in load
    return compiled.load_module(path, name)
  File "/home/ccanning/.local/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 288, in load_module
    __import__(dotted_path)
ImportError: libqipython.so: cannot open shared object file: No such file or directory
```

Apologies up front if this is an error on my end.

libqipython.so is inside a directory on my PYTHONPATH. When I start typing in order to instantiate a class from libqipython.so this error is raised. I'm assuming this is Jedi searching for completions and not finding libqipython.so, but I'm not sure how to guide it.

**Comment by jorgenschaefer** [comment]
I assume this problem was solved now. Please do not hesitate to open a new issue if you have any further problems or questions!
