### ISSUE TITLE
Elpy Error - The backend encountered an unexpected error

### ISSUE THREAD

**Issue by maxc01** [jorgenschaefer/elpy#417]
My system is FreeBSD 10.0 and I think this is a problem related with my system.
Sometimes when I type `numpy.` and this error message occurs.

```
Error Message

/usr/local/lib/python2.7/site-packages/numpy/core/_dotblas.so: Undefined symbol "cblas_cdotc_sub"

Configuration

Virtualenv........: None
RPC Python........: 2.7.8 (/usr/local/bin/python)
Interactive Python: ipython (/usr/local/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1-final0
Rope..............: Not found (0.10.2 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/maxc01/.emacs.d/elpa/elpy-20141031.945/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/maxc01/.emacs.d/elpa/elpy-20141031.945/elpy/server.py", line 87, in rpc_get_completions
    get_source(source), offset)
  File "/home/maxc01/.emacs.d/elpa/elpy-20141031.945/elpy/server.py", line 45, in _call_backend
    return meth(*args, **kwargs)
  File "/home/maxc01/.emacs.d/elpa/elpy-20141031.945/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 501, in type
    followed = self.follow_definition()
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 533, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 521, in _follow_statements_imports
    return super(Completion, self)._follow_statements_imports()
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 326, in _follow_statements_imports
    return imports.follow_imports(self._evaluator, [stripped])
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    for r in ImportWrapper(evaluator, s).follow():
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 171, in follow
    module, rest = self._importer.follow_file_system()
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469, in _follow_sys_path
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 527, in _load_module
    return load(source) if cached is None else cached.module
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 520, in load
    return compiled.load_module(path, name)
  File "/home/maxc01/.local/lib/python2.7/site-packages/jedi/evaluate/compiled/__init__.py", line 288, in load_module
    __import__(dotted_path)
ImportError: /usr/local/lib/python2.7/site-packages/numpy/core/_dotblas.so: Undefined symbol "cblas_cdotc_sub"
```

**Comment by jorgenschaefer** [comment]
I assume this problem was fixed, so I am closing this issue. I created an issue to track your idea of a message filter.

Please do not hesitate to open a new issue if you encounter any further problems.
