### ISSUE TITLE
__init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by tariqk** [jorgenschaefer/elpy#468]
Elpy's basically asking me to put this into the issue tracker.

```
Error Message

__init__() got an unexpected keyword argument 'encoding'

Configuration

Virtualenv........: None
RPC Python........: 2.7.3 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.4.50.1
Elpy..............: 1.6.0
Jedi..............: 0.7.0 (0.8.1 available)
Rope..............: Not found (0.10.2 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/tariqk/.emacs.d/elpa/elpy-1.6.0/elpy/jedibackend.py", line 285, in run_with_debug
    script = jedi.Script(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
#! /usr/bin/env python

import pygame, sys, traceback
from pygame.locals import *

sys.path.append("noddy/code")

from constants import *
from viewport import Game

def main():
    """
    main loop
    """
    game = Game()

# THE RUNNING PROGRAM
        
if __name__ == "__main__":
    try:
        pygame.init()
        main()
    except Exception, e:
        tb = sys.exc_info()[2]
        traceback.print_exception(e.__class__, e, tb)
    pygame.quit()
'''

script = jedi.Script(column=17, source=source, line=19, encoding='utf-8', path=u'/home/tariqk/projects/noddy-roguelike/main.py')
script.call_signatures()
```

Not exactly sure what's happening here, but I just finally got elpy working, apparently, properly (there were two overlapping `yasnippet` packages that were causing it to fail silently), and then this error comes up.

**Comment by tariqk** [comment]
Incidentally, I realized I hadn't run `pyvenv-activate`, which would explain why Jedi was at 0.7.0. With the virtual env running, I still get the same error:

```
Error Message

__init__() got an unexpected keyword argument 'encoding'

Configuration

Virtualenv........:  (/home/tariqk/projects/noddy-roguelike/)
RPC Python........: 2.7.3 (/home/tariqk/projects/noddy-roguelike/bin/python)
Interactive Python: python (/home/tariqk/projects/noddy-roguelike/bin/python)
Emacs.............: 24.4.50.1
Elpy..............: 1.6.0
Jedi..............: 0.8.1
Rope..............: Not found (0.10.2 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/tariqk/.emacs.d/elpa/elpy-1.6.0/elpy/jedibackend.py", line 285, in run_with_debug
    script = jedi.Script(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
#! /usr/bin/env python

import pygame
import sys
import traceback
from pygame.locals import *

sys.path.append("noddy/code")

from constants import *
from viewport import Game

def main():
    """
    main loop
    """
    game = Game()

# THE RUNNING PROGRAM

if __name__ == "__main__":
    try:
        pygame.init()
        main()
    except Exception, e:
        tb = sys.exc_info()[2]
        traceback.print_exception(e.__class__, e, tb)
    pygame.quit()
'''

script = jedi.Script(column=25, source=source, line=11, encoding='utf-8', path=u'/home/tariqk/projects/noddy-roguelike/main.py')
script.call_signatures()
```

**Comment by tariqk** [comment]
Based on the suggestion made [here](https://github.com/jorgenschaefer/elpy/issues/296#issuecomment-51898776), the problem no longer persists. `M-x elpy-rpc-restart` (and in this case, `C-x C-c`) did the job. Will have to remember to run `pyvenv-activate` before opening project files, in any case.

**Comment by jorgenschaefer** [comment]
Heh. Glad you could solve this already – thank you in any case for the report, and please do not hesitate to file a new issue if you have any further problems. :-)
