### ISSUE TITLE
Problems with importmagic tests

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#479]
@birkenfeld, some questions :-)

```
$ make python-coverage
[...]
FAIL: test_add_import (elpy.tests.test_impmagic.ImportMagicTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "elpy/tests/test_impmagic.py", line 50, in test_add_import
    'import logging\nimport time\n\nfrom mymod import AnUncommonName')
AssertionError: 'import time\n\nimport logging\n\nfrom mymod import AnUncommonName' != 'import logging\nimport time\n\nfrom mymod import AnUncommonName'
```

Is the list there not deterministic, i.e. should probably be sorted at some point?

Also, I get these errors at the end of a test run, any idea what they might be about?

```
Exception in thread Thread-7 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "elpy/impmagic.py", line 36, in _build_symbol_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 189, in build_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 144, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 150, in _index_package
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 142, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 161, in _index_module
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 128, in index_file
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 120, in index_source
  File "/usr/lib/python2.7/ast.py", line 241, in visit
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
  File "/usr/lib/python2.7/ast.py", line 241, in visit
  File "/usr/lib/python2.7/ast.py", line 250, in generic_visit
<type 'exceptions.TypeError'>: isinstance() arg 2 must be a class, type, or tuple of classes and types
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "elpy/impmagic.py", line 36, in _build_symbol_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 189, in build_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 144, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 150, in _index_package
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 144, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 150, in _index_package
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 142, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 161, in _index_module
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 128, in index_file
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 117, in index_source
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'
Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "elpy/impmagic.py", line 36, in _build_symbol_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 189, in build_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 144, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 150, in _index_package
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 144, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 150, in _index_package
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 142, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 161, in _index_module
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 128, in index_file
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 120, in index_source
  File "/usr/lib/python2.7/ast.py", line 241, in visit
  File "/usr/lib/python2.7/ast.py", line 249, in generic_visit
  File "/usr/lib/python2.7/ast.py", line 241, in visit
  File "/usr/lib/python2.7/ast.py", line 251, in generic_visit
  File "/usr/lib/python2.7/ast.py", line 241, in visit
  File "/usr/lib/python2.7/ast.py", line 250, in generic_visit
<type 'exceptions.TypeError'>: isinstance() arg 2 must be a class, type, or tuple of classes and types
...
```

(A whole bunch of similar errors)

Any idea what this is about?

**Comment by birkenfeld** [comment]
> Is the list there not deterministic, i.e. should probably be sorted at some point?

The imports should be sorted alphabetically by importmagic, so I don't know what's going on there. Since when do you get the failure?

> Any idea what this is about?

If the indexer thread is still running when the process shuts down, it'll run into the way Python clears modules by setting all globals to None, which leads to these strange exceptions.

This could be fixed with an except handler in the thread, I'll come up with a patch.

**Comment by jorgenschaefer** [comment]
> The imports should be sorted alphabetically by importmagic, so I don't know what's going on there. Since when do you get the failure?

I have not run the local python checks in a while, so "since earlier today", but that's not saying much at all.

git bisect tells me that 27b3b13b is the first rev that fails.

**Comment by birkenfeld** [comment]
OK, that's not surprising since that was the rev that introduced this test.

Looking closer at your test output, it seems that importmagic is treating "logging" like a 3rd-party module for you (two linebreaks between time and logging). Do you have a logging.py somewhere on sys.path by chance?

**Comment by jorgenschaefer** [comment]
Not directly:

```
>>> for p in sys.path:
...   if os.path.exists(os.path.join(p, "logging.py")):
...     print p
... 
>>> for p in sys.path:
...   if os.path.exists(os.path.join(p, "logging")):
...     print p
... 
/usr/lib/python2.7
```

But there is one in pip (`pip.utils.logging`):

```
$ find ~/.virtualenvs/elpy/ -iname '*logging*'
/home/forcer/.virtualenvs/elpy/lib/python2.7/site-packages/pip/utils/logging.pyc
/home/forcer/.virtualenvs/elpy/lib/python2.7/site-packages/pip/utils/logging.py
```

**Comment by birkenfeld** [comment]
Hmm, it might be an interaction with virtualenvs. How do I have to set up running the test suite to match your setup?

**Comment by jorgenschaefer** [comment]
I can reproduce it with a fresh virtualenv (no site packages) and Python 2.7.3:

```
mkvirtualenv elpy
pip install -r requirements.txt -r requirements-dev.txt
make python-coverage
```

**Comment by birkenfeld** [comment]
No luck with that here. Although with `make python-test` I get an unrelated failure unless I install elpy into the virtualenv.

**Comment by jorgenschaefer** [comment]
Interesting – could you file a separate issue for that?

Any idea how to debug this test failure further? Can I run some importmagic code to figure out which logging module it is picking up?

**Comment by birkenfeld** [comment]
Please use importmagic from the `debug` branch on my fork, I added recording of the filenames used to populate the tree.

Create an index with `from importmagic import SymbolIndex; si = SymbolIndex(); si.build_index(sys.path)`. Then look at `si._tree['logging']` - it should be like `<S:1.0 ['.../logging'] ...>`.

**Comment by jorgenschaefer** [comment]
Just to confirm, the bug still happens in that branch. And this is the value:

```
>>> si._tree['logging']
<S:1.0 ['/usr/lib/python2.7/logging'] {'setLoggerClass': 1.1, 'critical': 1.1, 'Handler': 1.1, 'LogRecord': 1.1, 'Logger': 1.1, 'Formatter': 1.1, 'BASIC_FORMAT': 1.1, 'getLevelName': 1.1, 'Filter': 1.1, 'addLevelName': 1.1, 'log': 1.1, 'getLogger': 1.1, 'FileHandler': 1.1, 'captureWarnings': 1.1, 'fatal': 1.1, 'WARNING': 1.1, 'LoggerAdapter': 1.1, 'StreamHandler': 1.1, 'NOTSET': 1.1, 'CRITICAL': 1.1, 'NullHandler': 1.1, 'error': 1.1, 'exception': 1.1, 'WARN': 1.1, 'disable': 1.1, 'warn': 1.1, 'ERROR': 1.1, 'DEBUG': 1.1, 'FATAL': 1.1, 'INFO': 1.1, 'BufferingFormatter': 1.1, 'basicConfig': 1.1, 'makeLogRecord': 1.1, 'warning': 1.1, 'getLoggerClass': 1.1, 'debug': 1.1, 'info': 1.1}>
```

**Comment by birkenfeld** [comment]
That is fine. I'll have a look into the import reordering logic next.

**Comment by jorgenschaefer** [comment]
Any updates on this?

**Comment by jorgenschaefer** [comment]
Marked test to be skipped in a983c1d, pending a fix from upstream.
