### ISSUE TITLE
"make python-test" fails from virtualenv without elpy installed

### ISSUE THREAD

**Issue by birkenfeld** [jorgenschaefer/elpy#481]
Preparation:
```
mkvirtualenv elpy
pip install -r requirements.txt -r requirements-dev.txt
make python-test
```

```
======================================================================
FAIL: test_should_complete_packages_for_import (tests.test_jedibackend.TestRPCGetCompletions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "elpy/tests/support.py", line 338, in test_should_complete_packages_for_import
    ["ts"])
AssertionError: Lists differ: [] != ['ts']

Second list contains 1 additional elements.
First extra element 0:
ts

- []
+ ['ts']

======================================================================
FAIL: test_should_return_top_level_modules (tests.test_pydocutils.TestGetModules)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gbr/devel/elpy/elpy/tests/test_pydocutils.py", line 66, in test_should_return_top_level_modules
    self.assertIn('elpy', modules)
AssertionError: 'elpy' not found in ['compat', 'impmagic', 'jedibackend', 'pydocutils', 'refactor', 'ropebackend', 'rpc', 'server', 'tests', 'UserDict', 'abc', 'codecs', 'copy_reg', 'distutils', 'encodings', 'fnmatch', 'genericpath', 'linecache', 'locale', 'ntpath', 'os', 'posixpath', 're', 'site', 'sre', 'sre_compile', 'sre_constants', 'sre_parse', 'stat', 'types', 'warnings', 'array', 'audioop', 'binascii', 'bz2', 'cPickle', 'cStringIO', 'cmath', 'crypt', 'datetime', 'dbm', 'fcntl', 'future_builtins', 'gdbm', 'grp', 'itertools', 'linuxaudiodev', 'math', 'mmap', 'nis', 'operator', 'ossaudiodev', 'parser', 'pyexpat', 'readline', 'resource', 'select', 'spwd', 'strop', 'syslog', 'termios', 'time', 'unicodedata', 'zlib', 'BaseHTTPServer', 'Bastion', 'CGIHTTPServer', 'ConfigParser', 'Cookie', 'DocXMLRPCServer', 'HTMLParser', 'MimeWriter', 'Queue', 'SimpleHTTPServer', 'SimpleXMLRPCServer', 'SocketServer', 'StringIO', 'UserList', 'UserString', 'aifc', 'antigravity', 'anydbm', 'argparse', 'ast', 'asynchat', 'asyncore', 'atexit', 'audiodev', 'base64', 'bdb', 'binhex', 'bisect', 'bsddb', 'cProfile', 'calendar', 'cgi', 'cgitb', 'chunk', 'cmd', 'code', 'codeop', 'collections', 'colorsys', 'commands', 'compileall', 'compiler', 'contextlib', 'cookielib', 'copy', 'csv', 'ctypes', 'curses', 'dbhash', 'decimal', 'difflib', 'dircache', 'dis', 'doctest', 'dumbdbm', 'dummy_thread', 'dummy_threading', 'email', 'ensurepip', 'filecmp', 'fileinput', 'formatter', 'fpformat', 'fractions', 'ftplib', 'functools', 'getopt', 'getpass', 'gettext', 'glob', 'gzip', 'hashlib', 'heapq', 'hmac', 'hotshot', 'htmlentitydefs', 'htmllib', 'httplib', 'idlelib', 'ihooks', 'imaplib', 'imghdr', 'importlib', 'imputil', 'inspect', 'io', 'json', 'keyword', 'lib2to3', 'logging', 'macpath', 'macurl2path', 'mailbox', 'mailcap', 'markupbase', 'md5', 'mhlib', 'mimetools', 'mimetypes', 'mimify', 'modulefinder', 'multifile', 'multiprocessing', 'mutex', 'netrc', 'new', 'nntplib', 'nturl2path', 'numbers', 'opcode', 'optparse', 'os2emxpath', 'pdb', 'pickle', 'pickletools', 'pipes', 'pkgutil', 'platform', 'plistlib', 'popen2', 'poplib', 'posixfile', 'pprint', 'profile', 'pstats', 'pty', 'py_compile', 'pyclbr', 'pydoc', 'pydoc_data', 'quopri', 'random', 'repr', 'rexec', 'rfc822', 'rlcompleter', 'robotparser', 'runpy', 'sched', 'sets', 'sgmllib', 'sha', 'shelve', 'shlex', 'shutil', 'smtpd', 'smtplib', 'sndhdr', 'socket', 'sqlite3', 'ssl', 'statvfs', 'string', 'stringold', 'stringprep', 'struct', 'subprocess', 'sunau', 'sunaudio', 'symbol', 'symtable', 'sysconfig', 'tabnanny', 'tarfile', 'telnetlib', 'tempfile', 'test', 'textwrap', 'this', 'threading', 'timeit', 'toaiff', 'token', 'tokenize', 'trace', 'traceback', 'tty', 'unittest', 'urllib', 'urllib2', 'urlparse', 'user', 'uu', 'uuid', 'wave', 'weakref', 'webbrowser', 'whichdb', 'wsgiref', 'xdrlib', 'xml', 'xmllib', 'xmlrpclib', 'zipfile', 'CDROM', 'DLFCN', 'IN', 'TYPES', 'Canvas', 'Dialog', 'FileDialog', 'FixTk', 'ScrolledText', 'SimpleDialog', 'Tix', 'Tkconstants', 'Tkdnd', 'Tkinter', 'tkColorChooser', 'tkCommonDialog', 'tkFileDialog', 'tkFont', 'tkMessageBox', 'tkSimpleDialog', 'ttk', 'turtle', 'bumpversion', 'coverage', 'easy_install', 'importmagic', 'jedi', 'mock', 'nose', 'pip', 'pkg_resources', 'pkginfo', 'py', 'requests', 'rope', 'setuptools', 'tox', 'twine', 'virtualenv', 'virtualenv_support', 'wheel', '__builtin__', '__main__', '_ast', '_codecs', '_sre', '_symtable', '_warnings', '_weakref', 'errno', 'exceptions', 'gc', 'imp', 'marshal', 'posix', 'pwd', 'signal', 'sys', 'thread', 'xxsubtype', 'zipimport']

======================================================================
FAIL: test_should_return_top_level_modules (tests.test_pydocutils.TestGetPydocCompletions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gbr/devel/elpy/elpy/tests/test_pydocutils.py", line 17, in test_should_return_top_level_modules
    self.assertIn('elpy', modules)
AssertionError: 'elpy' not found in ['BaseHTTPServer', 'Bastion', 'CDROM', 'CGIHTTPServer', 'Canvas', 'ConfigParser', 'Cookie', 'DLFCN', 'Dialog', 'DocXMLRPCServer', 'FileDialog', 'FixTk', 'HTMLParser', 'IN', 'MimeWriter', 'Queue', 'ScrolledText', 'SimpleDialog', 'SimpleHTTPServer', 'SimpleXMLRPCServer', 'SocketServer', 'StringIO', 'TYPES', 'Tix', 'Tkconstants', 'Tkdnd', 'Tkinter', 'UserDict', 'UserList', 'UserString', '__builtin__', '__main__', '_ast', '_codecs', '_sre', '_symtable', '_warnings', '_weakref', 'abc', 'aifc', 'antigravity', 'anydbm', 'argparse', 'array', 'ast', 'asynchat', 'asyncore', 'atexit', 'audiodev', 'audioop', 'base64', 'bdb', 'binascii', 'binhex', 'bisect', 'bsddb', 'bumpversion', 'bz2', 'cPickle', 'cProfile', 'cStringIO', 'calendar', 'cgi', 'cgitb', 'chunk', 'cmath', 'cmd', 'code', 'codecs', 'codeop', 'collections', 'colorsys', 'commands', 'compat', 'compileall', 'compiler', 'contextlib', 'cookielib', 'copy', 'copy_reg', 'coverage', 'crypt', 'csv', 'ctypes', 'curses', 'datetime', 'dbhash', 'dbm', 'decimal', 'difflib', 'dircache', 'dis', 'distutils', 'doctest', 'dumbdbm', 'dummy_thread', 'dummy_threading', 'easy_install', 'email', 'encodings', 'ensurepip', 'errno', 'exceptions', 'fcntl', 'filecmp', 'fileinput', 'fnmatch', 'formatter', 'fpformat', 'fractions', 'ftplib', 'functools', 'future_builtins', 'gc', 'gdbm', 'genericpath', 'getopt', 'getpass', 'gettext', 'glob', 'grp', 'gzip', 'hashlib', 'heapq', 'hmac', 'hotshot', 'htmlentitydefs', 'htmllib', 'httplib', 'idlelib', 'ihooks', 'imaplib', 'imghdr', 'imp', 'impmagic', 'importlib', 'importmagic', 'imputil', 'inspect', 'io', 'itertools', 'jedi', 'jedibackend', 'json', 'keyword', 'lib2to3', 'linecache', 'linuxaudiodev', 'locale', 'logging', 'macpath', 'macurl2path', 'mailbox', 'mailcap', 'markupbase', 'marshal', 'math', 'md5', 'mhlib', 'mimetools', 'mimetypes', 'mimify', 'mmap', 'mock', 'modulefinder', 'multifile', 'multiprocessing', 'mutex', 'netrc', 'new', 'nis', 'nntplib', 'nose', 'ntpath', 'nturl2path', 'numbers', 'opcode', 'operator', 'optparse', 'os', 'os2emxpath', 'ossaudiodev', 'parser', 'pdb', 'pickle', 'pickletools', 'pip', 'pipes', 'pkg_resources', 'pkginfo', 'pkgutil', 'platform', 'plistlib', 'popen2', 'poplib', 'posix', 'posixfile', 'posixpath', 'pprint', 'profile', 'pstats', 'pty', 'pwd', 'py', 'py_compile', 'pyclbr', 'pydoc', 'pydoc_data', 'pydocutils', 'pyexpat', 'quopri', 'random', 're', 'readline', 'refactor', 'repr', 'requests', 'resource', 'rexec', 'rfc822', 'rlcompleter', 'robotparser', 'rope', 'ropebackend', 'rpc', 'runpy', 'sched', 'select', 'server', 'sets', 'setuptools', 'sgmllib', 'sha', 'shelve', 'shlex', 'shutil', 'signal', 'site', 'smtpd', 'smtplib', 'sndhdr', 'socket', 'spwd', 'sqlite3', 'sre', 'sre_compile', 'sre_constants', 'sre_parse', 'ssl', 'stat', 'statvfs', 'string', 'stringold', 'stringprep', 'strop', 'struct', 'subprocess', 'sunau', 'sunaudio', 'symbol', 'symtable', 'sys', 'sysconfig', 'syslog', 'tabnanny', 'tarfile', 'telnetlib', 'tempfile', 'termios', 'test', 'tests', 'textwrap', 'this', 'thread', 'threading', 'time', 'timeit', 'tkColorChooser', 'tkCommonDialog', 'tkFileDialog', 'tkFont', 'tkMessageBox', 'tkSimpleDialog', 'toaiff', 'token', 'tokenize', 'tox', 'trace', 'traceback', 'ttk', 'tty', 'turtle', 'twine', 'types', 'unicodedata', 'unittest', 'urllib', 'urllib2', 'urlparse', 'user', 'uu', 'uuid', 'virtualenv', 'virtualenv_support', 'warnings', 'wave', 'weakref', 'webbrowser', 'wheel', 'whichdb', 'wsgiref', 'xdrlib', 'xml', 'xmllib', 'xmlrpclib', 'xxsubtype', 'zipfile', 'zipimport', 'zlib']

----------------------------------------------------------------------
```

**Comment by jorgenschaefer** [comment]
This is interesting, thanks for noticing it. :-) The trivial workaround would be:

```
PYTHONPATH=`pwd` make python-test
```

Or we can add this to `support.py`:

```
import sys
sys.path.insert(0, os.path.realpath(os.path.join(
    os.path.dirname(__file__), "../..")))
```

But having thought about it for a bit, this actually points to a deeper issue. Elpy _is_ in the path, otherwise the test modules could not be imported in the first place. But for some reason, the path discovery does not catch that.

For Jedi this is likely an obscure bug upstream which I reported there. The pydoc thing is also a bug in the pydoc handling, but that's so hacky I'm willing to ignore it here. "Fixed" (or rather, ignored) in the commit above.

**Comment by jorgenschaefer** [comment]
Yeah, well, "fixed".
