### ISSUE TITLE
Elpy does not recognises properly the python version when using pyenv externally

### ISSUE THREAD

**Issue by jrbalderrama** [jorgenschaefer/elpy#488]
I'm using pyenv with local environment version 3.4.2 however the RPC Python shows the global one declared as 3.7.9. Following this misconfiguration other errors are raised, for example, during auto-completion, this error appears with jedi or rope:

```
Error Message

invalid syntax (<unknown>, line 74)

Configuration

Virtualenv........:  (/Users/xxx/workspace/python-radio/radio/)
RPC Python........: 2.7.9 (/Users/xxx/.pyenv/shims/python)
Interactive Python: python (/Users/xxx/.pyenv/shims/python)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.8.1
Rope..............: 0.10.2
Importmagic.......: 0.1.2
Syntax checker....: flake8 (/Users/xxx/.pyenv/shims/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/xxx/.emacs.d/elpa/elpy-20150206.1012/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/xxx/.emacs.d/elpa/elpy-20150206.1012/elpy/server.py", line 227, in rpc_get_unresolved_symbols
    return self.import_magic.get_unresolved_symbols(source)
  File "/Users/xxx/.emacs.d/elpa/elpy-20150206.1012/elpy/impmagic.py", line 63, in get_unresolved_symbols
    scope = importmagic.symbols.Scope.from_source(source)
  File "/Users/xxx/.pyenv/versions/2.7.9/lib/python2.7/site-packages/importmagic/symbols.py", line 87, in from_source
    src = parse_ast(src)
  File "/Users/xxx/.pyenv/versions/2.7.9/lib/python2.7/site-packages/importmagic/util.py", line 18, in parse_ast
    return ast.parse(source, filename or '<unknown>')
  File "/Users/xxx/.pyenv/versions/2.7.9/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 74
    print("\tNo references for '{}'\n".format(name), file=sys.stderr)
                                                         ^
SyntaxError: invalid syntax
```

**Comment by jorgenschaefer** [comment]
Thank you very much for the report!
Where did you set the pyenv version? According to that output, Elpy runs `/Users/xxx/.pyenv/shims/python`, which is correct for pyenv, but that script claims to be 2.7.9.

What does `/Users/xxx/.pyenv/shims/python --version` say?

**Comment by jrbalderrama** [comment]
It claims v.3.4.2

**Comment by jorgenschaefer** [comment]
Huh! That's strange.

What's the value of the following expression?

```
(let ((process-environment (elpy-rpc--environment)))
  (cons (executable-find elpy-rpc-python-command)
        (getenv "PATH")))
```

**Comment by jrbalderrama** [comment]
```
("/Users/xxx/.pyenv/shims/python" . "/Users/xxx/workspace/python-radio/radio//bin:/Users/xxx/.pyenv/shims/:/Users/xxx/.rvm/gems/ruby-2.1.5/bin/:/Users/xxx/.rvm/gems/ruby-2.1.5@global/bin/:/Users/xxx/.rvm/rubies/ruby-2.1.5/bin/:/usr/local/bin/:/usr/local/sbin/:/Users/xxx/bin/:/usr/bin/:/bin/:/usr/sbin/:/sbin/:/usr/local/bin/:/opt/X11/bin/:/usr/local/MacGPG2/bin/:/usr/texbin/:/Users/xxx/.rvm/bin/:/usr/local/Cellar/emacs/24.4/libexec/emacs/24.4/x86_64-apple-darwin13.4.0/")
```

BTW this is the message when I get the compiler shell inside Emacs:

```
Python 3.4.2 (default, Feb  3 2015, 17:19:15) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by jorgenschaefer** [comment]
Hm. I just installed pyenv, and switching between 2.7.9 and 3.4.2 works fine for Elpy.

That is, I can run `pyenv global 2.7.9` and `M-x elpy-config` tells me RPC is using 2.7.9. After running `pyenv global 3.4.2`, `M-x elpy-config` tells me RPC is using 3.4.2.

Do you have some more reproduction steps for me?

**Comment by jorgenschaefer** [comment]
Oh, I just saw the _local_ part of your comment. Sorry, I do not know pyenv well and did not realize what that meant! That explains things.

`pyenv local` will create a file `.python-version` in a directory. Running the `python` command in that directory will use a different version of Python than doing so in some other directory.

Elpy does run the RPC process in the root directors (`/`) to avoid accidentally importing modules in your current path. So indeed, this is an incompatibility between pyenv and Elpy.

I am unsure how to fix this. Elpy should not run Python elsewhere, we have had bugs based on that in the past. Maybe Elpy could try and see if it can find a `.python-version` file and emulate pyenv behavior then, for example by using `$PYENV_ROOT/versions/$(cat .python-version)/bin/python`.

Thanks for the suggestion, and sorry for taking so long to realize what this was about!

**Comment by jrbalderrama** [comment]
Thanks you for your feedback. Just for confirmation, it means the reported bug is directly associated to python versions issue?

**Comment by jorgenschaefer** [comment]
The `SyntaxError` is because Python 2 does not have a print function, only a print statement, so it does not take keyword arguments. Arguably, this shouldn't cause a full stack trace at that point, though. Hm.

**Comment by rileyrg** [comment]
Did anyone get anywhere with this? pyenv seems a "standard" and elpy doesn't seem to recognise anything other than the pyenv global setting so no local project overrides via .python-version.
