### ISSUE TITLE
Unexpected error when reorganizing imports

### ISSUE THREAD

**Issue by cpitclaudel** [jorgenschaefer/elpy#491]
I got the following error after pressing <kbd>C-c C-r a</kbd> in a file called `__init__.py`.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

cannot concatenate 'str' and 'NoneType' objects

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.8.1-final0
Rope..............: 0.9.2 (0.10.2 available)
Importmagic.......: 0.1.2
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/server.py", line 186, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/refactor.py", line 210, in get_changes
    return method(*args)
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/refactor.py", line 227, in refactor_organize_imports
    changes = refactor.organize_imports(self.resource)
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 29, in organize_imports
    self.import_tools.organize_imports, resource, offset)
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 54, in _perform_command_on_import_tools
    result = method(pymodule, import_filter=import_filter)
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 174, in organize_imports
    module_imports.remove_unused_imports()
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/module_imports.py", line 37, in remove_unused_imports
    import_statement.accept(visitor)
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/importinfo.py", line 56, in accept
    return visitor.dispatch(self)
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/actions.py", line 124, in dispatch
    import_.import_info = result
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/importinfo.py", line 26, in _set_import_info
    new_import is not None and not new_import == self._import_info:
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/importinfo.py", line 87, in __eq__
    self.get_import_statement() == obj.get_import_statement()
  File "/usr/lib/python2.7/dist-packages/rope/refactor/importutils/importinfo.py", line 170, in get_import_statement
    result = 'from ' + '.' * self.level + self.module_name + ' import '
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by jorgenschaefer** [comment]
Thank you for the report!
This is a bug in Rope. Can you try to upgrade to 0.10.2 and see if that fixes it?

**Comment by cpitclaudel** [comment]
Ah, upgrading indeed fixed it; but this is a python 3 file, so now rope returns:

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

Syntax error in file <dboost/utils/printing.py> line <8>: invalid syntax

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: 0.1.2
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/server.py", line 186, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/refactor.py", line 210, in get_changes
    return method(*args)
  File "/home/clement/.emacs.d/elpa/elpy-20150206.1012/elpy/refactor.py", line 227, in refactor_organize_imports
    changes = refactor.organize_imports(self.resource)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 29, in organize_imports
    self.import_tools.organize_imports, resource, offset)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 54, in _perform_command_on_import_tools
    result = method(pymodule, import_filter=import_filter)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 183, in organize_imports
    pymodule = self._remove_self_imports(pymodule, import_filter)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/__init__.py", line 192, in _remove_self_imports
    module_imports.get_self_import_fix_and_rename_list()
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/module_imports.py", line 170, in get_self_import_fix_and_rename_list
    import_stmt.accept(visitor)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/importinfo.py", line 56, in accept
    return visitor.dispatch(self)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/actions.py", line 12, in dispatch
    return method(import_, import_.import_info)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/importutils/actions.py", line 240, in visitFromImport
    pymodule = self.pycore.resource_to_pyobject(resource)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pycore.py", line 197, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pycore.py", line 323, in get_pymodule
    force_errors=force_errors)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 155, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 184, in _init_source
    raise exceptions.ModuleSyntaxError(filename, e.lineno, e.msg)
ModuleSyntaxError: Syntax error in file <dboost/utils/printing.py> line <8>: invalid syntax
```

Uninstalling rope and keeping only rope_py3k causes no suggestions to appear when I press <kbd>C-c C-r</kbd>, though.

I wonder if there's a way to use rope_py3k for files that have a python3 sheebang? Or is there a way to tell elpy which one to use on a per-file basis (or in .dir-locals.el)?

**Comment by jorgenschaefer** [comment]
You are using Python 2 for Elpy:

```
RPC Python........: 2.7.6 (/usr/bin/python)
```

If you are not using a virtualenv to make the python command point to python3, you can change `elpy-rpc-python-command` to `"python3"` to get Elpy to use that. :-)

**Comment by cpitclaudel** [comment]
Thanks! Changing elpy-rpc-python-command to python3 yields the following message:

Error initializing Elpy

There was an error when trying to start the backend. Elpy can not work until
this problem is solved. The following lines were received from Python, and might
help identifying the problem.

Unhandled exception in thread started by 
{"result": null, "id": 7}
{"result": null, "id": 8}
{"result": null, "id": 9}
{"result": null, "id": 10}
{"result": null, "id": 11}
{"result": null, "id": 12}

And the configuration in that case is
Elpy Configuration

Virtualenv........: None
RPC Python........: 3.4.0 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.8.1-final0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.2
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

The error message displays every time I move to a different line.

**Comment by cpitclaudel** [comment]
This happens regardless of whether I use rope of elpy.

**Comment by cpitclaudel** [comment]
Actually, this is strange. It happens regardless of whether I set the command to "python2" or "python3"; removing the setting makes everything work again

**Comment by jorgenschaefer** [comment]
`Unhandled exception in thread started by`

This sounds an awful lot like #482 – there's some bug somewhere in Elpy that causes that error, and we haven't been able to figure out where yet. :-(

**Comment by cpitclaudel** [comment]
I see. Experimenting a bit more shows that importmagic is indeed the culprit fr python3. Uninstalling it solves the problem. Anything I could run to help?

I've computed a list of package that I have in common with the OP of #482:

```
flake8==2.3.0
jedi==0.8.1-final0
pycparser==2.10
pycrypto==2.6.1
pyflakes==0.8.1
pyparsing==2.0.1
rope-py3k==0.9.4-1
```

removing them one by one doesn't help, though. I stopped when al that was left was 

```
importmagic==0.1.2
jedi==0.8.1-final0
pyflakes==0.8.1
rope-py3k==0.9.4-1
```

and the problem was still there. It looks like importmagic is indeed chocking on something, but not the same thing in the two cases.

**Comment by cpitclaudel** [comment]
I think I found it. importmagic fails on package dateutils:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/clement/documents/test.py", line 8, in <module>
    with open('index.json') as fd:
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 194, in build_index
    self.index_path(filename)
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 149, in index_path
    self._index_package(root, location)
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 155, in _index_package
    subtree.index_path(os.path.join(root, filename))
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 147, in index_path
    self._index_module(root, location)
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 166, in _index_module
    self.index_file(basename, root)
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 133, in index_file
    raise e
  File "/home/clement/.local/lib/python3.4/site-packages/importmagic/index.py", line 129, in index_file
    success = subtree.index_source(filename, fd.read())
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdf in position 1208: invalid continuation byte
```

And indeed dateutil is not using utf-8:

```
# -*- coding:iso-8859-1 -*-
"""
Copyright (c) 2003-2007  Gustavo Niemeyer <gustavo@niemeyer.net>
```

I'll post a bug report there

**Comment by jorgenschaefer** [comment]
You are awesome!

Thank you for the excellent debugging work.

This seems to be fixed upstream, so I will close this issue. Please do not hesitate to open further issues if you have any more problems! (Fixing them yourself appreciated, but not strictly required :-D)

**Comment by birkenfeld** [comment]
> You are awesome!

Indeed, thanks for all your investigation into this.

**Comment by cpitclaudel** [comment]
My pleasure! Thanks for the awesome work :)
