### ISSUE TITLE
Disable Elpy RPC for very large files

### ISSUE THREAD

**Issue by bersace** [jorgenschaefer/elpy#500]
Hi,

I hit a bug with jedi on big files.

Here is the trace  :

```
Error Message

u'u'

Configuration

Virtualenv........: None
RPC Python........: 2.7.8 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.7.0
Jedi..............: 0.8.1
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/bersace/.emacs.d/elpa/elpy-20150206.1012/elpy/jedibackend.py", line 300, in run_with_debug
    return getattr(script, name)()
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/__init__.py", line 557, in call_signatures
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 226, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 216, in user_stmt
    module = self.module()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 255, in module
    return self._parser().module
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 209, in _parser
    parser = FastParser(self._source, self._path)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 65, in __call__
    p = super(CachedFastParser, self).__call__(source, module_path)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 199, in __init__
    self._parse(code)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 302, in _parse
    line_offset, nodes, not is_first)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 367, in _get_parser
    top_module=self.module, no_docstr=no_docstr)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 59, in __init__
    self._parse()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 604, in _parse
    stmt, tok = self._parse_statement(self._gen.current)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 360, in _parse_statement
    tok = next(self._gen)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 627, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 634, in __next__
    self.current = next(self._tokenizer)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 399, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 405, in __next__
    current = next(self.gen)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/tokenize.py", line 285, in generate_tokens
    endprog = (endprogs[initial] or endprogs[token[1]] or
KeyError: u'u'

Jedi Debug Information

Jedi did not emit any debug info.
```

I would like not to publish reproduction code. I pasted the reproduction code in a file but then it does not fail :/

Can you help me debugging this ?

Regards,
Étienne

**Comment by jorgenschaefer** [comment]
Thanks for the report! I'm not sure how to debug this any further without access to the source file – I forwarded this upstream. If David needs some help figuring out what's going on here, he'll let us know.

**Comment by bersace** [comment]
Finally, i created a hook for large file that disable some features. Here it is :

```lisp
(use-package
 elpy
 :init
 (progn
   (elpy-enable)
   (defun my--python-large-file ()
     (when (> (buffer-size) 100000)
       (message "Degraded mode for large python file")
       (setq undo-limit 10)
       (make-variable-buffer-local 'mmm-global-mode)
       (setq mmm-global-mode nil)
       (setq font-lock-support-mode 'jit-lock-mode)
       (setq jit-lock-stealth-time 16
	     jit-lock-defer-contextually t
	     jit-lock-stealth-nice 1
	     jit-lock-stealh-load 10)
       (setq-default font-lock-multiline t)
       (elpy-modules-buffer-stop)
       (make-variable-buffer-local 'elpy-modules)
       (setq elpy-modules
	     '(elpy-module-flymake
	       elpy-module-yasnippet
	       elpy-module-pyvenv
	       elpy-module-sane-defaults))
       (elpy-modules-buffer-init)))

   (add-hook 'elpy-mode-hook 'my--python-large-file)
   (setq yas-snippet-dirs
	 (list (expand-file-name "~/.emacs.d/snippets")
	       (concat (file-name-directory (locate-library "elpy"))
		       "snippets/")))
   (yas-reload-all)))
```

I'm far from an elisp guru, so comments are welcome ;)

**Comment by jorgenschaefer** [comment]
@bersace, thank you for the snippet – are you sure this is the right issue you commented on, though? :-)

**Comment by bersace** [comment]
Yes. This disable jedi on big file ;)

**Comment by jorgenschaefer** [comment]
Ah, haha :-)

The author of Jedi mentions that the original issue here is likely fixed in the next release of Jedi. If you can, could you test this with the current development version? You'd have to clone the jedi github repository at https://github.com/davidhalter/jedi/ and add that to your PYTHONPATH or virtualenv to check.

**Comment by bersace** [comment]
Still very laggy, but at least it does not raise an exception. Thanks :)

**Comment by jorgenschaefer** [comment]
Great! Thank you for testing this!

How big is this file, by the way?

**Comment by bersace** [comment]
```console
$ ls -hl ~/large.py 
-rw-rw-r-- 1 bersace bersace 241K févr. 19 11:16 /home/bersace/large.py
$ wc -l ~/large.py 
5925 /home/bersace/large.py
```

I can send you the file privatly if you wish. That's unit tests.

**Comment by jorgenschaefer** [comment]
Ok, 241K _is_ pretty large – Elpy needs to send this to Jedi for completion suggestions, so it ends up sending half a meg of data to Jedi on almost every key stroke. :-D I hope this is a rare use case.

**Comment by bersace** [comment]
Unfortunately :

```console
...
76K     ./employee_space/tests.py
76K     ./registration/tests.py
76K     ./sharing/tests.py
84K     ./document/models.py
96K     ./bulk/tests.py
100K    ./api/tests/employee.py
104K    ./document/views.py
108K    ./account/models.py
128K    ./distribution/models.py
128K    ./search/tests/documents.py
140K    ./api/tests/signature.py
152K    ./workplace/tests.py
160K    ./importer/tests.py
228K    ./account/tests.py
244K    ./signature/tests.py
304K    ./document/tests.py
336K    ./distribution/tests.py
```

I'm splitting things on the way, but that's not always possible *yet*

:(

**Comment by bersace** [comment]
Ja, that yould be nice to have some degraded beheviour on big file.

**Comment by jorgenschaefer** [comment]
A configuration option that disables sending of files over a given size sounds like a good idea, I'll add that. Thank you for the suggestion!

**Comment by bersace** [comment]
:+1:

**Comment by bersace** [comment]
Hi. I tryied to disable my custom elpy degraded mode. I still need to disable highlight-indentation on large file. What do you think of disabling it too on big files ?

**Comment by bersace** [comment]
Here si the my elpy-mode wrapper that disable highlight indentation on big files : https://github.com/bersace/dotemacs/blob/master/lisp/my-elpy.el :)

**Comment by jorgenschaefer** [comment]
Thanks for the suggestion. This is an interesting idea – having Elpy generally degrade gracefully when the file is too large might be a nice feature idea. Could you open an new issue for that, so it's not lost? :-)
