### ISSUE TITLE
Flow object error

### ISSUE THREAD

**Issue by imfede** [jorgenschaefer/elpy#514]
Hi, after a while using your awesome mode, it started giving me the following error. Note that I do not changed anything in the configuration/source files/workflow to make this happen (not that I know of, at least). This error shows up everytime i type something. and wait for the dropdown menu to give me that nice completion list.
What follows is the content of the *Elpy Buffer* auto-opened when the error came:

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Flow' object has no attribute 'name'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.4.1
Elpy..............: 1.7.1
Jedi..............: 0.8.1-final0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: Not found (pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/federico/.emacs.d/elpa/elpy-20150226.1148/elpy/jedibackend.py", line 300, in run_with_debug
    return getattr(script, name)()
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 574, in call_signatures
    self._pos, user_stmt)
  File "/Library/Python/2.7/site-packages/jedi/cache.py", line 90, in wrapper
    value = optional_callable()
  File "/Library/Python/2.7/site-packages/jedi/api/__init__.py", line 572, in <lambda>
    _callable = lambda: self._evaluator.eval_call(stmt_el)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 240, in eval_call_path
    search_global=True)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 47, in find
    types = self._names_to_types(names, resolve_decorator)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 222, in _names_to_types
    types += self._remove_statements(typ, name)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 260, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=unicode(self.name_str))
  File "/Library/Python/2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 132, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 170, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 180, in process_precedence_element
    return self.eval_statement_element(el)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 215, in eval_statement_element
    return self.eval_call(element)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 226, in eval_call
    return self.eval_call_path(path, par, s.start_pos)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 246, in eval_call_path
    return self.follow_path(path, types, scope)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 260, in follow_path
    fp = self._follow_path(iter_paths[i], typ, call_scope)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 308, in _follow_path
    types = self.find_types(typ, current)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    return f.find(scopes, resolve_decorator, search_global)
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 46, in find
    names = self.filter_name(scopes)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 77, in filter_name
    for name_list_scope, name_list in scope_names_generator:
  File "/Library/Python/2.7/site-packages/jedi/evaluate/imports.py", line 263, in scope_names_generator
    yield s, s.get_defined_names()
  File "/Library/Python/2.7/site-packages/jedi/parser/representation.py", line 441, in get_defined_names
    n = super(SubModule, self).get_defined_names()
  File "/Library/Python/2.7/site-packages/jedi/_compatibility.py", line 148, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/jedi/parser/representation.py", line 332, in get_defined_names
    n += [s.name for s in self.subscopes]
AttributeError: 'Flow' object has no attribute 'name'

Jedi Debug Information

[N] dbg: finder.filter_name "menubar" in (<Function: __init__@9-34>): [<Name: menubar@17,8>]@(21, 8)
[N]  dbg: eval_statement <Statement: menubar = wx.MenuBar() @17,8> (menubar)
[N]  dbg: eval_expression_list: [<Call: wx.MenuBar>]
[N]   dbg: finder.filter_name "wx" in (<Function: __init__@9-34>-<ModuleWrapper: <fast.Module: golGUI@1-221>>): [<Name: wx@3,7>]@(17, 8)
[N]   dbg: finder._names_to_types: [<Name: wx@3,7>] -> [<Import: import wx @3,0>]
[N]  dbg: follow_module None wx
[N]  dbg: search_module wx /Users/federico/Google Drive/workspace/python/golGUI
[N]  dbg: follow_module None wx
[N]  dbg: search_module wx /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx
[N]  dbg: follow_module /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx _core
[N]  dbg: follow_module None __version__
[N]  dbg: search_module __version__ /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx
[N]  dbg: after import: [<ModuleWrapper: <fast.Module: __version__@1-11>>]
[N]  dbg: follow_module None _gdi
[N]  dbg: search_module _gdi /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx
[N]  dbg: after import: [<ModuleWrapper: <fast.Module: _gdi@1-8338>>]
[N]  dbg: follow_module None _windows
[N]  dbg: search_module _windows /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx
[N]  dbg: after import: [<ModuleWrapper: <fast.Module: _windows@1-5824>>]
[N]  dbg: follow_module None _controls
[N]  dbg: search_module _controls /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx
[N]  dbg: after import: [<ModuleWrapper: <fast.Module: _controls@1-7919>>]
[N]  dbg: follow_module None _misc
[N]  dbg: search_module _misc /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx
[N]  dbg: after import: [<ModuleWrapper: <fast.Module: _misc@1-7015>>]
[N]  dbg: after import: [<StarImportModule: <ModuleWrapper: <fast.Module: _core@1-16934>>>]
[N]  dbg: after import: [<StarImportModule: <ModuleWrapper: <fast.Module: wx@1-62>>>]
[N]  dbg: _follow_path: MenuBar in scope <StarImportModule: <ModuleWrapper: <fast.Module: wx@1-62>>>
[N]    dbg: execute: <InstanceElement of <eFunction of <Function: __init__@235-239>>> ()
[N]    dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@235-239>>>

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/bin/python

import wx
import time
import random
import sys

class gol(wx.Frame):
    def __init__(self, parent, id, dims, clist):
        wx.Frame.__init__(self, parent, id)
        self.dim = dims
        starth = dims[0]
        startw = dims[1]
        self.SetSize((startw, starth))
        self.SetTitle('Game of Life')
        
        menubar = wx.MenuBar()
        fileMenu = wx.Menu()
        fitem = fileMenu.Append(wx.ID_EXIT, 'Quit', 'Exit')
        #verra' appesa al menu in grassetto!
        menubar.Append(fileMenu, 'File')
        self.SetMenuBar(menubar)
        self.Bind(wx.EVT_MENU, self.destroy, fitem)
        
        self.statusbar = self.CreateStatusBar()
        self.statusbar.SetStatusText('N: 0')
        
        self.board = board(self, clist)
        self.board.SetFocus()
        self.board.start()
        
        self.Center()
        self.Show( True )

    def destroy(self, event):
        self.Destroy()
        sys.exit(0)


class board(wx.Panel):
    ID_TIMER = 1
    
    def __init__(self, parent, clist):
        wx.Panel.__init__(self, parent)
        self.parent = parent
        self.panx = int(parent.dim[0] / 2) 
        self.pany = int(parent.dim[1] / 2) 
        self.isRunning = False
        
        self.logic = gameLogic()
        self.logic.insertAliveCellList( clist )
        
        self.Bind(wx.EVT_PAINT, self.refresh)
        
        self.timer = wx.Timer(self, board.ID_TIMER)
        self.Bind(wx.EVT_TIMER, self.OnTimer, id=board.ID_TIMER)
        
        self.Bind(wx.EVT_KEY_DOWN, self.OnKeyDown)
        
        self.Bind(wx.EVT_LEFT_DOWN, self.ModCellOnclick)
    
    def ModCellOnclick(self, event):
        coord = event.GetPositionTuple()
        x = coord[0]
        y = coord[1]
        cellx = int( (x - self.panx) / 10 )
        celly = int( (y - self.pany) / 10 )
        self.logic.toggleCell( cell(cellx, celly) )
        self.refreshStatusBar()
        self.Refresh()
        event.Skip()
        
    def OnTimer(self, event):
        self.logic.makeOneStep()
        self.refreshStatusBar()
        self.Refresh()

    def refreshStatusBar(self):
        self.parent.statusbar.SetStatusText(
            'N: '+str(len(self.logic.listAlive)))
    
    def OnKeyDown(self, event):
        key = event.GetKeyCode()
        if key == wx.WXK_SPACE:
            if self.isRunning:
                self.stop()
            else:
                self.start()
        elif key == wx.WXK_LEFT:
            self.pan(False, 1)
        elif key == wx.WXK_RIGHT:
            self.pan(False, -1)
        elif key == wx.WXK_UP:
            self.pan(True, 1)
        elif key == wx.WXK_DOWN:
            self.pan(True, -1)
    
    def pan(self, isVert, amount):
        if isVert:
            self.pany += amount*10
        else:
            self.panx += amount*10
        self.Refresh()
        
    def start(self):
        self.isRunning = True
        self.timer.Start(300)
    
    def stop(self):
        self.isRunning = False
        self.timer.Stop()
    
    def refresh(self, e):
        """refresh on EVT_PAINT or change in list"""
        
        dc = wx.PaintDC(self)
        dc.SetPen(wx.Pen('#ffffff'))
        dc.SetBrush(wx.Brush('#000000'))

        for cell in self.logic.listAlive:
            self.drawCell(dc, cell)
        self.Refresh()
        
    def drawCell(self, dc, cell):
        x = cell.x*10 + self.panx
        y = cell.y*10 + self.pany
        width = 10
        height = width
        dc.DrawRectangle(x, y, width, height)

class gameLogic():
    """representation of the game"""
    
    def __init__(self):
        self.listAlive = []
        self.sleepTime = 1
    
    def clearBoard(self):
        self.listAlive = []

    def toggleCell(self, cell):
        if self.cellIsAlive(cell):
            self.listAlive.remove(cell)
        else:
            self.listAlive.append(cell)
    
    def insertAliveCell(self, cell):
        if cell not in self.listAlive:
            self.listAlive.append( cell )
    
    def insertAliveCellList(self, cellist):
        for cell in cellist:
            if cell not in self.listAlive:
                self.listAlive.append( cell )
    
    def countAliveNear(self, near):
        count = 0
        for i in [-1, 0, 1]:
            for j in [-1, 0, 1]:
                if (( (i!=0) or (j!=0) ) and
                    ( cell(near.x+i, near.y+j) in self.listAlive)):
                    count += 1
        return count
    
    def getNear(self, near):
        clist = []
        for i in [-1, 0, 1]:
            for j in [-1, 0, 1]:
                if( i!=0 or j!=0 ):
                    clist.append( cell(near.x+i, near.y+j) )
        return clist
    
    def cellIsAlive(self, cell):
        return True if cell in self.listAlive else False
    
    def getNewList(self):
        clist = []
        for c in self.listAlive:
            clist.append(c)
        
        for c in self.listAlive:
            for candidate in self.getNear(c):
                if candidate not in clist:
                    clist.append(candidate)
        
        return self.refineList(clist)
    
    def refineList(self, clist):
        newlist = []
        for c in clist:
            count = self.countAliveNear(c)
            if count == 3:
                newlist.append(c)
            if count == 2 and self.cellIsAlive(c):
                newlist.append(c)
            
        return newlist
    
    def makeOneStep(self):
        self.listAlive = self.getNewList()

class cell():
    """This is a cell"""
    
    def __init__(self, cx, cy):
        self.x = cx
        self.y = cy
    
    def __eq__(self, other):
        return True if ((self.x == other.x) and
                        (self.y == other.y) ) else False


if __name__ == "__main__":
    app = wx.App()
    cellist = [cell(-1,0), cell(0,0),
               cell(1,0), cell(2,0),
               cell(3,0)]
    gol(None, -1, (500,500), cellist)
    app.MainLoop()
'''

script = jedi.Script(column=24, source=source, line=21, encoding='utf-8', path=u'/Users/federico/Google Drive/workspace/python/golGUI/golGUI.py')
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report!

This is a bug in the Jedi library. David is about to release a new version, so this might be fixed already in the development version – if you can, could try installing the development version of Jedi and see if that fixes the problem?

In a virtualenv, `pip install -e git://github.com/davidhalter/jedi.git#egg=jedi` should install it easily. If you do not use virtualenvs (you should :-)), you can try `pip install --user -e ...` to install it in `~/.local/`.

**Comment by imfede** [comment]
Thx for the quick reply. As a side not i do not use virtualenvs (still) mainly because those are my first python projects (as you can probably see from the source) and i want to take one step at a time. I'm trying to install & run the development version of jedi now, i'll let you know the results

**Comment by imfede** [comment]
Well, now it throws a bunch of similar error, just regarding other objects/attributes. I will play with it a bit and then post to jedi github issue

**Comment by jorgenschaefer** [comment]
Thank you! Please do refer to the issue here if you post one there, just in case David has questions about this. :-)

**Comment by jorgenschaefer** [comment]
In the meantime, you can increase `elpy-rpc-error-timeout` so Elpy is not quite as annoying with the error popups …

**Comment by imfede** [comment]
Great, thank you again

**Comment by jorgenschaefer** [comment]
I assume this problem is solved. Please do not hesitate to open a new issue if you have any further problems, and enjoy Elpy :-)
