### ISSUE TITLE
Unexpected error while editing python file in TRAMP over ssh

### ISSUE THREAD

**Issue by rneatherway** [jorgenschaefer/elpy#517]
```
Error Message

[Errno 2] No such file or directory: ''

Configuration

Virtualenv........: None
RPC Python........: 2.7.8 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.4.1
Elpy..............: 1.7.1
Jedi..............: 0.8.1-final0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/home/robin/.local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/robin/.emacs.d/elpa/elpy-20150226.1148/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/robin/.emacs.d/elpa/elpy-20150226.1148/elpy/server.py", line 70, in rpc_init
    self.backend = ropebackend.RopeBackend(self.project_root)
  File "/home/robin/.emacs.d/elpa/elpy-20150226.1148/elpy/ropebackend.py", line 62, in __init__
    **prefs)
  File "/home/robin/.local/lib/python2.7/site-packages/rope/base/project.py", line 134, in __init__
    os.mkdir(self._address)
OSError: [Errno 2] No such file or directory: ''
```

**Comment by ChillarAnand** [comment]
elpy wont work correctly with tramp https://github.com/jorgenschaefer/pyvenv/issues/26#issuecomment-75029907

**Comment by rneatherway** [comment]
No I didn't expect so. I'm just reporting as the error message requested me to. I suggest that elpy should disable operation in this case.

**Comment by jorgenschaefer** [comment]
Thank you for the report. Indeed, Elpy should not throw errors like these but explain what is going on.
