### ISSUE TITLE
Elpy Error reported when entering unicode escape into string

### ISSUE THREAD

**Issue by alflanagan** [jorgenschaefer/elpy#545]
I started typing \u00A0 as the only character inside existing " marks. Got this report before I finished typing:

```
Error Message

(unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape (<unknown>, line 1)

Configuration

Virtualenv........: chatmoss_convert (/home/aflanagan/python-environments/chatmoss_convert)
RPC Python........: 3.4.3 (/home/aflanagan/python-environments/chatmoss_convert/bin/python)
Interactive Python: python (/home/aflanagan/python-environments/chatmoss_convert/bin/python)
Emacs.............: 24.5.50.2
Elpy..............: 1.7.50
Jedi..............: 0.8.1
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/home/aflanagan/python-environments/chatmoss_convert/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/cache.py", line 137, in wrapper
    return getattr(self, name)
AttributeError: _expression_list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/elpy-1.7.50-py3.4.egg/elpy/jedibackend.py", line 214, in run_with_debug
    return getattr(script, name)()
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/api/__init__.py", line 558, in call_signatures
    call, index = search_call_signatures(user_stmt, self._pos)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 122, in search_call_signatures
    user_stmt = fast_parent_copy(user_stmt)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 61, in fast_parent_copy
    return recursion(obj)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 48, in recursion
    setattr(new_obj, key, list_rec(value))
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 57, in list_rec
    copied_list[i] = recursion(el)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 48, in recursion
    setattr(new_obj, key, list_rec(value))
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 57, in list_rec
    copied_list[i] = recursion(el)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 18, in recursion
    obj.get_defined_names()
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/parser/representation.py", line 960, in get_defined_names
    for calls, operation in self.assignment_details:
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/parser/representation.py", line 984, in assignment_details
    self.expression_list()
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/parser/representation.py", line 1183, in expression_list
    call = cls(self._sub_module, tok_str, tok.start_pos, tok.end_pos, self)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/parser/representation.py", line 1339, in __init__
    self.value = literal_eval(literal)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/_compatibility.py", line 193, in literal_eval
    return ast.literal_eval(string)
  File "/usr/lib64/python3.4/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.4/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/cache.py", line 137, in wrapper
    return getattr(self, name)
AttributeError: _expression_list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/elpy-1.7.50-py3.4.egg/elpy/jedibackend.py", line 301, in run_with_debug
    return getattr(script, name)()
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/api/__init__.py", line 558, in call_signatures
    call, index = search_call_signatures(user_stmt, self._pos)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 123, in search_call_signatures
    arr, index = call_signature_array_for_pos(user_stmt, position)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 106, in call_signature_array_for_pos
    arr, index = search_array(command, pos)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 72, in search_array
    new_arr, index = call_signature_array_for_pos(stmt, pos)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 103, in call_signature_array_for_pos
    for command in stmt.expression_list():
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/cache.py", line 139, in wrapper
    result = func(self)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/parser/representation.py", line 1183, in expression_list
    call = cls(self._sub_module, tok_str, tok.start_pos, tok.end_pos, self)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/parser/representation.py", line 1339, in __init__
    self.value = literal_eval(literal)
  File "/home/aflanagan/python-environments/chatmoss_convert/lib/python3.4/site-packages/jedi/_compatibility.py", line 193, in literal_eval
    return ast.literal_eval(string)
  File "/usr/lib64/python3.4/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib64/python3.4/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"Search an XML file for invalid character sequences"

import re
from collections import defaultdict

# Regular expression to match characters that may be a problem
PROBLEM_REGEX = r'[^a-zA-Zéñ0-9©%#<>/ "“”*$+.!:_\'‘’°&();,\t\n?=—-]*'
PROBLEM_RE = re.compile(PROBLEM_REGEX)

TRANSLATIONS = {"Ã±": "ñ",
                "\u": " ",  # first is NO-BREAK-SPACE, U+00A0
}

# counter = 40
sequences = defaultdict(int)

with open("recipes.xml", "r") as recin:
    for index, line in enumerate(recin):
        x = PROBLEM_RE.findall(line)
        for y in x:
            if y:
                sequences[y] += 1
        #         print("{}: '{}' ({})".format(index, y,
        #                                      [hex(ord(c)) for c in y]))
        #         counter -= 1
        # if counter <= 0:
        #     break

for seq in sequences:
    print("'{}' ({}): {:,}".format(seq,
                                   [hex(ord(c)) for c in seq],
                                   sequences[seq]))

# Local Variables:
# python-indent-offset: 4
# fill-column: 100
# indent-tabs-mode: nil
# End:
'''

script = jedi.Script(encoding='utf-8', source=source, column=19, line=13, path='/mnt/extra/Devel/chatmoss_convert/sample_data/find_bad_chars.py')
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report!
I can reproduce this locally. It's a bug in Jedi 0.8.1. Trying with the (unreleased) Jedi 0.9.0 shows that this is fixed there, so this should be solved once the next Jedi release happens. I'm afraid you do not have much of an option than to wait until then, though. :-(

**Comment by alflanagan** [comment]
Good to know, thanks!
