### ISSUE TITLE
It told me to open a bug report, so ...

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#546]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

name sync_exec not found

Configuration

Virtualenv........: rack (/Users/erichanchrow/.virtualenvs/rack)
RPC Python........: 2.7.6 (/Users/erichanchrow/.virtualenvs/rack/bin/python)
Interactive Python: python (/Users/erichanchrow/.virtualenvs/rack/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.7.1
Jedi..............: 0.8.1
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/Users/erichanchrow/.virtualenvs/rack/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20150226.1148/elpy/ropebackend.py", line 96, in call_rope
    **kwargs)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 92, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/contrib/fixsyntax.py", line 61, in pyname_at
    return new_pyname()
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/contrib/fixsyntax.py", line 59, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/base/evaluate.py", line 102, in get_primary_and_pyname_at
    return (None, holding_scope.parent[name])
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/base/pyscopes.py", line 30, in __getitem__
    return self.get_name(key)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/rope/base/pyscopes.py", line 122, in get_name
    raise exceptions.NameNotFoundError('name %s not found' % name)
NameNotFoundError: name sync_exec not found

Rope Debug Information

```

Reproduction:

```Python

source = '''
#!/usr/bin/env python2.7

"""Fork and exec a subprocess, and sever all connection to it -- if it dies, we won't know about it.

Useful for creating processes in a "fire-and-forget" fashion.
"""

from __future__ import print_function
from __future__ import absolute_import

__author__ = 'ehanchrow@ine.com'

import logging
import os
import resource
import signal

log = logging.getLogger(__name__)

# TODO -- compare this to https://github.com/thesharp/daemonize, and
# either use that wholesale, or steal ideas from it.  I didn't know of
# that project when I wrote this.

# How many file handles can a process have open at once?  This is
# important to know, since we want to _close_ all possible open file
# handles.
MAXFD = 1024                    # fallback

# http://legacy.python.org/dev/peps/pep-0446/#closing-all-open-file-descriptors
# talks about this, and suggests that the "subprocess" module jumps
# through roughly the same hoops.  In particular, it suggests that I
# use os.sysconf("SC_OPEN_MAX") to get MAXFD.


def _get_max_fd():
    """Return the maximum number of file handles that a process is
    allowed to open.  Knowing this, we can safely close every possible
    handle, without having to take forever.

    """
    try:
        from_sysconf = os.sysconf("SC_OPEN_MAX")
    except(AttributeError, ValueError):
        from_sysconf = MAXFD

    from_getrlimit = resource.getrlimit(resource.RLIMIT_NOFILE)[1]
    if (from_getrlimit == resource.RLIM_INFINITY):
        from_getrlimit = MAXFD

    # TODO -- is "min" the right thing here?
    return min(from_sysconf, from_getrlimit)


def _the_slow_way():
    """For development only: determine MAXFD (for this platform, anyway)
    the slow, dumb, but accurate way: just keep opening files until we
    can't open any more.

    """
    num_opened = 0
    handles = []
    while True:
        try:
            print("num_opened is %d" % num_opened)
            handles.append(open(os.devnull, 'r'))
            num_opened += 1
        except OSError, e:
            print("Ahoy! %s" % e)
            break
    exit(0)


def async_exec(*args, **kwargs):
    """Run the given argument list asynchronously, rather as if we'd used
    `nohup`.  Adapted from
    http://code.activestate.com/recipes/278731/.  The new process is
    in a separate session
    (https://www.gnu.org/software/libc/manual/html_node/Process-Group-Functions.html#Process-Group-Functions)
    so as to disconnect from the controlling tty (hence rendering it
    impervious to some signals), and explicitly ignores SIGHUP.

    This function actually forks twice, so that the final process is
    our grandchild, not our child.  I suspect this is unnecessary;
    http://stackoverflow.com/a/881434/20146 says that it's just so
    that there's no chance that the final process can somehow acquire
    a controlling terminal.  That seems pretty unlikely even if we
    only forked once.

    """

    log_directory = kwargs.get('log_directory')
    if log_directory:
        try:
            os.makedirs(log_directory)
        except OSError, e:
            if e.errno != os.errno.EEXIST:
                raise

    grandpa_pid = os.getpid()

    # If os.execl (below) fails, we could log the failure to stderr,
    # but this exception is easier to notice.
    program_name = args[0]
    if not os.access(program_name, os.X_OK):

        # TODO -- a plain Exception like this will get turned into an
        # HTTP response with a 500 code, meaning "internal error".
        # But it's possible that the problem was due to a malformed
        # URL, which would call for a 4xx code, meaning "the http
        # client is on drugs".  None of the HTTP status codes at
        # http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html seem
        # appropriate for "no such file or directory".

        message = ["Cannot execute %r because it's not executable", program_name]
        log.exception(*message)
        raise Exception (*message)

    child = os.fork()
    if child == 0:
        # The first child
        os.setsid()
        signal.signal(signal.SIGHUP, signal.SIG_IGN)

        # This prevents zombies.

        # I originally had this in this module's __init__, but that
        # caused a weird problem: every time the web service used
        # "pexpect" to spawn a telnet process, and then called 'close'
        # on it, the pexpect code got all freaked out: its "isalive"
        # method called os.waitpid, but got ECHILD back; it then
        # raised an exception since it wasn't prepared for that case.

        # Anyway: putting the call to "signal" here is The Right
        # Thing, since it only gets invoked if it's needed, and
        # doesn't even affect the web server, since if you look
        # closely you'll see that this code is actually in a _child_
        # of the webserver process.

        signal.signal(signal.SIGCHLD, signal.SIG_IGN)

        child = os.fork()

        if child == 0:
            # The second child

            # Restore the signal handler that we muffled in our
            # parent.  This prevents a mysterious exception:
            # ``IOError: [Errno 10] No child processes`` coming from a
            # call to os.open deep inside code that gets invoked by
            # the Pyramid Configurator.

            # I suspect this is a bug in Python 2.7.5.  It's
            # tantalizingly similar to
            # http://bugs.python.org/issue9127, but that has been
            # fixed.
            signal.signal(signal.SIGCHLD, signal.SIG_DFL)

            # I can't explain why this is necessary; I just know that
            # if I don't do it, the parent or the child hangs.
            os.closerange(0, _get_max_fd() - 1)

            if log_directory:
                logfile_basename = os.path.join(log_directory, '{}-{}.'.format (args[1], os.getpid ()))

                stdout = open ('{}stdout'.format (logfile_basename), 'w')
                stderr = open ('{}stderr'.format (logfile_basename), 'w')
            else:
                stdout = open(os.devnull, 'w')
                stderr = open(os.devnull, 'w')

            os.dup2(stdout.fileno(), 1)
            os.dup2(stderr.fileno(), 2)

            try:
                os.execve(args[0], args[1:], dict(os.environ, INE_GRANDPA_PID=str(grandpa_pid)))
            except OSError as e:
                print("os.execl {!r} failed: {}".format(args, e), file=stderr)
                stderr.flush()
                os._exit(0) # prevent zombies if execl fails
        else:
            # First child

            log.info("Started grandchild process %d", child)

            os._exit(0)
    else:
        log.info("Started child process %d.  Grandchild log messages will be sent to syslog; its stdout and stderr will be %s", child, 'in {!r}'.format(log_directory) if log_directory else 'ignored')

        # This also prevents zombies.
        os.waitpid(child, 0)


def main():
    # _the_slow_way ()
    logging.basicConfig()
    print("Hello %s!  You are allowed %d open file handles." % (os.uname()[0], _get_max_fd()))
    async_exec('/bin/bash', 'bash', '-c', "date ; echo no wai > /dev/stderr")

if __name__ == "__main__":
    main()
'''

project = rope.base.project.Project(
    "/Users/erichanchrow/git-repositories/ine-rackcontrol/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/Users/erichanchrow/git-repositories/ine-rackcontrol/rackcontrol/async.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 2099, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Thank you for the report!
Bug in Rope, will work around this …
