### ISSUE TITLE
'NoneType' object has no attribute 'exc_info'Importmagic fails with 

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/elpy#550]
Running the current test suite fails with this:

```
Exception in thread Thread-7 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "elpy/impmagic.py", line 40, in _build_symbol_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 191, in build_index
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 145, in index_path
  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 151, in _index_package
  File "/usr/lib/python2.7/contextlib.py", line 50, in __exit__
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'

  File "/home/forcer/.virtualenvs/elpy/local/lib/python2.7/site-packages/importmagic/index.py", line 129, in index_file
  File "/usr/lib/python2.7/contextlib.py", line 50, in __exit__
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'
```

This seems to be a problem in importmagic, but I am not sure what kind of problem this is.

@birkenfeld, have you seen anything like this? Any idea what might be causing this?

**Comment by jorgenschaefer** [comment]
The problem here is that this thing is exiting when the interpreter is shutting down, and `sys` is actually `None`. Heh.

**Comment by jorgenschaefer** [comment]
Seems to be fixed in the latest versions of importmagic.
