### ISSUE TITLE
Another bug that I was asked to enter

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#561]
```
Error Message

u'key'

Configuration

Virtualenv........:  (/Users/erichanchrow/git-repositories/me/anagrams/python/venv/)
RPC Python........: 2.7.6 (/Users/erichanchrow/git-repositories/me/anagrams/python/venv/bin/python)
Interactive Python: python (/Users/erichanchrow/git-repositories/me/anagrams/python/venv/bin/python)
Emacs.............: 25.0.50.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/Users/erichanchrow/git-repositories/me/anagrams/python/venv/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Users/erichanchrow/git-repositories/me/anagrams/python/venv/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'key'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/bin/env python

from __future__ import print_function

# Core
import collections
import os
import re
import sys

# Local
from bag import Bag

has_a_vowel_re = re.compile(r'[aeiouy]')
long_enough_re = re.compile(r'^i$|^a$|^..')
non_letter_re = re.compile(r'[^a-z]')

default_dict_name = os.path.join(os.path.dirname(__file__), "../words.utf8")


def snarf_dictionary_from_file(fn):
    print("Snarfing {}".format(fn), file=sys.stderr)

    with open(fn) as inf:
        hash_table = collections.defaultdict(set)
        for w in inf:
            w = w.lower().rstrip()

            if non_letter_re.search(w):
                continue
            if (not long_enough_re.match(w)):
                continue
            if (not has_a_vowel_re.search(w)):
                continue

            key = Bag(w)
            hash_table[key].add(w)

    print("done", file=sys.stderr)

    print(max(hash_table., key=lambda))
        

    return hash_table
'''

script = jedi.Script(column=25, source=source, line=41, encoding='utf-8', path=u'/Users/erichanchrow/git-repositories/me/anagrams/python/dict.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thank you! Reported upstream, so this Jedi bug can be fixed :-)
