### ISSUE TITLE
Yet another

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#570]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

u'command'

Configuration

Virtualenv........: rack (/Users/erichanchrow/.virtualenvs/rack)
RPC Python........: 2.7.6 (/Users/erichanchrow/.virtualenvs/rack/bin/python)
Interactive Python: python (/Users/erichanchrow/.virtualenvs/rack/bin/python)
Emacs.............: 24.5.50.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/Users/erichanchrow/.virtualenvs/rack/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/erichanchrow/.virtualenvs/rack/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'command'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
# Core
import logging
import SocketServer

# 3rd-party
from telnetsrv.threaded import TelnetHandler, command  # pip install telnetsrv

logger = logging.getLogger()


class MyTelnetHandler(TelnetHandler):
    WELCOME = "Fake Cisco Access server"
    PROMPT = 'INE-RACK-ACCESS#'
    logging = logger

    authNeedUser = True
    authNeedPass = True

    def authCallback(self, username, password):
        logging.debug("authcallback called with %r and %r", username, password)
        if username == '':
            e = Exception("Bad username -- you seem to be whuppin' the Return key")
            logging.warn("Raising %s", e)
            raise e

        self.writeresponse("Welcome {}.  Your password is {!r}.  Oh, did I say that out loud?".format(username, password))

    @command('terminal')
    def command_terminal(self, params):
        self.writeresponse('yeah, sure, fine, whatever')

    @command('show')
    def command_show(self, params):
        for l in range(10):
            self.writeresponse(' {} vty wooga wooga'.format(l))

    @command('!')
    def


class TelnetServer(SocketServer.TCPServer):
    allow_reuse_address = True

    def handle_error(self, request, client_address):
        logger.warn("Ah, I see something about %s from %s pissed me off", request, client_address)

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    server = TelnetServer(("0.0.0.0", 2323), MyTelnetHandler)
    server.handle_request()
'''

script = jedi.Script(column=7, source=source, line=38, encoding='utf-8', path=u'/Users/erichanchrow/git-repositories/ine-rackcontrol/branch/fake_access_server.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report, and sorry for the inconvenience you apparently get from these bugs.

This looks very similar to #564 and #561 …

**Comment by offby1** [comment]
Honestly I'm not even looking at them; I just kill the bug-report buffer and continue working.

**Comment by ChillarAnand** [comment]
i got one more error.


Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

u'python_2_unicode_compatible'

Configuration

Virtualenv........: junction (/home/anand/.virtualenvs/junction)
RPC Python........: 2.7.6 (/home/anand/.virtualenvs/junction/bin/python)
Interactive Python: python (/home/anand/.virtualenvs/junction/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: flake8 (/home/anand/.virtualenvs/junction/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/anand/projects/lisp/elpy/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/anand/.virtualenvs/junction/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'python_2_unicode_compatible'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

# Third Party Stuff
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django_extensions.db.fields import AutoSlugField

# Junction Stuff
from junction.base.constants import (
    PROPOSAL_REVIEW_STATUS_LIST,
    PROPOSAL_STATUS_LIST,
    PROPOSAL_TARGET_AUDIENCES,
    PROPOSAL_USER_VOTE_ROLES
)
from junction.base.models import AuditModel, TimeAuditModel
from junction.conferences.models import Conference


@python_2_unicode_compatible
class ProposalSection(AuditModel):

    """ List of Proposal Sections"""
    name = models.CharField(max_length=255, verbose_name="Proposal Section Name")
    description = models.TextField(default="")
    active = models.BooleanField(default=True, verbose_name="Is Active?")
    conferences = models.ManyToManyField(to=Conference, related_name='proposal_sections')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class ProposalSectionReviewer(AuditModel):

    """ List of Proposal Section Reviewers"""
    conference_reviewer = models.ForeignKey('conferences.ConferenceProposalReviewer',
                                            verbose_name="Conference Proposal Reviewers")
    proposal_section = models.ForeignKey(ProposalSection, verbose_name="Proposal Section")
    active = models.BooleanField(default=True, verbose_name="Is Active?")

    def __str__(self):
        return "{}:[{}]".format(self.conference_reviewer, self.proposal_section)


@python_2_unicode_compatible
class ProposalType(AuditModel):

    """ List of Proposal Types """
    name = models.CharField(max_length=255, verbose_name="Proposal Type Name")
    description = models.TextField(default="")
    active = models.BooleanField(default=True, verbose_name="Is Active?")
    conferences = models.ManyToManyField(to=Conference, related_name='proposal_types')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Proposal(TimeAuditModel):

    """ The proposals master """
    conference = models.ForeignKey(Conference)
    proposal_section = models.ForeignKey(ProposalSection, verbose_name="Proposal Section")
    proposal_type = models.ForeignKey(ProposalType, verbose_name="Proposal Type")
    author = models.ForeignKey(User, verbose_name="Primary Speaker")
    title = models.CharField(max_length=255)
    slug = AutoSlugField(max_length=255, populate_from=('title',))
    description = models.TextField(default="")
    target_audience = models.PositiveSmallIntegerField(
        choices=PROPOSAL_TARGET_AUDIENCES, default=1, verbose_name="Target Audience")
    prerequisites = models.TextField(blank=True, default="")
    content_urls = models.TextField(blank=True, default="")
    speaker_info = models.TextField(blank=True, default="")
    speaker_links = models.TextField(blank=True, default="")
    status = models.PositiveSmallIntegerField(
        choices=PROPOSAL_STATUS_LIST, default=1)
    review_status = models.PositiveSmallIntegerField(
        choices=PROPOSAL_REVIEW_STATUS_LIST, default=1, verbose_name="Review Status")
    deleted = models.BooleanField(default=False, verbose_name="Is Deleted?")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('proposal-detail', args=[self.conference.slug, self.slug])

    def get_update_url(self):
        return reverse('proposal-update', args=[self.conference.slug, self.slug])

    def get_review_url(self):
        return reverse('proposal-review', args=[self.conference.slug, self.slug])

    def get_delete_url(self):
        return reverse('proposal-delete', args=[self.conference.slug, self.slug])

    def get_up_vote_url(self):
        return reverse('proposal-vote-up', args=[self.conference.slug, self.slug])

    def get_down_vote_url(self):
        return reverse('proposal-vote-down', args=[self.conference.slug, self.slug])

    def get_comments_count(self):
        """ Show only the public comment count """
        return ProposalComment.objects.filter(proposal=self, deleted=False, private=False).count()

    def get_reviews_comments_count(self):
        """ Show only the public comment count """
        return ProposalComment.objects.filter(proposal=self, deleted=False, private=True).count()

    def get_votes_count(self):
        """ Show only the public comment count """
        up_vote_count = ProposalVote.objects.filter(proposal=self, up_vote=True).count()
        down_vote_count = ProposalVote.objects.filter(proposal=self, up_vote=False).count()
        return up_vote_count - down_vote_count

    def status_text(self):
        """ Text representation of status values """
        for value, text in PROPOSAL_STATUS_LIST:
            if self.status == value:
                return text

    class Meta:
        unique_together = ("conference", "slug")


@python_2_unicode_compatible
class ProposalVote(TimeAuditModel):

    """ User vote for a specific proposal """
    proposal = models.ForeignKey(Proposal)
    voter = models.ForeignKey(User)
    role = models.PositiveSmallIntegerField(
        choices=PROPOSAL_USER_VOTE_ROLES, default=1)
    up_vote = models.BooleanField(default=True)

    def __str__(self):
        return "[{}] {}".format("1" if self.up_vote else "-1", self.proposal)

    class Meta:
        unique_together = ("proposal", "voter")


@python_2_unicode_compatible
class Proposal lReviewerVote(TimeAuditModel):

    """ Reviewer vote for a specific proposal """
    proposal = models.ForeignKey(Proposal)
    voter = models.ForeignKey(ProposalSectionReviewer)
    role = models.PositiveSmallIntegerField(choices=PROPOSAL_USER_VOTE_ROLES, default=2)
    up_vote = models.BooleanField(default=True)

    def __str__(self):
        return "[{}] {}".format("1" if self.up_vote else "-1", self.proposal)

    class Meta:
        unique_together = ("proposal", "voter")


@python_2_unicode_compatible
class ProposalComment(TimeAuditModel):

    """ User comments for a specific proposal """
    proposal = models.ForeignKey(Proposal)
    commenter = models.ForeignKey(User)
    private = models.BooleanField(default=False, verbose_name="Is Private?")
    comment = models.TextField()
    deleted = models.BooleanField(default=False, verbose_name="Is Deleted?")

    def __str__(self):
        return "[{} by {}] {}".format(self.comment,
                                      self.commenter.get_full_name(),
                                      self.proposal)

    def get_up_vote_url(self):
        return reverse('proposal-comment-up-vote', args=[self.proposal.conference.slug, self.proposal.slug, self.id])

    def get_down_vote_url(self):
        return reverse('proposal-comment-down-vote', args=[self.proposal.conference.slug, self.proposal.slug, self.id])

    def get_votes_count(self):
        up_vote_count = ProposalCommentVote.objects.filter(proposal_comment=self, up_vote=True).count()
        down_vote_count = ProposalCommentVote.objects.filter(proposal_comment=self, up_vote=False).count()
        return up_vote_count - down_vote_count


@python_2_unicode_compatible
class ProposalCommentVote(TimeAuditModel):

    """ User vote for a specific proposal's comment """
    proposal_comment = models.ForeignKey(ProposalComment)
    voter = models.ForeignKey(User)
    up_vote = models.BooleanField(default=True)

    def __str__(self):
        return "[{}] {}".format("1" if self.up_vote else "-1", self.proposal_comment)

    class Meta:
        unique_together = ("proposal_comment", "voter")
'''

script = jedi.Script(column=14, source=source, line=147, encoding='utf-8', path=u'/home/anand/projects/python/django/junction/junction/proposals/models.py')
script.completions()
```
