### ISSUE TITLE
Elpy/rope refactor menu producing errors, functionality limited

### ISSUE THREAD

**Issue by jskulski** [jorgenschaefer/elpy#577]
Hey Jorgen + et al,

I'm relatively new to emacs. I'm having some issues with getting the refactor menu to work as expected.

As far as I can tell, everything is installed correctly but I run into this error:

 'NoneType' object has no attribute 'group'

When I try to Extract Method. Renaming variables and modules seem to work. I haven't really used rope before, so I'm not very familiar with all the methods. I just tried a few things.

Reorganizing imports seems to work.
Renaming variables works for file (not project)
Module renaming works

Inlining function/moving module to new package causes the same error.

I am using linux mint
Installed emacs through apt-get
Installed rope/jedi/falke8 through pip 
I installed elpy through package-install

Thanks for reading. If there's anything else I can provide, let me know. Thanks!

-----

Here is the trace:
```
Error Message

'NoneType' object has no attribute 'group'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/jskulski/.emacs.d/elpa/elpy-20150502.740/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/jskulski/.emacs.d/elpa/elpy-20150502.740/elpy/server.py", line 186, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/jskulski/.emacs.d/elpa/elpy-20150502.740/elpy/refactor.py", line 210, in get_changes
    return method(*args)
  File "/home/jskulski/.emacs.d/elpa/elpy-20150502.740/elpy/refactor.py", line 300, in refactor_extract_method
    changes = refactor.get_changes(name, similar=True, global_=make_global)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/extract.py", line 68, in get_changes
    new_contents = _ExtractPerformer(info).extract()
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/extract.py", line 215, in extract
    extract_info = self._collect_info()
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/extract.py", line 244, in _collect_info
    self._find_matches(extract_collector)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/extract.py", line 250, in _find_matches
    finder = similarfinder.SimilarFinder(self.info.pymodule)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/similarfinder.py", line 28, in __init__
    pymodule.source_code, pymodule.get_ast(), self._does_match)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/similarfinder.py", line 77, in __init__
    self._init_using_ast(node, source)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/similarfinder.py", line 86, in _init_using_ast
    patchedast.patch_ast(node, source)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 33, in patch_ast
    ast.call_for_nodes(node, walker)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 493, in _Module
    self._handle(node, list(node.body), eat_spaces=True)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 292, in _ClassDef
    self._handle(node, children)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 385, in _FunctionDef
    self._handle(node, children)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 329, in _Expr
    self._handle(node, [node.value])
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 277, in _Call
    self._handle(node, children)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 255, in _BinOp
    self._handle(node, children)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 323, in _Dict
    self._handle(node, children)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 104, in _handle
    ast.call_for_nodes(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 57, in call_for_nodes
    result = callback(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 76, in __call__
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 309, in _Str
    self._handle(node, [self.String])
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 109, in _handle
    end=self._find_next_statement_start())
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 662, in consume_string
    return self._consume_pattern(repattern, end)
  File "/usr/local/lib/python2.7/dist-packages/rope/refactor/patchedast.py", line 707, in _consume_pattern
    if self._good_token(match.group(), match.start()):
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

This is a bug in the Rope library. Elpy should catch that one and not display the "big" error like this, but that won't make the functionality work, sadly. Rope is very limited as far as refactoring goes, so I'm afraid there is not much to be done here – either it works, or it doesn't.

**Comment by jskulski** [comment]
That's unfortunate, but thanks for the response!

**Comment by jorgenschaefer** [comment]
Indeed. I wish things would work better. :-(

**Comment by jorgenschaefer** [comment]
Even though it's a bit of a let-down, I guess that answers the problem here. Please do not hesitate to create a new issue if you have further problems. I hope we can help more with them, then! :-)
