### ISSUE TITLE
Use function works for global functions, only.

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#578]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

Use function works for global functions, only.

Configuration

Virtualenv........: py3 (/home/anand/.virtualenvs/py3)
RPC Python........: 3.4.0 (/home/anand/.virtualenvs/py3/bin/python)
Interactive Python: python (/home/anand/.virtualenvs/py3/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/home/anand/.virtualenvs/py3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/anand/projects/lisp/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/anand/projects/lisp/elpy/elpy/server.py", line 187, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/anand/projects/lisp/elpy/elpy/refactor.py", line 210, in get_changes
    return method(*args)
  File "/home/anand/projects/lisp/elpy/elpy/refactor.py", line 308, in refactor_use_function
    refactor = UseFunction(self.project, self.resource, offset)
  File "/home/anand/.virtualenvs/py3/lib/python3.4/site-packages/rope/refactor/usefunction.py", line 20, in __init__
    'Use function works for global functions, only.')
rope.base.exceptions.RefactoringError: Use function works for global functions, only.
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This should cause a normal error display in the minibuffer, not a full Elpy error.
