### ISSUE TITLE
Breaks when writing Python properties

### ISSUE THREAD

**Issue by chendaniely** [jorgenschaefer/elpy#588]
Hi:

I'm not sure if this is an elpy or jedi bug, something always breaks when I begin writing python `property` methods:

    Elpy Error    

    The backend encountered an unexpected error. This indicates a bug in
    Elpy. Please open a bug report with the data below in the Elpy bug
    tracker:    

    https://github.com/jorgenschaefer/elpy/issues/new    

    ```
    Error Message    

    'property'    

    Configuration    

    Virtualenv........: None
    RPC Python........: 3.4.3 (/home/dchen/anaconda3/envs/mann/bin/python)
    Interactive Python: python (/home/dchen/anaconda3/envs/mann/bin/python)
    Emacs.............: 24.5.1
    Elpy..............: 1.8.0
    Jedi..............: 0.9.0
    Rope..............: 0.9.4-1
    Importmagic.......: 0.1.3
    Syntax checker....: flake8 (/home/dchen/anaconda3/envs/mann/bin/flake8)    

    Traceback    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '_user_stmt'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '__parser'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
        clear_names(c.children)
    AttributeError: 'Name' object has no attribute 'children'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 216, in run_with_debug
        return getattr(script, name)()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/api/__init__.py", line 185, in completions
        user_stmt = self._parser.user_stmt_with_whitespace()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
        user_stmt = self.user_stmt()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
        module = self.module()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 339, in module
        return self._parser().module
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 283, in _parser
        parser = FastParser(self._grammar, self._source, self._path)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 109, in __call__
        p.update(source)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 257, in update
        self._parse(source)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 383, in _parse
        line_offset, nodes)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 435, in _get_node
        p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 155, in __init__
        self.module = p.parse(self._tokenize(tokenizer))
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
        if self.addtoken(type, value, prefix, start_pos):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
        value, start_pos, prefix, self.addtoken)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
        self._stack_removal(grammar, stack, index + 1, value, start_pos)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
        clear_names(children=node[1])
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
        clear_names(c.children)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 298, in clear_names
        self._scope_names_stack[-1][c.value].remove(c)
    KeyError: 'property'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '_user_stmt'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 141, in wrapper
        return getattr(self, name)
    AttributeError: 'UserContextParser' object has no attribute '__parser'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
        clear_names(c.children)
    AttributeError: 'Name' object has no attribute 'children'    

    During handling of the above exception, another exception occurred:    

    Traceback (most recent call last):
      File "/home/dchen/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
        return getattr(script, name)()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/api/__init__.py", line 185, in completions
        user_stmt = self._parser.user_stmt_with_whitespace()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
        user_stmt = self.user_stmt()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
        module = self.module()
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 339, in module
        return self._parser().module
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/cache.py", line 143, in wrapper
        result = func(self)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/user_context.py", line 283, in _parser
        parser = FastParser(self._grammar, self._source, self._path)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 109, in __call__
        p.update(source)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 257, in update
        self._parse(source)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 383, in _parse
        line_offset, nodes)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/fast.py", line 435, in _get_node
        p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 155, in __init__
        self.module = p.parse(self._tokenize(tokenizer))
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
        if self.addtoken(type, value, prefix, start_pos):
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
        value, start_pos, prefix, self.addtoken)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
        self._stack_removal(grammar, stack, index + 1, value, start_pos)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
        clear_names(children=node[1])
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 294, in clear_names
        clear_names(c.children)
      File "/home/dchen/.local/lib/python3.4/site-packages/jedi/parser/__init__.py", line 298, in clear_names
        self._scope_names_stack[-1][c.value].remove(c)
    KeyError: 'property'    

    Jedi Debug Information    

    Jedi did not emit any debug info.    

    ```    

    Reproduction:    

    ```Python
    import jedi    

    source = '''\
    #! /usr/bin/env python    

    import random    

    import mann.agent    
    

    class BinaryAgent(mann.agent.Agent):
        binary_agent_count = 0    

        def __init__(self):
            self.agent_id = BinaryAgent.binary_agent_count
            BinaryAgent.binary_agent_count += 1    

            self.state = 0
            self.num_update = 0
            self.step_update_status = 0
            self.predecessors = [None]    

            self.reset_step_variables()    

        # def set_binary_state(self, value):
        #     # binary state means 0 or 1
        #     assert value in [0, 1],\
        #         "binary state can only be 0 or 1, got %r" % value    

        #     # make sure we are only changing the state when the value is different
        #     assert value != self.binary_state, "changing state to same value"    

        #     self.binary_state = value    

        # def get_state(self):
        #     return self.binary_state    

        def seed_agent(self, seed_value=1):
            """Seed agent
            """
            self.state = seed_value
            return(self)    

        def random_binary_state(self):
            '''
            generates a random state for the agent as it is created
            raises exception if state cannot be assign    

            Returns:
                int: value of 0 or 1 for a :py:data::self.state
            '''
            random_float = random.random()
            if random_float < .5:
                return 0
            elif random_float >= .5:
                return 1
            # else:
            #     return -1
            #     raise Exception("Error in _random_state")    

        def reset_step_variables(self):
            self.step_update_status = None
            return(self)    

        def _update_agent_state_default(self):
            '''
            Looks at the list of predessors for the selected agent
            randomly picks one of them
            if the selected predessor is has a different state
            there will be a 70% chance that the selected agent will change states
            to match the predessor's state
            otherwise no state is changed
            '''
            # print('in _update_agent_state_default')
            # print("type of predecssors: ",  type(self.predecessors))  # list
            # print("container of predessors: ", self.predecessors)
            predecessor_picked = random.sample(list(self.predecessors), 1)[0]
            # print("predecessor picked: ", predecessor_picked)
            # print("predecessor picked key: ", predecessor_picked.get_key())
            if self.binary_state == predecessor_picked.binary_state:
                # print("no update required, binary states are the same")
                # print("self.binary_state = ", self.binary_state)
                # print("predecessor_picked.binary_state = ",
                #       predecessor_picked.binary_state)
                pass
            else:
                # print('updateing agent state')
                random_number = random.random()
                if random_number < 0.7:
                    self.set_binary_state(predecessor_picked.binary_state)
                else:
                    pass    

        def update_agent_state(self, pick='default'):
            '''
            pick = 'default': uses the update_agent__state_default algorithm
            '''
            # print('in update_agent_state')
            # print('has predecessors', self.has_predessor())
            if self.has_predessor():
                if pick == 'default':
                    self._update_agent_state_default()
                else:
                    raise ValueError("Algorithm used for pick unknown")
            else:
                pass    

        @property
        def agent_id(self):
            return self._agent_id    

        @agent_id.setter
        def agent_id(self, id_value):
            self._agent_id = id_value    

        @property
        def num_update(self):
            return self._num_update    

        @num_update.setter
        def num_update(self, num):
            assert num == 0 or num == self._num_update + 1,\
                "Tried to increment num_update by {}, which is not 1".\
                format(str(num))
            self._num_update = num    

        @property
        def state(self):
            return self._state    

        @state.setter
        def state(self, new_state):
            assert new_state in [0, 1, None], \
                "New state for BinaryAgent must be 0, 1, or None.  "\
                "Tried to set a value of {}".\
                format(str(new_state))
            self._state = new_state    

        @property
        def sdl
    '''    

    script = jedi.Script(source=source, column=11, path='/home/dchen/git/vbi/multi-agent-neural-network/mann/agent_binary.py', line=137, encoding='utf-8')
    script.completions()
    ```

**Comment by jorgenschaefer** [comment]
Thank you for the report!
The error looks like davidhalter/jedi#590 – I guess we hope for a bugfix release of Jedi soon.
