### ISSUE TITLE
"The backend encountered an unexpected error... KeyError: u'self'"

### ISSUE THREAD

**Issue by njsmith** [jorgenschaefer/elpy#593]
```
Error Message

u'self'

Configuration

Virtualenv........: .user-python2.7-64bit-3 (/home/njs/.user-python2.7-64bit-3)
RPC Python........: 2.7.8 (/home/njs/.user-python2.7-64bit-3/bin/python)
Interactive Python: ipython (/home/njs/.user-python2.7-64bit-3/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/home/njs/.user-python2.7-64bit-3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'self'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
# This file is part of pycam02ucs
# Copyright (C) 2014 Nathaniel Smith <njs@pobox.com>
# See file LICENSE.txt for license information.

import numpy as np
import collections

class PathKeeper(object):
    def __init__(self):
        self._paths = defaultdict(lambda

    def add_connection(self, source, target, data):
        self._paths[(source, target)] = [data]
        queue = [(source, target, [data])]
        while queue:
            source, target, data = queue.pop()
            current_path = self._paths.get((source, target))
            if current_path is None or len(data) < len(current_path):
                self._paths[(source, target)] = [data]
            
        

################################################################

from .srgb import sRGB_to_XYZ, XYZ_to_sRGB

def _XYZ_to_XYZ(XYZ):
    XYZ = np.asarray(XYZ, dtype=float)
    return XYZ

def _XYZ_to_xyY(XYZ):
    XYZ = np.asarray(XYZ, dtype=float)
    norm = np.sum(arr, axis=-1, keepdims=True)
    xy = XYZ[..., :2] / norm
    return np.concatenate((xy, XYZ[..., 2:3]), axis=-1)

def _xyY_to_XYZ(xyY):
    xyY = np.asarray(xyY, dtype=float)
    x = xyY[..., 0]
    y = xyY[..., 1]
    Y = xyY[..., 2]
    X = Y / y * x
    Z = Y / y * (1 - x - y)
    return np.concatenate((X[..., np.newaxis],
                           Y[..., np.newaxis],
                           Z[..., np.newaxis]),
                          axis=-1)

to_XYZ = {
    "XYZ": _XYZ_to_XYZ,
    "xyY": _xyY_to_XYZ,
    "sRGB": _sRGB_to_XYZ,
    }

_CIECAM02_coordinates = set("JChQMsH")

# sRGB -> CIECAM02, only one viewing condition possible
#   and maybe want some arbitrary JMhH or something
# also: subset of CIECAM02 -> different subset of CIECAM02
# XYZ, xyY -> CIECAM02 under arbitrary viewing conditions
# CIECAM02 -> CAM02-space,

# XYZ is 0-100
# CIECAM02 stuff is always 0-100
# CAM02-xxx ditto
# xyY is... what? (0-1, 0-1, 0-100) I guess.
# sRGB is 0-1

# colorblindness is a perceptual thing, not a light thing, so I guess we apply
# there?
# convert sRGB -> CIECAM02-with-colorblindness, then CIECAM02 -> sRGB? kinda
# weird given that we have the direct matrices, but makes it easier to reason
# about I guess?

def convert(arr, start, end, viewing_conditions=ViewingConditions.sRGB):
    pass
'''

script = jedi.Script(column=40, source=source, line=10, encoding='utf-8', path=u'/home/njs/pycam02ucs/pycam02ucs/util.py')
script.completions()
```

**Comment by njsmith** [comment]
(I'd just typed the "lambda" on the 10th line of the file, when this error message popped up.)

**Comment by jorgenschaefer** [comment]
Thanks for the report!

This is a recurring (and highly annoying) bug in Jedi. 

Reported in #588, #570, #564, #561 and reported upstream as davidhalter/jedi#579 over a month ago. Elpy should probably just catch that error and ignore it. Sorry for the inconvenience. :-/

**Comment by njsmith** [comment]
Ah, thanks. Feel free to close then.

On Tue, Jun 16, 2015 at 1:38 AM, Jorgen Schäfer <notifications@github.com>
wrote:

> Thanks for the report!
>
> This is a recurring (and highly annoying) bug in Jedi.
>
> Reported in #588 <https://github.com/jorgenschaefer/elpy/issues/588>, #570
> <https://github.com/jorgenschaefer/elpy/issues/570>, #564
> <https://github.com/jorgenschaefer/elpy/issues/564>, #561
> <https://github.com/jorgenschaefer/elpy/issues/561> and reported upstream
> as davidhalter/jedi#579 <https://github.com/davidhalter/jedi/issues/579>
> over a month ago. Elpy should probably just catch that error and ignore it.
> Sorry for the inconvenience. :-/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jorgenschaefer/elpy/issues/593#issuecomment-112339095>
> .
>



-- 
Nathaniel J. Smith -- http://vorpus.org
