### ISSUE TITLE
jedi error: "list index out of range"

### ISSUE THREAD

**Issue by njsmith** [jorgenschaefer/elpy#595]
Hi, me again.

```
Error Message

list index out of range

Configuration

Virtualenv........: .user-python2.7-64bit-3 (/home/njs/.user-python2.7-64bit-3)
RPC Python........: 2.7.8 (/home/njs/.user-python2.7-64bit-3/bin/python)
Interactive Python: ipython (/home/njs/.user-python2.7-64bit-3/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/home/njs/.user-python2.7-64bit-3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/server.py", line 86, in rpc_get_calltip
    get_source(source), offset)
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "/home/njs/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/tree.py", line 1185, in name
    if is_node(self._tfpdef(), 'tfpdef'):
  File "/home/njs/.user-python2.7-64bit-3/local/lib/python2.7/site-packages/jedi/parser/tree.py", line 1181, in _tfpdef
    return self.children[offset]
IndexError: list index out of range
```

This one happened as I was editing a function signature to add a `*args` at the end -- I typed `*` and the traceback popped up.

**Comment by jorgenschaefer** [comment]
Thank you for the report!

Can you provide more detailed reproduction steps? Writing a function with `*args` seems to work fine here. (If not, no problem, I'll pass it on upstream anyhow; but if you have some simple reproduction steps, that'd be great :-))

**Comment by njsmith** [comment]
No idea, sorry! I can also write a function with *args normally, just
this time for some reason it blew up. And unfortunately I didn't save
a snapshot of the file... and I guess elpy didn't dump a reproducible
test case this time. So... good luck? :-)

On Tue, Jun 16, 2015 at 1:33 AM, Jorgen Schäfer
<notifications@github.com> wrote:
> Thank you for the report!
>
> Can you provide more detailed reproduction steps? Writing a function with
> *args seems to work fine here. (If not, no problem, I'll pass it on upstream
> anyhow; but if you have some simple reproduction steps, that'd be great :-))
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Nathaniel J. Smith -- http://vorpus.org

**Comment by gopar** [comment]
Jedi issue, not elpy
