### ISSUE TITLE
elpy crashing at random, requests I file the below report

### ISSUE THREAD

**Issue by dradetsky** [jorgenschaefer/elpy#599]
```
Error Message

u'property'

Configuration

Virtualenv........: None
RPC Python........: 2.7.9 (/usr/bin/python)
Interactive Python: ipython (/usr/local/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/home/dmr/.local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/dmr/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/home/dmr/.local/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'property'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
class Syncer(object):
    def __init__(self, target_file, src_path, dest_path):
        pass

    @property
    def full_path(self):
        pass

    @property
    def key_n
'''

script = jedi.Script(column=13, source=source, line=10, encoding='utf-8', path=u'/home/dmr/6si/ntropy/jobs/sync-sftp/clssync.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thank you very much for the report!

This is a known bug in Jedi which is not yet fixed – I will have to add a workaround for this to Elpy, as it seems to be triggering a lot. Sorry for the inconvenience!

**Comment by dradetsky** [comment]
Yeah, well, that's how it goes sometimes. I've had to disable elpy as it's unusable, but if you let me know when you push a fix for this, I'll try it out and let you know how it goes.

FYI, this was happening before I even installed jedi. Since the error was sometimes almost nothing but "jedi produced no debug info", I thought this was the problem and installed jedi, but nothing changed.

**Comment by jorgenschaefer** [comment]
Huh. Without Jedi, this should be a very different error – are you sure it's the same?

You can set `elpy-rpc-error-timeout` to a large value to disable showing of such errors and see if that improves things.

The following patch should disable this specific error:

```diff
diff --git a/elpy/jedibackend.py b/elpy/jedibackend.py
index e51f250..7605b7b 100644
--- a/elpy/jedibackend.py
+++ b/elpy/jedibackend.py
@@ -283,6 +283,8 @@ def run_with_debug(jedi, name, *args, **kwargs):
                 "No such file or directory" in str(e)
         ):
             return None
+        if isinstance(e, KeyError):
+            return None
 
         from jedi import debug
 
```

Does that help?

**Comment by dradetsky** [comment]
I'm pretty sure it was the same error, but the overall behavior of crashing
every couple seconds was the same. I can remove jedi and try again if it's
important.

**Comment by jorgenschaefer** [comment]
See if you get more errors with the above patch :-)

**Comment by chumsley** [comment]
Thanks for the awesome package!

I have what appears to be the same error in the jedi backend.  I can trigger it by writing a decorator and then starting to define a function.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

u'randec'

Configuration

Virtualenv........: None
RPC Python........: 2.7.8 (/Users/james/anaconda/bin/python)
Interactive Python: ipython (/Users/james/anaconda/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.9.4 (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Syntax checker....: pyflakes (/Users/james/anaconda/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/james/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/james/anaconda/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'randec'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
def randec(fn):
    """Rando's favourite decorator"""
    return fn

@randec
def'''

script = jedi.Script(column=3, source=source, line=6, encoding='utf-8', path=u'/tmp/minimal.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thanks for the report! I hope to release a bugfix release that addresses specifically this problem soon. Sorry for the inconvenience.
