### ISSUE TITLE
Another Jedi Error - <Name: deprecate@244,11>

### ISSUE THREAD

**Issue by ajsteven130** [jorgenschaefer/elpy#601]
On Windows 7, i have no problems with jedi-0.8.1, but upgrading to 0.9.0 causes an error in the backend the first time it tries to do a completion. I confirmed that this error only pops up on jedi-0.9.0 by going back and forth between the two versions.

Thanks very much for the awesome package and for any help with this problem.

 Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

<Name: deprecate@244,11>

Configuration

Virtualenv........: None
RPC Python........: 3.4.1 (c:/Anaconda3/python.exe)
Interactive Python: C:\Anaconda3\python.exe (c:/Anaconda3/python.exe)
Emacs.............: 24.5.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.3
Syntax checker....: flake8.exe (c:/Anaconda3/Scripts/flake8.exe)

Traceback

Traceback (most recent call last):
  File "c:\Users\A6419643\.emacs.d\elpa\elpy-20150502.740\elpy\rpc.py", line 100, in handle_request
    result = method(*params)
  File "c:\Users\A6419643\.emacs.d\elpa\elpy-20150502.740\elpy\server.py", line 93, in rpc_get_completions
    get_source(source), offset)
  File "c:\Users\A6419643\.emacs.d\elpa\elpy-20150502.740\elpy\server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "c:\Users\A6419643\.emacs.d\elpa\elpy-20150502.740\elpy\jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "c:\Users\A6419643\.emacs.d\elpa\elpy-20150502.740\elpy\jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "c:\Anaconda3\lib\site-packages\jedi\api\classes.py", line 470, in type
    followed = self.follow_definition()
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\api\classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\api\classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\imports.py", line 103, in follow
    for t in types))
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\imports.py", line 103, in <genexpr>
    for t in types))
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "c:\Anaconda3\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "c:\Anaconda3\lib\site-packages\jedi\debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\__init__.py", line 299, in execute
    types = func(self, arguments)
  File "c:\Anaconda3\lib\site-packages\jedi\_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
  File "c:\Anaconda3\lib\site-packages\jedi\evaluate\helpers.py", line 55, in <listcomp>
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@244,11>
```

**Comment by ajsteven130** [comment]
This is a repeat of [597](https://github.com/jorgenschaefer/elpy/issues/597). I clicked through the issues with jedi in the title, but only stumbled on https://github.com/jorgenschaefer/elpy/issues/597 after posting this issue. 

I see that you are on top of it.

**Comment by jorgenschaefer** [comment]
Thank you for the report!

While this is indeed the same as #597, do you perchance have a simpler reproduction case that does not involve matplotlib? :-)

**Comment by jorgenschaefer** [comment]
Let's track this issue over in #597!
