### ISSUE TITLE
'Operator' object has no attribute 'get_definition'  

### ISSUE THREAD

**Issue by PatchesNULL** [jorgenschaefer/elpy#627]
Configuration
```
Virtualenv........: None
RPC Python........: 3.4.3 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.5.1
Elpy..............: 1.8.1
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)
```
Traceback
```
Traceback (most recent call last):
  File "/home/Patches/.emacs.d/elpa/elpy-1.8.1/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/Patches/.emacs.d/elpa/elpy-1.8.1/elpy/server.py", line 86, in rpc_get_calltip
    get_source(source), offset)
  File "/home/Patches/.emacs.d/elpa/elpy-1.8.1/elpy/server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "/home/Patches/.emacs.d/elpa/elpy-1.8.1/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/usr/lib/python3.4/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/usr/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.4/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.4/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
```

To recreate, I just open any python file and try to use urllibs urlopen

```
import urllib

urllib.request.urlopen(HAPPENSHERE)
```

Can provide more information as you need it. So far it only happens with urlopen().

**Comment by jorgenschaefer** [comment]
Thank you for the report!

This is strange, I can't reproduce this – can you provide the full output from Elpy (that includes Jedi debug output and a reproduction case)?

**Comment by jorgenschaefer** [comment]
Ok, found a reproduction case – I think I was using the wrong Python, not sure. While checking the Jedi bug tracker, I noticed I had reported this before as davidhalter/jedi#573. As this seems to take a while to get fixed upstream, Elpy should probably add some code to ignore this error.
