### ISSUE TITLE
Unexpected output from elpy backend.

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#646]
Output from Backend

There was some unexpected output from the Elpy backend. This is
usually some module that does not use correct logging, but might
indicate a configuration problem.

Output
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
```

**Comment by jorgenschaefer** [comment]
Thanks for the report. What were you doing when you got this? Was there any other output? Can you run the Elpy RPC process manually in that environment and receive similar messages?

**Comment by ChillarAnand** [comment]
I just opened some python file from elpy. It didn't produce any other output.

Not able to reproduce it.

**Comment by jorgenschaefer** [comment]
Very strange. :-/

**Comment by ChillarAnand** [comment]
Closing as this bug is not reproducible.

**Comment by ChillarAnand** [comment]
I stumbled on this bug again. 

I have made some changes to elpy code base and there were some errors in it. That's why it was throwing error. Nothing to do with elpy. :-)

**Comment by jorgenschaefer** [comment]
Ohh, good! Thanks for the follow-up, and glad you found the problem :-)
