### ISSUE TITLE
Syntax error: expected an indented block

### ISSUE THREAD

**Issue by ChillarAnand** [jorgenschaefer/elpy#648]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

Syntax error in file <apps/project/views.py> line <129>: expected an indented block

Configuration

Virtualenv........: exp (/home/k3/.virtualenvs/exp)
RPC Python........: 2.7.6 (/home/k3/.virtualenvs/exp/bin/python)
Interactive Python: python (/home/k3/.virtualenvs/exp/bin/python)
Emacs.............: 24.4.1
Elpy..............: 1.8.1
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/home/k3/.virtualenvs/exp/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/k3/anand/projects/lisp/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/k3/anand/projects/lisp/elpy/elpy/server.py", line 187, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/k3/anand/projects/lisp/elpy/elpy/refactor.py", line 210, in get_changes
    return method(*args)
  File "/home/k3/anand/projects/lisp/elpy/elpy/refactor.py", line 250, in refactor_rename_at_point
    refactor = Rename(self.project, self.resource, offset)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/rope/refactor/rename.py", line 24, in __init__
    this_pymodule = self.pycore.resource_to_pyobject(self.resource)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/rope/base/pycore.py", line 197, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/rope/base/pycore.py", line 323, in get_pymodule
    force_errors=force_errors)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/rope/base/pyobjectsdef.py", line 155, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/home/k3/.virtualenvs/exp/local/lib/python2.7/site-packages/rope/base/pyobjectsdef.py", line 184, in _init_source
    raise exceptions.ModuleSyntaxError(filename, e.lineno, e.msg)
ModuleSyntaxError: Syntax error in file <apps/project/views.py> line <129>: expected an indented block
```

**Comment by jorgenschaefer** [comment]
Thanks for the report! Elpy probably should catch all the `rope.*` errors for Rope calls and turn them into normal Emacs errors, instead of full backtraces.
