### ISSUE TITLE
The backend encountered an unexpected error.

### ISSUE THREAD

**Issue by vinayak-kaniyarakkal** [jorgenschaefer/elpy#655]
Hii,

I got a buffer opened with following content

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

u'query'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/mahiti/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'query'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
from django.views import generic as g
from common_methods import auto_as_view
from cfeeds.models import Question
#


class ManageMixin(object):

    model = Question

    def get_object(self):
        qs = self.get_queryset()
        return qs.get(id=self.kwargs.get('object_id'))

    def get_queryset(self):
        query = {}
        if self.kwargs.get('fpm'):
            query = lambda{'feed__code': self.kwargs.get('fpm')})
        return self.model.objects.filter(**query)
#


@auto_as_view
class ListCFeed(ManageMixin, g.ListView):

    pass
#


@auto_as_view
class AddCFeed(ManageMixin, g.CreateView):

    pass
#


@auto_as_view
class EditCFeed(ManageMixin, g.UpdateView):

    pass
#
'''

script = jedi.Script(column=26, source=source, line=18, encoding='utf-8', path=u'/home/mahiti/DonorSafe/cfeeds/hmanagefeeds.py')
script.completions()
```
...
Cordially
Vinayak K

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

> `Elpy..............: 1.8.0`

Could you try upgrading to 1.9.0 and see if the problem persists?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this was fixed by upgrading. Please do not hesitate to open a new issue if you have further problems!
