### ISSUE TITLE
u'auto_as_view'

### ISSUE THREAD

**Issue by vinayak-kaniyarakkal** [jorgenschaefer/elpy#657]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

u'auto_as_view'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/mahiti/.emacs.d/elpa/elpy-20150502.740/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/__init__.py", line 515, in call_signatures
    stmt = self._get_under_cursor_stmt(call_txt, start_pos)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/__init__.py", line 309, in _get_under_cursor_stmt
    user_stmt = self._parser.user_stmt()
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/usr/local/lib/python2.7/dist-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'auto_as_view'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
'''
Views that uses feeds to and convert them into html.
'''
#  Name of some of views written here starts with 'H' which inticates html.
#  This is to avoid confussion with views written in managefpm.py


from django.views.generic import ListView, CreateView, UpdateView
import requests
from common_methods import auto_as_view
from django.shortcuts import render


class HManageFpmMixin(object):

    template_name = 'cfeeds/list.html'

    def get_queryset(self):
        subDomain = self.request.META['HTTP_HOST'].lower()
        qs = requests.get(
            'http://%s/cfeeds/list-feed/%s/' %
            (subDomain, self.kwargs.get('model'))
        ).json()
        if self.kwargs.get('profile_id'):
            return [i for i in qs
                    if str(i.get('profile')) == self.kwargs.get('profile_id')]
        return qs

    #  HListFpm
    def get_context_data(self, **kwargs):
        context = super(HManageFpmMixin, self).get_context_data(**kwargs)
        context['model'] = self.kwargs.get('model')
        try:
            context['fields'] = self.get_queryset()[0].keys()
        except IndexError:
            context['objects_list'] = None
        return context
#


@auto_as_view
class HListFpm(HManageFpmMixin, ListView):

    pass
#


@auto_as_view
class HAddEditFpmMixin(HManageFpmMixin):

    def get_fields(self):
        subDomain = self.request.META['HTTP_HOST'].lower()
        return requests.get(
            'http://%s/cfeeds/retrive-feed/%s/0' %
            (subDomain, self.kwargs.get('model'))
        ).json()

    def get(self, request, *args, **kwargs):
        return render(self.request, 'cfeeds/add-form.html', {
            'fields': self.get_fields()
        })
#


@auto_as_view
class HAddFpm(HManageFpmMixin):
, CreateView

@auto_as_view
class HEditFpm(UpdateView):
    pass
#


@auto_as_view
class HListProfiledFpm(HListFpm._original):

    def get_queryset(self):
        return [i for i in
                super(HListProfiledFpm._original, self).get_queryset()
                if i.get('profile') == self.kwargs.get('profile_id')]
#
'''

script = jedi.Script(column=21, source=source, line=66, encoding='utf-8', path=u'/home/mahiti/DonorSafe/cfeeds/render_views.py')
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

> `Elpy..............: 1.8.0`

Could you try upgrading to 1.9.0 and see if the problem persists?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this was fixed by upgrading. Please do not hesitate to open a new issue if you have further problems!
