### ISSUE TITLE
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'

### ISSUE THREAD

**Issue by KlasKronander** [jorgenschaefer/elpy#677]
I use elpy and it usually works great with autocomepltions etc. Today I have experienced repeated error messages popping up in a new buffer, and the issue occurs when the cursor is on a line that calls a lambda function. The issue is reproduced in this simple case:

    my_lambda = lambda x: x+1
    my_lambda(1)

Whenever I bring the cursor to the second line I will get an error from elpy. Debugging information pasted below. 

```
Error Message

'Lambda' object has no attribute 'get_subscope_by_name'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/klas/.emacs.d/elpa/elpy-1.9.0/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/klas/.emacs.d/elpa/elpy-1.9.0/elpy/server.py", line 87, in rpc_get_calltip
    get_source(source), offset)
  File "/home/klas/.emacs.d/elpa/elpy-1.9.0/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/klas/.emacs.d/elpa/elpy-1.9.0/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'
```

**Comment by jorgenschaefer** [comment]
Thanks a lot for the bug report and reproduction case!

I reported this upstream as davidhalter/jedi#628
