### ISSUE TITLE
'utf8' codec can't decode byte 0xf8 in position 4142: invalid start byte

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#685]
I ran into this by doing
- `git clone https://github.com/waf-project/waf.git`
- `cd waf`
- `./waf-light configure build`
- then visiting the resulting file `waf`.  That file is about 150 lines of ordinary Python, followed by a ginormous comment that (apparently) contains binary compressed data, which I imagine expands to more Python.
```
Error Message

'utf8' codec can't decode byte 0xf8 in position 4142: invalid start byte

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python3 (/usr/local/bin/python3)
Emacs.............: 25.0.50.2
Elpy..............: 1.9.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.2
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20150830.510/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 87, in rpc_get_calltip
    get_source(source), offset)
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 262, in get_source
    return f.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 302, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 4142: invalid start byte
```

**Comment by jorgenschaefer** [comment]
Interesting, thanks for the report!

Elpy should be more careful about reading there… seems like it should be able to fall back to another encoding. The file itself is marked as iso-8859-1, too.
