### ISSUE TITLE
Elpy/Jedi error (Python 3.5)

### ISSUE THREAD

**Issue by pierre-girbon** [jorgenschaefer/elpy#686]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/bin/python3)
Interactive Python: python3 (/usr/bin/python3)
Emacs.............: 24.5.1
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/pierre/.emacs.d/elpa/elpy-20150830.510/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/pierre/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 87, in rpc_get_calltip
    get_source(source), offset)
  File "/home/pierre/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/pierre/.emacs.d/elpa/elpy-20150830.510/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This is a bug in Jedi, reported as davidhalter/jedi#573, which is sadly not fixed yet :-(

This has also been reported as #627 before here, so I'll close this report to track the problem there.

Please do not hesitate to open new issues if you have any problems, though!
