### ISSUE TITLE
Error while uncommenting a line

### ISSUE THREAD

**Issue by AttilaVM** [jorgenschaefer/elpy#696]
I got the following error while using elpy:

```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.2 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/attila/.emacs.d/elpa/elpy-20150830.510/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/attila/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 87, in rpc_get_calltip
    get_source(source), offset)
  File "/home/attila/.emacs.d/elpa/elpy-20150830.510/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/attila/.emacs.d/elpa/elpy-20150830.510/elpy/jedibackend.py", line 129, in rpc_get_calltip
    "index": call.index,
  File "/usr/lib64/python3.4/site-packages/jedi/api/classes.py", line 653, in index
    if self._index >= len(self.params):
  File "/usr/lib64/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib64/python3.4/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib64/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib64/python3.4/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
```

My dmesg output is seemingly connected to this issue:
```
[ 2192.347351] traps: python3.4[3903] general protection ip:3f27590939 sp:7f84013650e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 2211.606513] traps: python3.4[3914] general protection ip:3f27590939 sp:7f342e03b0e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 2262.067469] kworker/dying (105) used greatest stack depth: 11704 bytes left
[ 2281.337962] traps: python3.4[3956] general protection ip:3f27590939 sp:7f043e70b0e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 4410.661261] traps: python3.4[4633] general protection ip:3f27590939 sp:7fe4185c60e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 4430.397930] traps: python3.4[4639] general protection ip:3f27590939 sp:7ff9c4cc70e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 4460.311387] traps: python3.4[4665] general protection ip:3f27590939 sp:7f9db09730e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 5024.017536] traps: python3.4[4910] general protection ip:3f27590939 sp:7fa4bc0650e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 5049.312703] traps: python3.4[4916] general protection ip:3f27590939 sp:7f07f44230e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 5078.163755] traps: python3.4[4943] general protection ip:3f27590939 sp:7fc000dfb0e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 5099.927424] traps: python3.4[4949] general protection ip:3f27590939 sp:7f21dca840e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 5120.734758] traps: python3.4[4971] general protection ip:3f27590939 sp:7f46d57d40e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
[ 5140.698065] traps: python3.4[4981] general protection ip:3f27590939 sp:7f2f7022a0e0 error:0 in libQtCore.so.4.8.6[3f27400000+2f5000]
```

Update:
Odd enough, but It occurs when I use **Thread** from threading module.

**Comment by AttilaVM** [comment]
I work around the problem with using a virtual environment with 2.7 python version.

**Comment by jorgenschaefer** [comment]
I am sorry I did not respond to this earlier, it must have slipped by. The commit above should fix this problem, too (or rather, works around it), so this should be solved in the next release.

Thanks for the report, and I hope you enjoy Elpy despite of this! :-)

**Comment by jorgenschaefer** [comment]
As this was fixed with the commit above, I will close this issue. Thanks again for the report!
