### ISSUE TITLE
Flymake errors when opening python file

### ISSUE THREAD

**Issue by gregnewman** [jorgenschaefer/elpy#703]
Elpy has been working great for me the past week but last night, when opening a new python file, pyflakes started throwing errors.

Image of error prompt: http://cl.ly/dgsz

I turned up the error reporting for flymakes `(setq flymake-log-level 3)` and opened a python file to trace the issue.

Output from `*messages*`:
```
file /Users/greg/code/voter-import/manage.py, init=elpy-flymake-python-init
flymake is running: nil
file /Users/greg/code/voter-import/manage.py, init=elpy-flymake-python-init [3 times]
create-temp-inplace: file=/Users/greg/code/voter-import/manage.py temp=/Users/greg/code/voter-import/manage_flymake.py
saved buffer manage.py in file /Users/greg/code/voter-import/manage_flymake.py
starting process on dir /
started process 61961, command=(flake8 /Users/greg/code/voter-import/manage_flymake.py), dir=/Users/greg/code/voter-import/
[yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/greg/.emacs.d/elpa/elpy-20150830.510/snippets/python-mode) (quote python-mode)))!
[yas] Loading compiled snippets from /Users/greg/.emacs.d/elpa/elpy-20150830.510/snippets/python-mode
Loading /Users/greg/.emacs.d/elpa/elpy-20150830.510/snippets/python-mode/.yas-setup...done
[yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/greg/.emacs.d/elpa/yasnippet-20151004.1657/snippets/python-mode) (quote python-mode)))!
[yas] Loading compiled snippets from /Users/greg/.emacs.d/elpa/yasnippet-20151004.1657/snippets/python-mode
Loading /Users/greg/.emacs.d/elpa/yasnippet-20151004.1657/snippets/python-mode/.yas-setup...done
[yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /Users/greg/.emacs.d/elpa/yasnippet-20151004.1657/snippets/prog-mode) (quote prog-mode)))!
[yas] Loading compiled snippets from /Users/greg/.emacs.d/elpa/yasnippet-20151004.1657/snippets/prog-mode
Loading /Users/greg/.emacs.d/elpa/yasnippet-20151004.1657/snippets/prog-mode/.yas-setup...done
received 1024 byte(s) of output from process 61961
file /Users/greg/code/voter-import/manage.py, init=elpy-flymake-python-init
parsed 'Traceback (most recent call last):', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/bin/flake8 line=11 text=in <module>
get-real-file-name: file-name=/usr/local/bin/flake8 real-name=/usr/local/bin/flake8
parsed '  File "/usr/local/bin/flake8", line 11, in <module>', got line-err-info
parsed '    sys.exit(main())', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/flake8/main.py line=25 text=in main
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/flake8/main.py real-name=/usr/local/lib/python2.7/site-packages/flake8/main.py
parsed '  File "/usr/local/lib/python2.7/site-packages/flake8/main.py", line 25, in main', got line-err-info
parsed '    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/flake8/engine.py line=228 text=in get_style_guide
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py real-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py
parsed '  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 228, in get_style_guide', got line-err-info
parsed '    kwargs['parser'], options_hooks = get_parser()', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/flake8/engine.py line=70 text=in get_parser
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py real-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py
parsed '  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 70, in get_parser', got line-err-info
parsed '    (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/flake8/engine.py line=54 text=in _register_extensions
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py real-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py
parsed '  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 54, in _register_extensions', got line-err-info
parsed '    checker = _load_entry_point(entry, verify_requirements=False)', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/flake8/engine.py line=33 text=in _load_entry_point
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py real-name=/usr/local/lib/python2.7/site-packages/flake8/engine.py
parsed '  File "/usr/local/lib/python2.7/site-packages/flake8/engine.py", line 33, in _load_entry_point', got line-err-info
parsed '    plugin = entry_point.resolve()', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py line=2361 text=in resolve
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py real-name=/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py
parsed '  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve', got line-err-info
received 483 byte(s) of output from process 61961
file /Users/greg/code/voter-import/manage.py, init=elpy-flymake-python-init
parsed '    module = __import__(self.module_name, fromlist=['__name__'], level=0)', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/flake8/_pyflakes.py line=10 text=in <module>
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/flake8/_pyflakes.py real-name=/usr/local/lib/python2.7/site-packages/flake8/_pyflakes.py
parsed '  File "/usr/local/lib/python2.7/site-packages/flake8/_pyflakes.py", line 10, in <module>', got line-err-info
parsed '    import pyflakes.checker', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/lib/python2.7/site-packages/pyflakes/checker.py line=7 text=in <module>
get-real-file-name: file-name=/usr/local/lib/python2.7/site-packages/pyflakes/checker.py real-name=/usr/local/lib/python2.7/site-packages/pyflakes/checker.py
parsed '  File "/usr/local/lib/python2.7/site-packages/pyflakes/checker.py", line 7, in <module>', got line-err-info
parsed '    import doctest', no line-err-info
parse line: file-idx=2 line-idx=3 file=/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py line=355 text=in <module>
get-real-file-name: file-name=/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py real-name=/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py
parsed '  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 355, in <module>', got line-err-info
parsed '    class _OutputRedirectingPdb(pdb.Pdb):', no line-err-info
parsed 'AttributeError: 'module' object has no attribute 'Pdb'', no line-err-info
file /Users/greg/code/voter-import/manage.py, init=elpy-flymake-python-init
process 61961 exited with code 1
cleaning up using flymake-simple-cleanup
deleted file /Users/greg/code/voter-import/manage_flymake.py
manage.py: 0 error(s), 0 warning(s) in 0.89 second(s)
switched OFF Flymake mode for buffer manage.py due to fatal status CFGERR, warning Configuration error has occurred while running (flake8 /Users/greg/code/voter-import/manage_flymake.py)
```

I went through my configs to see what might have changes yesterday (I did some org customization) and found nothing.

I've uninstalled flake8 and pyflakes and reinstalled them.  Still get the same results.

I tried to find information on the `CFGERR` fatal status but not finding much.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> `parsed '    class _OutputRedirectingPdb(pdb.Pdb):', no line-err-info`
> `parsed 'AttributeError: 'module' object has no attribute 'Pdb'', no line-err-info`

This looks very strange. Why would `pdb` not have the `Pdb` class?

> `started process 61961, command=(flake8 /Users/greg/code/voter-import/manage_flymake.py), dir=/Users/greg/code/voter-import/`

Is there maybe a `pdb.py` or `pdb/__init__.py` in `/Users/greg/code/voter-import/`?

**Comment by gregnewman** [comment]
I have no clue why it would not have the Pdb class.

No, there are not pdb.py anywhere.  I even tried opening a py file from a new clean project and get the same results.

Now, pdb brings up something.  Friday I did try to enter the debugger but it failed, probably because of the virtualenv.  I killed the debugger and moved on.  But still, not pdb.py files exist.

**Comment by jorgenschaefer** [comment]
Can you try the following and tell me what it says?

```Python
import pdb
pdb.Pdb
pdb.__file__
```

**Comment by gregnewman** [comment]
From terminal:
```
Python 2.7.10 (default, Oct  3 2015, 19:13:15) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
>>> pdb.Pdb
<class pdb.Pdb at 0x10350c3f8>
>>> pdb.__file__
'/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.pyc'
>>> 
```

From emacs shell:
```
Python 2.7.10 (default, Oct  3 2015, 19:13:15) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>import pdb 
>>> pdb.Pdb
pdb.Pdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pdb' is not defined
```

I do have this in my init which fixed a lot of elpy issues I was having with homebrew python.
```
#+BEGIN_SRC emacs-lisp :tangle yes
   ; Set PYTHONPATH
   (setenv "PYTHONPATH" "/usr/local/lib/python2.7/site-packages/")

   ; I'm using homebrew python so add homebrew path to exec-path
   (add-to-list 'exec-path "/usr/local/bin/")
#+end_src
```

**Comment by jorgenschaefer** [comment]
In the Emacs shell, `import pdb` worked witout error, but then `pdb.Pdb` complains `pdb` is not defined? That can't be right?

**Comment by gregnewman** [comment]
That is correct.

**Comment by jorgenschaefer** [comment]
That's … not possible, I thought :-D What dies `pdb` without anything else in that shell show?

**Comment by gregnewman** [comment]
I also uninstalled pdb and reinstalled, same results:

```
>>> pdb
pdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pdb' is not defined
```

**Comment by jorgenschaefer** [comment]
`import pdb` should bind the variable `pdb` to a value in the current scope. If `pdb` afterwards fails with that error, something is seriously, seriously broken. I do not know how to debug this remotely I'm afraid. :-(

`pdb` is part of Python, by the way. What do you mean with "reinstalled"?

**Comment by gregnewman** [comment]
Pdb was in site-packages, I assume installed by flake8 or something. I never install any packages globally except what was required for elpy. I uninstalled and reinstalled with pip.

**Comment by gregnewman** [comment]
Ok, I uninstalled that mystery pdb from my global site-packages and all is fixed.  Not sure what caused that and sorry for wasting your time @jorgenschaefer.  Emacs shell now imports pdb fine and flymake errors are gone.

```
successfully uninstalled pdb-0.1
```

I would like to know what installed pdb into global site-packages but not sure how and if it's necessary to try and find out at this point.

**Comment by jorgenschaefer** [comment]
[pdb](https://pypi.python.org/pypi/pdb/0.1) from pypi seems to be a password database thingy … very strange package.

And no worries about bringing it up here, glad it is resolved and do not hesitate to open a new issue if you have further problems. Enjoy Elpy. :-)
