### ISSUE TITLE
Attribute int not found

### ISSUE THREAD

**Issue by mxi1** [jorgenschaefer/elpy#710]
```
Error Message

Attribute int not found

Configuration

Virtualenv........: py3_venv (/Users/minjun/py3_venv)
RPC Python........: 3.5.0 (/Users/minjun/py3_venv/bin/python)
Interactive Python: python (/Users/minjun/py3_venv/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/minjun/py3_venv/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/minjun/.emacs.d/elpa/elpy-20150830.510/elpy/ropebackend.py", line 99, in call_rope
    **kwargs)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 100, in get_calltip
    pyobject = pyname.get_object()
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/oi/soi.py", line 64, in infer_assigned_object
    result = _infer_assignment(assignment, pyname.module)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/oi/soi.py", line 117, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/oi/soi.py", line 150, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 234, in _List
    holding = self._get_object_for_node(node.elts[0])
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 275, in _get_object_for_node
    pyname = eval_node(self.scope, stmt)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 187, in _Call
    pyobject=_get_returned(pyfunction))
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 168, in _get_returned
    return pyobject.get_returned_object(args)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 72, in get_returned_object
    return self.returned.get(args)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 44, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/oi/soi.py", line 21, in infer_returned_object
    result = object_info.get_exact_returned(pyfunction, args)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/oi/objectinfo.py", line 90, in get_exact_returned
    path, key, self._args_to_textual(pyobject, args))
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/oi/objectinfo.py", line 96, in _args_to_textual
    arguments = args.get_arguments(parameters)[:len(parameters)]
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/arguments.py", line 20, in get_arguments
    for pyname in self.get_pynames(parameters):
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/arguments.py", line 33, in get_pynames
    result[index] = self._evaluate(arg)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/arguments.py", line 41, in _evaluate
    return rope.base.evaluate.eval_node(self.scope, ast_node)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 195, in _Num
    self.result = self._get_builtin_name(type_name)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/evaluate.py", line 198, in _get_builtin_name
    pytype = rope.base.builtins.builtins[type_name].get_object()
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/Users/minjun/py3_venv/lib/python3.5/site-packages/rope/base/pyobjects.py", line 20, in get_attribute
    'Attribute %s not found' % name)
rope.base.exceptions.AttributeNotFoundError: Attribute int not found

Rope Debug Information

```

Reproduction:

```Python

source = '''
import asyncio
import aiohttp


@asyncio.coroutine
def fetch_page(url, pause=False):
    if pause:
        yield from asyncio.sleep(2)

    response = yield from aiohttp.request('GET', url)
    assert response.status == 200
    content = yield from response.read()
    print('URL: {0}: Content: {1}'.format(url, content))


@asyncio.coroutine
def my_coroutine(future, task_name, seconds_to_sleep=3):
    print('{0} sleeping for: {1} seconds'.format(task_name, seconds_to_sleep))
    yield from asyncio.sleep(seconds_to_sleep)
    print('{0} is finished'.format(task_name))


def got_result(future):
    print(future.result())


loop = asyncio.get_event_loop()
future1 = asyncio.Future()
future2 = asyncio.Future()


tasks = [
    my_coroutine(future1, 'task1', 4),
    my_coroutine(future2, 'task2', 3)]

future1.add_done_callback(got_result)
future2.add_done_callback(got_result)

loop.run_until_complete(asyncio.wait(tasks))
loop.close()
'''

project = rope.base.project.Project(
    "/Users/minjun/Code/lang/python/asyncio/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/Users/minjun/Code/lang/python/asyncio/tutorial0.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 716, resource, maxfixes=5, remove_self=True
)
```

**Comment by ChillarAnand** [comment]
Hi @mxi1 

You are using 

> Elpy..............: 1.9.0

I guess it is fixed it  latest version. 
Can you upgrade to latest version and check?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this problem is fixed already. Especially as Rope errors are just ignored in the next release. If you have further problems, please do not hesitate to open a new issue, and enjoy Elpy!
