### ISSUE TITLE
jedi: StopIteration exception

### ISSUE THREAD

**Issue by flamingbear** [jorgenschaefer/elpy#711]
Sorry for just dropping this in, but your code asked for it.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message



Configuration

Virtualenv........:  (/opt/miniconda/bin/)
RPC Python........: 3.5.0 (/opt/miniconda/bin/python)
Interactive Python: python (/opt/miniconda/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/opt/miniconda/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/vagrant/.emacs.d/.cask/24.5.1/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 90, in iter_content
    return f.get_return_types(check_yields=True)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/precedence.py", line 45, in calculate_children
    right = next(iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.emacs.d/.cask/24.5.1/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/iterable.py", line 90, in iter_content
    return f.get_return_types(check_yields=True)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/representation.py", line 624, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/opt/miniconda/lib/python3.5/site-packages/jedi/evaluate/precedence.py", line 45, in calculate_children
    right = next(iterator)
StopIteration

Jedi Debug Information

[N] dbg: Parsed /vagrant/source/seaicedata/tmp.py, with 0 parsers in 2 splits.
[N] dbg: eval_element Node(power, [<Name: dirs@10,14>, Node(trailer, [<Operator: .>, <Name: remove@10,19>])])@(10, 14)
[N] dbg: finder.filter_name "<Name: dirs@10,14>" in (<eFunction of <Function: all_files@5-13>>): '[<Name: dirs@8,14>]'@(10, 14)
[N] dbg: eval_element Node(power, [<Name: os@8,29>, Node(trailer, [<Operator: .>, <Name: walk@8,32>]), Node(trailer, [<Operator: (>, <Name: base@8,37>, <Operator: )>])])@(8, 29)
[N]  dbg: finder.filter_name "<Name: os@8,29>" in (<eFunction of <Function: all_files@5-13>>): '[<Name: os@1,7>]'@(8, 29)
[N]  dbg: search_module 'os' in '/vagrant/source/seaicedata/tmp.py'
[N]  dbg: after import: [<ModuleWrapper: <fast.FastModule: os@1-1029>>]
[N]  dbg: finder._names_to_types: [<Name: os@1,7>] -> [<ModuleWrapper: <fast.FastModule: os@1-1029>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: walk@8,32>]) in scope <ModuleWrapper: <fast.FastModule: os@1-1029>>
[N]  dbg: finder.filter_name "<Name: walk@8,32>" in (<ModuleWrapper: <fast.FastModule: os@1-1029>>): '[<Name: walk@296,4>]'@None
[N]  dbg: finder._names_to_types: [<FakeName: walk@296,4>] -> [<eFunction of <Function: walk@296-431>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: (>, <Name: base@8,37>, <Operator: )>]) in scope <eFunction of <Function: walk@296-431>>
[N]  dbg: execute: <eFunction of <Function: walk@296-431>> <Arguments: base>
[N]  dbg: execute result: [<Generator of <eFunction of <Function: walk@296-431>>>] in <eFunction of <Function: walk@296-431>>
[N] dbg: eval_element <Name: walk_into@410,15>@(410, 15)
[N]  dbg: eval_element <Name: followlinks@398,15>@(398, 15)
[N]   dbg: finder.filter_name "<Name: followlinks@398,15>" in (<FunctionExecution of <eFunction of <Function: walk@296-431>>>): '[<FakeName: followlinks@296,42>]'@(398, 15)
[N]   dbg: eval_element <Keyword: False>@(296, 54)
[N]   dbg: finder._names_to_types: [<FakeName: followlinks@296,42>] -> [<CompiledObject: False>]
[N]  dbg: eval_element Node(and_test, [Node(not_test, [<Keyword: not>, <Name: topdown@395,15>]), <Keyword: and>, <Name: is_dir@395,27>])@(395, 11)
[N]  dbg: eval_element Node(not_test, [<Keyword: not>, <Name: topdown@395,15>])@(395, 11)
[N]  dbg: eval_element <Name: topdown@395,15>@(395, 15)
[N]   dbg: finder.filter_name "<Name: topdown@395,15>" in (<FunctionExecution of <eFunction of <Function: walk@296-431>>>): '[<FakeName: topdown@296,14>]'@(395, 15)
[N]   dbg: eval_element <Keyword: True>@(296, 22)
[N]   dbg: finder._names_to_types: [<FakeName: topdown@296,14>] -> [<CompiledObject: True>]
[N]  dbg: calculate_children types [<CompiledObject: False>]
[N]  dbg: search_module 'posix' in '/opt/miniconda/lib/python3.5/os.py'
[N]  dbg: after import: [<CompiledObject: <module 'posix' (built-in)>>]
[N]  dbg: search_module 'nt' in '/opt/miniconda/lib/python3.5/os.py'
[W]  warning: /opt/miniconda/lib/python3.5/os.py:71:9: E3 Potential ImportError.
[N]  dbg: after import: []
[N]  dbg: search_module 'ce' in '/opt/miniconda/lib/python3.5/os.py'
[W]  warning: /opt/miniconda/lib/python3.5/os.py:91:9: E3 Potential ImportError.
[N]  dbg: after import: []
[N]  dbg: finder.filter_name "<Name: walk_into@410,15>" in (<FunctionExecution of <eFunction of <Function: walk@296-431>>>): '[]'@(410, 15)
[W]  warning: /opt/miniconda/lib/python3.5/os.py:410:15: E2 NameError: name 'walk_into' is not defined.
[N]  dbg: finder._names_to_types: [] -> []
[N] dbg: eval_element Node(yield_arg, [<Keyword: from>, Node(power, [<Name: walk@411,27>, Node(trailer, [<Operator: (>, Node(arglist, [Node(power, [<Name: entry@411,32>, Node(trailer, [<Operator: .>, <Name: path@411,38>])]), <Operator: ,>, <Name: topdown@411,44>, <Operator: ,>, <Name: onerror@411,53>, <Operator: ,>, <Name: followlinks@411,62>]), <Operator: )>])])])@(411, 22)
[N] dbg: eval_element <Keyword: from>@(411, 22)

```

Reproduction:

``` Python
import jedi

source = '''\
import os
import fnmatch


def all_files():
    base = '/projects/DATASETS/nsidc0051_gsfc_nasateam_seaice/final-gsfc/'
    filelist = []
    for root, dirs, files in os.walk(base):
        # if 'monthly' in dirs:
        #     dirs.remove('monthly')
        filelist.extend([os.path.join(root, f) for f in fnmatch.filter(files, '*.bin')])
    return sorted(filelist)
'''

script = jedi.Script(encoding='utf-8', line=10, column=31, path='/vagrant/source/seaicedata/tmp.py', source=source)
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! No need to apologize, these reports are useful :-)

This seems to be a problem in Jedi with Python 3.5 only.

The reproduction steps generated by Elpy also reproduce the problem in Python 3.5, so I have reported this upstream. Thanks again!

**Comment by flamingbear** [comment]
Alright then.  I'll file another soon for a different case.  Cheers,

**Comment by jorgenschaefer** [comment]
Seems to happen in 3.4 as well, see #874 for example.

**Comment by gopar** [comment]
Jedi issue, not elpy
