### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tmfe61** [jorgenschaefer/elpy#712]
```
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/local/bin/python3)
Interactive Python: python3 (/usr/local/bin/python3)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/thomas/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 51, in pyname_at
    pymodule = self.get_pymodule()
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 27, in get_pymodule
    self.resource.read() == code:
  File "/usr/local/lib/python3.5/site-packages/rope/base/resources.py", line 111, in read
    return fscommands.file_data_to_unicode(data)
  File "/usr/local/lib/python3.5/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/usr/local/lib/python3.5/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/usr/local/lib/python3.5/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/usr/local/lib/python3.5/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

Rope Debug Information

```'''

project = rope.base.project.Project(
    "/Users/thomas/projekte/WinderPython/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/Users/thomas/projekte/WinderPython/Tambourberechnungen.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 2652, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you very much for the report!

This is a bug in Rope, which is sadly unlikely to get fixed with the Rope library mostly unmaintained. If this is a recurring problem, try using the Jedi backend instead.

**Comment by jorgenschaefer** [comment]
The next release of Elpy will ignore all Rope errors, so I will close this issue. Please do not hesitate to open a new one if you encounter further problems, and enjoy Elpy!
