### ISSUE TITLE
auto-generated bug report

### ISSUE THREAD

**Issue by nih0** [jorgenschaefer/elpy#715]
```
Error Message

Attribute int not found

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/local/bin/python3)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/silbergrau/.emacs.d/elpa/elpy-1.10.0/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/silbergrau/.emacs.d/elpa/elpy-1.10.0/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/home/silbergrau/.emacs.d/elpa/elpy-1.10.0/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/silbergrau/.emacs.d/elpa/elpy-1.10.0/elpy/ropebackend.py", line 155, in rpc_get_completions
    for proposal in proposals]
  File "/home/silbergrau/.emacs.d/elpa/elpy-1.10.0/elpy/ropebackend.py", line 155, in <listcomp>
    for proposal in proposals]
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 254, in type
    pyobject = pyname.get_object()
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/rope/base/pynames.py", line 159, in get_object
    return self._get_imported_pyname().get_object()
  File "/usr/local/lib/python3.5/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/rope/base/oi/soi.py", line 64, in infer_assigned_object
    result = _infer_assignment(assignment, pyname.module)
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/rope/base/oi/soi.py", line 117, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/usr/local/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/site-packages/rope/base/oi/soi.py", line 150, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/local/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 195, in _Num
    self.result = self._get_builtin_name(type_name)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 198, in _get_builtin_name
    pytype = rope.base.builtins.builtins[type_name].get_object()
  File "/usr/local/lib/python3.5/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/local/lib/python3.5/site-packages/rope/base/pyobjects.py", line 20, in get_attribute
    'Attribute %s not found' % name)
rope.base.exceptions.AttributeNotFoundError: Attribute int not found
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! I see @ChillarAnand did an excellent job and already provided a pull request for this, thank you! :-)

As a note, though, you are using Rope 10.3, which does not really work with Python 3 – you probably should be using the `rope_py3k` package. Or, more likely, simply drop rope and stick with Jedi. Rope's current maintainer does not see a use for Rope for the purposes that Elpy uses it for (besides refactoring), so sticking to Jedi seems a safer bet. :-/
