### ISSUE TITLE
"waf" with ginormous binary comment: 'latin-1' codec can't encode character u'\u0186' in position 4152: ordinal not in range(256)

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#718]
Reproducing this will be a bit involved, since I can't seem to include the complete error message in this bug report (probably because it's so big, or filled with nonprintable characters).  But the steps are pretty straightforward:

    $ git clone https://gitlab.com/NTPsec/ntpsec.git
    $ git reset --hard 517fa69b41c3f022a402ee3f1b9ba08f87c7a381
    $ cd ntpsec

    Visit the "waf" file.  Scroll down a few pages.

```
Error Message

'latin-1' codec can't encode character u'\u0186' in position 4152: ordinal not in range(256)

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python3 (/usr/local/bin/python3)
Emacs.............: 25.0.50.1
Elpy..............: 1.10.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.2 (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: Not found (flake8)

Traceback

Traceback (most recent call last):
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/contrib/codeassist.py", line 92, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/contrib/fixsyntax.py", line 46, in pyname_at
    pymodule = self.get_pymodule()
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/base/utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/contrib/fixsyntax.py", line 28, in get_pymodule
    code, resource=self.resource, force_errors=True)
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/base/pycore.py", line 114, in get_string_module
    return PyModule(self, code, resource, force_errors=force_errors)
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/base/pyobjectsdef.py", line 155, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/base/pyobjectsdef.py", line 179, in _init_source
    source_bytes = fscommands.unicode_to_file_data(source_code)
  File "/Users/erichanchrow/Library/Python/2.7/lib/python/site-packages/rope-0.10.2-py2.7.egg/rope/base/fscommands.py", line 196, in unicode_to_file_data
    return contents.encode(encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u0186' in position 4152: ordinal not in range(256)

Rope Debug Information

```

Reproduction:

```Python

source = '''
#!/usr/bin/env python
# encoding: ISO8859-1
# Thomas Nagy, 2005-2015

"""
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

3. The name of the author may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
"""

import os, sys, inspect

VERSION="1.8.12"
REVISION="f00e5b53f6bbeab1384a38c9cc5d51f7"
GIT="1427497785a594dedeaac09013db635791f068c4"
INSTALL=''
C1='#+'
C2='#)'
C3='#%'
cwd = os.getcwd()
join = os.path.join


WAF='waf'
def b(x):
	return x
if sys.hexversion>0x300000f:
	WAF='waf3'
	def b(x):
		return x.encode()

def err(m):
	print(('\033[91mError: %s\033[0m' % m))
	sys.exit(1)

def unpack_wafdir(dir, src):
	f = open(src,'rb')
	c = 'corrupt archive (%d)'
	while 1:
		line = f.readline()
		if not line: err('run waf-light from a folder containing waflib')
		if line == b('#==>\n'):
			txt = f.readline()
			if not txt: err(c % 1)
			if f.readline() != b('#<==\n'): err(c % 2)
			break
	if not txt: err(c % 3)
	txt = txt[1:-1].replace(b(C1), b('\n')).replace(b(C2), b('\r')).replace(b(C3), b('\x00'))

	import shutil, tarfile
	try: shutil.rmtree(dir)
	except OSError: pass
	try:
		for x in ('Tools', 'extras'):
			os.makedirs(join(dir, 'waflib', x))
	except OSError:
		err("Cannot unpack waf lib into %s\nMove waf in a writable directory" % dir)

	os.chdir(dir)
	tmp = 't.bz2'
	t = open(tmp,'wb')
	try: t.write(txt)
	finally: t.close()

	try:
		t = tarfile.open(tmp)
	except:
		try:
			os.system('bunzip2 t.bz2')
			t = tarfile.open('t')
			tmp = 't'
		except:
			os.chdir(cwd)
			try: shutil.rmtree(dir)
			except OSError: pass
			err("Waf cannot be unpacked, check that bzip2 support is present")

	try:
		for x in t: t.extract(x)
	finally:
		t.close()

	for x in ('Tools', 'extras'):
		os.chmod(join('waflib',x), 493)

	if sys.hexversion<0x300000f:
		sys.path = [join(dir, 'waflib')] + sys.path
		import fixpy2
		fixpy2.fixdir(dir)

	os.remove(tmp)
	os.chdir(cwd)

	try: dir = unicode(dir, 'mbcs')
	except: pass
	try:
		from ctypes import windll
		windll.kernel32.SetFileAttributesW(dir, 2)
	except:
		pass

def test(dir):
	try:
		os.stat(join(dir, 'waflib'))
		return os.path.abspath(dir)
	except OSError:
		pass

def find_lib():
	src = os.path.abspath(inspect.getfile(inspect.getmodule(err)))
	base, name = os.path.split(src)

	#devs use $WAFDIR
	w=test(os.environ.get('WAFDIR', ''))
	if w: return w

	#waf-light
	if name.endswith('waf-light'):
		w = test(base)
		if w: return w
		err('waf-light requires waflib -> export WAFDIR=/folder')

	dirname = '%s-%s-%s' % (WAF, VERSION, REVISION)
	for i in (INSTALL,'/usr','/usr/local','/opt'):
		w = test(i + '/lib/' + dirname)
		if w: return w

	#waf-local
	dir = join(base, (sys.platform != 'win32' and '.' or '') + dirname)
	w = test(dir)
	if w: return w

	#unpack
	unpack_wafdir(dir, src)
	return dir

wafdir = find_lib()
sys.path.insert(0, wafdir)

if __name__ == '__main__':

	from waflib import Scripting
	Scripting.waf_entry_point(cwd, VERSION, wafdir)

# Very long mostly-binary comment redacted here

'''

project = rope.base.project.Project(
    "/Users/erichanchrow/git-repositories/3rd-party/ntpsec/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/Users/erichanchrow/git-repositories/3rd-party/ntpsec/waf",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 1459, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! I found the original report, it was #685 – back then, it was an Elpy bug. This is a Rope bug.

I have to admit, considering the low desire by the current Rope maintainers to make Rope work with unknown source files (or even to throw recognizeable error messages), I am tempted to just ignore these again …

Again, thanks for the report!

**Comment by jorgenschaefer** [comment]
The next release of Elpy will ignore all errors from Rope, so this should not happen again. Thank you for the report, and do not hesitate to open a new issue if you have further problems. Enjoy Elpy!
