### ISSUE TITLE
'Call' object has no attribute 'starargs'

### ISSUE THREAD

**Issue by flamingbear** [jorgenschaefer/elpy#721]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Call' object has no attribute 'starargs'

Configuration

Virtualenv........:  (/Users/savoie/anaconda/envs/py3/)
RPC Python........: 3.5.0 (/Users/savoie/anaconda/envs/py3/bin/python)
Interactive Python: python (/Users/savoie/anaconda/envs/py3/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/savoie/anaconda/envs/py3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20151101.401/elpy/server.py", line 235, in rpc_get_unresolved_symbols
    return self.import_magic.get_unresolved_symbols(source)
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20151101.401/elpy/impmagic.py", line 88, in get_unresolved_symbols
    scope = importmagic.symbols.Scope.from_source(source)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 88, in from_source
    visitor.visit(src)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 183, in visit
    self.generic_visit(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 178, in visit
    method(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 240, in visit_FunctionDef
    self.visit_Lambda(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 259, in visit_Lambda
    self.visit(statement)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 178, in visit
    method(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 292, in visit_Assign
    self.visit(node.value)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 178, in visit
    method(node)
  File "/Users/savoie/anaconda/envs/py3/lib/python3.5/site-packages/importmagic/symbols.py", line 374, in visit_Call
    for arg in chain(node.args, node.keywords, filter(None, [node.starargs, node.kwargs])):
AttributeError: 'Call' object has no attribute 'starargs'
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This was a bug in importmagic (reported as alecthomas/importmagic#25) which was fixed on Oct 17. Sadly, the fixed version has not been released yet. If you want to fix this right away, you can install importmagic from source. Otherwise, I'm afraid you will have to wait for a new release from importmagic :-(

**Comment by kootenpv** [comment]
Seconding, it would be great if this would be fixed.
