### ISSUE TITLE
rope: TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by asdyjd** [jorgenschaefer/elpy#726]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in Elpy.
Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

cannot concatenate 'str' and 'NoneType' objects

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (d:/Anaconda2/python.exe)
Interactive Python: ipython (d:/Anaconda2/Scripts/ipython.exe)
Emacs.............: 25.0.50.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8.exe (d:/Anaconda2/Scripts/flake8.exe)

Traceback

Traceback (most recent call last):
  File "d:\emacs\.emacs.d\elpa\elpy-20151101.401\elpy\ropebackend.py", line 100, in call_rope
    **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\rope\contrib\codeassist.py", line 101, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\rope\contrib\codeassist.py", line 569, in get_calltip
    result = self._get_function_signature(pyobject, add_module=True)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python27\site-packages\rope\contrib\codeassist.py", line 619, in _get_function_signature
    return '%s(%s)' % (location + pyfunction.get_name(),
TypeError: cannot concatenate 'str' and 'NoneType' objects

Rope Debug Information

```

Reproduction:

```Python

source = '''
# encoding=utf-8
import scrapy
import mysql.connector
import logging
import sys
import re
reload(sys)
sys.setdefaultencoding('utf-8')


class findclass(scrapy.Spider):
    name = 'find'
    fr = open('find.txt')
    fw = open('findout.txt')
    cnt = mysql.connector.connect(user='root', password='asdzxc', host='127.0.0.1', database='jav', charset='utf8')
    cu = cnt.cursor()
    logging.basicConfig(filename='log.txt', format='%(asctime)s %(levelname)s %(name)s %(message)s',
                        filemode='w', level=logging.DEBUG, datefmt='%Y%m%d %H:%M:%S')

    def start_requests(self):
        for elem in self.fr.newlines():
            self.cu.execute(elem)
            res = self.cu.fetchall()
            for mov in res:
                yield scrapy.Request(url=str(mov[0]), meta={'proxy': 'http:127.0.0.1:1080', 'sourceurl': str(mov[3])}, headers={'User-Agent': "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"})

    def parse(self, response):
        if response.selector.css('.row').extract_first():
            self.fw.write('%s\t%s' % (response.url, response.meta['sourceurl']))

if __name__ == '__main__':
    from twisted.internet import reactor
    from scrapy.crawler import CrawlerRunner
    from scrapy.utils.project import get_project_settings
    runner = CrawlerRunner(get_project_settings())
    d = runner.crawl('find')
    d.addBoth(lambda _: reactor.stop())
    reactor.run()
'''

project = rope.base.project.Project(
    "e:/project/python/scrape/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "e:/project/python/scrape/find/spiders/__init__.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 1070, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report!

This is a bug in Rope. Sadly, the Rope maintainers have made it quite clear that they are not interested in fixing this kind of bug, so I am not holding my breath for this to get fixed. Until Elpy cleans up the Rope dependency, please use the Jedi backend (e.g. by uninstalling Rope entirely), which should cause fewer errors (or at least get them fixed when reported! :-D).

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
