### ISSUE TITLE
Mock decorators failure

### ISSUE THREAD

**Issue by dmwelch** [jorgenschaefer/elpy#727]
```
Error Message

u'mock'

Configuration

Virtualenv........: emacs (/Users/dwelch/virtualenvs/emacs)
RPC Python........: 2.7.10 (/Users/dwelch/virtualenvs/emacs/bin/python)
Interactive Python: python (/Users/dwelch/virtualenvs/emacs/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Syntax checker....: pyflakes (/Users/dwelch/virtualenvs/emacs/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/dwelch/.emacs.d/elpa/elpy-1.8.0/elpy/jedibackend.py", line 303, in run_with_debug
    return getattr(script, name)()
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/pgen2/parse.py", line 170, in addtoken
    value, start_pos, prefix, self.addtoken)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 269, in error_recovery
    self._stack_removal(grammar, stack, index + 1, value, start_pos)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 304, in _stack_removal
    clear_names(children=node[1])
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 294, in clear_names
    clear_names(c.children)
  File "/Users/dwelch/virtualenvs/emacs/lib/python2.7/site-packages/jedi/parser/__init__.py", line 298, in clear_names
    self._scope_names_stack[-1][c.value].remove(c)
KeyError: u'mock'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
from toolchest.utils import path

from unittest import TestCase
import mock


class ensure_pathTestCase(TestCase):

    @mock.patch('path.ensure_path.makedirs')
    @mock.patch('path.ensure_path.isdirs')
    def test_existing_dir(self, mock_isdirs, mock_makedirs):
        
        mock_isdirs.return_value = True
        path.ensure_path('/tmp')
        self
        self.assertFalse(mock_makedirs.is_called, "makedirs() is being called")

    @mock.patch('path.ensure_path.makedirs')
    @mock.patch('path.ensure_path.isdirs')
    def test_nonexisting_dir(self, mock_isdirs, mock_makedirs):
'''

script = jedi.Script(column=12, source=source, line=15, encoding='utf-8', path=u'/Users/dwelch/src/eo_toolbox/toolchest/utils/test/path.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This looks like the same error as #561 – I reported this upstream with Jedi, where it should get fixed at some point. Elpy will not show this error again starting with the next version.

**Comment by dmwelch** [comment]
Thx for looking into it!
