### ISSUE TITLE
Error in populating autocomplete menu.

### ISSUE THREAD

**Issue by areading314** [jorgenschaefer/elpy#729]
```
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: pyflakes (/usr/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/arthur/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 40, in code_assist
    return assist()
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 382, in __call__
    completions = list(self._code_completions().values())
  File "/home/arthur/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 304, in code_completions
    return orig_code_completions(self)
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 462, in _code_completions
    result.update(self._dotted_completions(module_scope, inner_scope))
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 397, in _dotted_completions
    for name, pyname in element.get_attributes().items():
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 196, in get_attributes
    result = dict(self._get_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 191, in _get_concluded_attributes
    self.concluded_attributes.set(self._create_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 135, in _create_concluded_attributes
    result.update(base.get_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 196, in get_attributes
    result = dict(self._get_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 191, in _get_concluded_attributes
    self.concluded_attributes.set(self._create_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 134, in _create_concluded_attributes
    for base in reversed(self.get_superclasses()):
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 126, in get_superclasses
    self._superclasses.set(self._get_bases())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 142, in _get_bases
    base_name)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 156, in _Attribute
    self.result = pyname.get_object()[node.attr]
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 204, in get_attribute
    if name in self._get_concluded_attributes():
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 191, in _get_concluded_attributes
    self.concluded_attributes.set(self._create_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 247, in _create_concluded_attributes
    result.update(init_object.get_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 196, in get_attributes
    result = dict(self._get_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 191, in _get_concluded_attributes
    self.concluded_attributes.set(self._create_concluded_attributes())
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 199, in _create_concluded_attributes
    result.update(star_import.get_names())
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 545, in get_names
    imported = self.imported_module.get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 131, in get_object
    if self._get_pymodule() is None:
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 120, in _get_pymodule
    self.module_name, self._current_folder())
  File "/usr/lib/python3.5/site-packages/rope/base/project.py", line 67, in get_module
    return self.pycore.resource_to_pyobject(module)
  File "/usr/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pycore.py", line 252, in get_pymodule
    force_errors=force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 225, in __init__
    init_dot_py, force_errors=force_errors).get_ast()
  File "/usr/lib/python3.5/site-packages/rope/base/project.py", line 123, in get_pymodule
    return self.pycore.resource_to_pyobject(resource, force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pycore.py", line 255, in get_pymodule
    force_errors=force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 161, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 182, in _init_source
    source_code = fscommands.file_data_to_unicode(source_bytes)
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

Rope Debug Information

```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!
This is the same as #712 and #722 – a bug in Rope. Sadly, the Rope maintainers have been rather explicit about not being interested in Rope catching such errors. If you want, you can just remove Rope and stick with Jedi for completion (don't forget to `M-x elpy-rpc-restart` to restart Elpy without Rope).

Sorry I do not have a better solution for Rope problems right now.

**Comment by areading314** [comment]
Thanks!

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
