### ISSUE TITLE
error on refactor

### ISSUE THREAD

**Issue by nbecker** [jorgenschaefer/elpy#730]
Error Message

'With' object has no attribute 'optional_vars'

Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (/usr/bin/python3)
Interactive Python: ipython (/home/nbecker/.local/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes (/usr/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/nbecker/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/nbecker/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 187, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/nbecker/.emacs.d/elpa/elpy-20151101.401/elpy/refactor.py", line 216, in get_changes
    return method(*args)
  File "/home/nbecker/.emacs.d/elpa/elpy-20151101.401/elpy/refactor.py", line 233, in refactor_organize_imports
    changes = refactor.organize_imports(self.resource)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/__init__.py", line 29, in organize_imports
    self.import_tools.organize_imports, resource, offset)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/__init__.py", line 54, in _perform_command_on_import_tools
    result = method(pymodule, import_filter=import_filter)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/__init__.py", line 189, in organize_imports
    pymodule = self._remove_self_imports(pymodule, import_filter)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/__init__.py", line 198, in _remove_self_imports
    module_imports.get_self_import_fix_and_rename_list()
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/module_imports.py", line 193, in get_self_import_fix_and_rename_list
    import_stmt.accept(visitor)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/importinfo.py", line 56, in accept
    return visitor.dispatch(self)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/actions.py", line 13, in dispatch
    return method(import_, import_.import_info)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/refactor/importutils/actions.py", line 248, in visitFromImport
    result = pymodule[name].get_object()
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 204, in get_attribute
    if name in self._get_concluded_attributes():
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 191, in _get_concluded_attributes
    self.concluded_attributes.set(self._create_concluded_attributes())
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjectsdef.py", line 247, in _create_concluded_attributes
    result.update(init_object.get_attributes())
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 196, in get_attributes
    result = dict(self._get_concluded_attributes())
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 190, in _get_concluded_attributes
    self._get_structural_attributes()
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 184, in _get_structural_attributes
    self.structural_attributes = self._create_structural_attributes()
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjects.py", line 239, in _create_structural_attributes
    ast.walk(child, new_visitor)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/pyobjectsdef.py", line 386, in _With
    if node.optional_vars:
AttributeError: 'With' object has no attribute 'optional_vars'
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!
This is a bug in Rope. Sadly, the Rope maintainers have been rather explicit about not being interested in Rope catching such errors, so there is not much I can do about this. :-(

Sorry I do not have a better solution for Rope problems right now.

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
