### ISSUE TITLE
Jedi Error : Backend encountered unexpected error.

### ISSUE THREAD

**Issue by bibek22** [jorgenschaefer/elpy#739]
```
Error Message

'Node' object has no attribute 'path'

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 217, in completions
    new = classes.Completion(self._evaluator, c, needs_dot, len(like))
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 369, in __init__
    super(Completion, self).__init__(evaluator, name)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 72, in __init__
    self.module_path = self._module.path
AttributeError: 'Node' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 217, in completions
    new = classes.Completion(self._evaluator, c, needs_dot, len(like))
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 369, in __init__
    super(Completion, self).__init__(evaluator, name)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 72, in __init__
    self.module_path = self._module.path
AttributeError: 'Node' object has no attribute 'path'

Jedi Debug Information

[N] dbg: While parsing '/home/bibek/Templates/python/reverseshell/server.py', line 7 slowed down the fast parser.
[N] dbg: Parsed /home/bibek/Templates/python/reverseshell/server.py, with 1 parsers in 2 splits.
[W] warning: No statement under the cursor.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>

```

Reproduction:

``` Python
import jedi

source = '''\
#!/usr/bin/env python

import socket
import sys

# Create socket (allows two computers to connet)

def socket_create():
    try:
        global host
        global port
        global s
        hos'''

script = jedi.Script(encoding='utf-8', line=13, source=source, column=11, path='/home/bibek/Templates/python/reverseshell/server.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This is a bug in Jedi. I have submitted a bug report about this there. :-)

**Comment by bibek22** [comment]
Hit this again this morning. Not sure if this is the same bug.
```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........: None
RPC Python........: 3.5.0 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

Jedi Debug Information

[N] dbg: While parsing '/home/bibek/Templates/python/bucky/downloader.py', line 5 slowed down the fast parser.
[N] dbg: Parsed /home/bibek/Templates/python/bucky/downloader.py, with 1 parsers in 2 splits.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
[N] dbg: eval_element Node(power, [<Name: urllib@6,4>, Node(trailer, [<Operator: .>, <Name: request@6,11>]), Node(trailer, [<Operator: .>, <Name: urlopen@6,19>])])@(6, 4)
[N] dbg: finder.filter_name "<Name: urllib@6,4>" in (<eFunction of <Function: download_stock_data@5-7>>): '[<Name: urllib@2,7>]'@(6, 4)
[N] dbg: search_module 'urllib' in '/home/bibek/Templates/python/bucky/downloader.py'
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: urllib@1-1>>]
[N] dbg: finder._names_to_types: [<Name: urllib@2,7>] -> [<ModuleWrapper: <fast.FastModule: urllib@1-1>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: request@6,11>]) in scope <ModuleWrapper: <fast.FastModule: urllib@1-1>>
[N] dbg: finder.filter_name "<Name: request@6,11>" in (<ModuleWrapper: <fast.FastModule: urllib@1-1>>): '[<FakeName: request@0,0>]'@None
[N] dbg: search_module 'urllib.request' in paths ['/usr/lib/python3.5/urllib']
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: request@1-2630>>]
[N] dbg: finder._names_to_types: [<FakeName: request@0,0>] -> [<ModuleWrapper: <fast.FastModule: request@1-2630>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: urlopen@6,19>]) in scope <ModuleWrapper: <fast.FastModule: request@1-2630>>
[N] dbg: finder.filter_name "<Name: urlopen@6,19>" in (<ModuleWrapper: <fast.FastModule: request@1-2630>>): '[<Name: urlopen@139,4>]'@None
[N] dbg: finder._names_to_types: [<FakeName: urlopen@139,4>] -> [<eFunction of <Function: urlopen@139-164>>]

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/bin/python
import urllib.request

url = ""
def download_stock_data(url):
    response = urllib.request.urlopen(ulr)'''

script = jedi.Script(encoding='utf-8', path='/home/bibek/Templates/python/bucky/downloader.py', source=source, line=6, column=41)
script.completions()
```

**Comment by jorgenschaefer** [comment]
Not the same bug, I am afraid, but a similar one - Python 3.5.0 changed some internal structures in the ast module and Jedi 0.9.0 is not fully compatible yet, so you might come across more of those bugs. :-(

**Comment by aaron-trout** [comment]
Another similar thing:

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........: advpy (/Users/aaron/.envs/advpy)
RPC Python........: 3.5.1 (/Users/aaron/.envs/advpy/bin/python)
Interactive Python: python (/Users/aaron/.envs/advpy/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.9.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/aaron/.envs/advpy/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/aaron/.emacs.d/el-get/elpy/elpy/jedibackend.py", line 224, in run_with_debug
    return getattr(script, name)()
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/.emacs.d/el-get/elpy/elpy/jedibackend.py", line 326, in run_with_debug
    return getattr(script, name)()
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/Users/aaron/.envs/advpy/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

Jedi Debug Information

[N] dbg: While parsing '/Users/aaron/code/advpy/day1/metaclass_demo.py', line 35 slowed down the fast parser.
[N] dbg: While parsing '/Users/aaron/code/advpy/day1/metaclass_demo.py', line 36 slowed down the fast parser.
[N] dbg: Parsed /Users/aaron/code/advpy/day1/metaclass_demo.py, with 1 parsers in 10 splits.
[W] warning: No statement under the cursor.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
[N] dbg: eval_element <Name: print@28,0>@(28, 0)
[N] dbg: finder.filter_name "<Name: print@28,0>" in (<ModuleWrapper: <fast.FastModule: metaclass_demo@1-45>>): '[<Name: print@1,29>]'@(28, 0)
[N] dbg: search_module 'pprint' in '/Users/aaron/code/advpy/day1/metaclass_demo.py'
[N]  dbg: finder.filter_name "'pprint'" in (<ModuleWrapper: <fast.FastModule: pprint@11-598>>): '[<Name: pprint@47,4>]'@None
[N]  dbg: finder._names_to_types: [<FakeName: pprint@47,4>] -> [<eFunction of <Function: pprint@47-55>>]
[N] dbg: after import: [<eFunction of <Function: pprint@47-55>>]
[N] dbg: finder._names_to_types: [<Name: print@1,29>] -> [<eFunction of <Function: pprint@47-55>>]

```

Reproduction:

```Python
import jedi

source = '''\
from pprint import pprint as print

# Use metaclass for alternate dict creation


def dict_meta(names, bases, mapping):
    del mapping['__qualname__']
    del mapping['__module__']
    return mapping


class Loons(metaclass=dict_meta):
    bugs = 'gray'
    daffy = 'black'
    tweety = 'yellow'

print(Loons)


class Circle:
    '''
    Round thing
    '''


c = Circle()
print(repr(Circle))
print(rep


class DetailedReprMeta(type):
    def __repr__(cls):
        return '[class {!r} at 0x{:08X}]'.format(cls.__name__, id(cls))


class Circle(metaclass=DetailedReprMeta):
    '''
    Round thing
    '''


c = Circle()
print(Circle)
print(c)
'''

script = jedi.Script(source=source, encoding='utf-8', path='/Users/aaron/code/advpy/day1/metaclass_demo.py', column=9, line=28)
script.completions()
```

While messing around with metaclasses during some python training :D
