### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'names_dicts'

### ISSUE THREAD

**Issue by terrycojones** [jorgenschaefer/elpy#744]
This just appeared in an `*Elpy Error*` buffer:

```
Error Message

'NoneType' object has no attribute 'names_dicts'

Configuration

Virtualenv........: lm35 (/Users/terry/.virtualenvs/lm35)
RPC Python........: 3.5.0 (/Users/terry/.virtualenvs/lm35/bin/python)
Interactive Python: ipython (/Users/terry/.virtualenvs/lm35/bin/ipython)
Emacs.............: 25.0.50.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes (/Users/terry/.virtualenvs/lm/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/terry/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/terry/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/Users/terry/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/terry/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/Users/terry/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/Users/terry/.virtualenvs/lm35/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
AttributeError: 'NoneType' object has no attribute 'names_dicts'
```

**Comment by jorgenschaefer** [comment]
Thank you very much for the report! This is a known bug in Jedi which was reported upstream a while ago. I hope it gets fixed there soon. Otherwise, Elpy will go and ignore it.

**Comment by jorgenschaefer** [comment]
This was previously reported as #569 and reported upstream. I'll close this issue so we can track the problem in one place – thanks for opening it in any case, I'd rather get too many than too few reports! Please do not hesitate to open a new issue if you have further problems, and enjoy Elpy.
