### ISSUE TITLE
Rope: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by hellified** [jorgenschaefer/elpy#750]
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/isaac/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/usr/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 66, in pyname_at
    return new_pyname()
  File "/usr/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 64, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 112, in get_primary_and_pyname_at
    return eval_str2(holding_scope, name)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 46, in eval_str2
    return eval_node2(holding_scope, node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/usr/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/usr/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 187, in _Call
    pyobject=_get_returned(pyfunction))
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 168, in _get_returned
    return pyobject.get_returned_object(args)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 72, in get_returned_object
    return self.returned.get(args)
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 44, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/oi/soi.py", line 24, in infer_returned_object
    result = _infer_returned(pyfunction, args)
  File "/usr/lib/python3.5/site-packages/rope/base/oi/soi.py", line 94, in _infer_returned
    resulting_pyname = evaluate.eval_node(scope, returned_node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 161, in _Call
    primary, pyobject = self._get_primary_and_object_for_node(node.func)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 285, in _get_primary_and_object_for_node
    pyobject = pyname.get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 159, in get_object
    return self._get_imported_pyname().get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 150, in _get_imported_pyname
    result = self.imported_module.get_object()[self.imported_name]
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 131, in get_object
    if self._get_pymodule() is None:
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 120, in _get_pymodule
    self.module_name, self._current_folder())
  File "/usr/lib/python3.5/site-packages/rope/base/project.py", line 67, in get_module
    return self.pycore.resource_to_pyobject(module)
  File "/usr/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pycore.py", line 255, in get_pymodule
    force_errors=force_errors)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 161, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 182, in _init_source
    source_code = fscommands.file_data_to_unicode(source_bytes)
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/usr/lib/python3.5/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

Rope Debug Information

```

Reproduction:

```Python

source = '''
from django.http import HttpResponse, HttpResponseRedirect

from django.core.urlresolvers import reverse

from django.shortcuts import get_object_or_404, render

from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(
            reverse('polls:results', args=(question.id,))
        )
'''

project = rope.base.project.Project(
    "/home/isaac/learn/django/mysite/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/home/isaac/learn/django/mysite/polls/views.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 1515, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Rope. Sadly, the current maintainers of Rope are not interested in fixing these problems, so all Elpy can try and do is to ignore everything. I recommend using Jedi instead of Rope (just deinstall Rope).

Sorry for this somewhat annoying solution.

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
