### ISSUE TITLE
Rope: Error? Attribute bool not found?

### ISSUE THREAD

**Issue by IanQS** [jorgenschaefer/elpy#752]
Error Message

Attribute bool not found

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ian/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/ian/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/home/ian/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/ian/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 155, in rpc_get_completions
    for proposal in proposals]
  File "/home/ian/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 155, in <listcomp>
    for proposal in proposals]
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 254, in type
    pyobject = pyname.get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 159, in get_object
    return self._get_imported_pyname().get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 159, in get_object
    return self._get_imported_pyname().get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/oi/soi.py", line 64, in infer_assigned_object
    result = _infer_assignment(assignment, pyname.module)
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/oi/soi.py", line 117, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/usr/lib/python3.5/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/usr/lib/python3.5/site-packages/rope/base/oi/soi.py", line 150, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 220, in _Compare
    self.result = self._get_builtin_name('bool')
  File "/usr/lib/python3.5/site-packages/rope/base/evaluate.py", line 198, in _get_builtin_name
    pytype = rope.base.builtins.builtins[type_name].get_object()
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/lib/python3.5/site-packages/rope/base/pyobjects.py", line 20, in get_attribute
    'Attribute %s not found' % name)
rope.base.exceptions.AttributeNotFoundError: Attribute bool not found
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! I'm afraid this is a bug in Rope. The current maintainers of Rope are not interested in fixing these problems. Elpy will ignore Rope errors in the future, and probably drop Rope support completely. For the foreseeable future, I recommend just using Jedi instead (simply deinstall rope).
