### ISSUE TITLE
Rope: Attribute int not found

### ISSUE THREAD

**Issue by maroxe** [jorgenschaefer/elpy#755]
Error Message

Attribute int not found

Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (/Users/maroxe/anaconda/bin/python)
Interactive Python: ipython (/Users/maroxe/anaconda/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.8.1 (0.9.0 available)
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/maroxe/anaconda/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/maroxe/.emacs.d/elpa/elpy-1.10.0/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/maroxe/.emacs.d/elpa/elpy-1.10.0/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/Users/maroxe/.emacs.d/elpa/elpy-1.10.0/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/maroxe/.emacs.d/elpa/elpy-1.10.0/elpy/ropebackend.py", line 155, in rpc_get_completions
    for proposal in proposals]
  File "/Users/maroxe/.emacs.d/elpa/elpy-1.10.0/elpy/ropebackend.py", line 155, in <listcomp>
    for proposal in proposals]
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/contrib/codeassist.py", line 254, in type
    pyobject = pyname.get_object()
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pynames.py", line 159, in get_object
    return self._get_imported_pyname().get_object()
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pynames.py", line 159, in get_object
    return self._get_imported_pyname().get_object()
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pynames.py", line 188, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/oi/soi.py", line 64, in infer_assigned_object
    result = _infer_assignment(assignment, pyname.module)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/oi/soi.py", line 117, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/utils.py", line 40, in newfunc
    return func(*args, **kwds)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/oi/soi.py", line 150, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 227, in _Dict
    values = self._get_object_for_node(node.values[0])
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 275, in _get_object_for_node
    pyname = eval_node(self.scope, stmt)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 26, in eval_node
    return eval_node2(scope, node)[1]
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 195, in _Num
    self.result = self._get_builtin_name(type_name)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/evaluate.py", line 198, in _get_builtin_name
    pytype = rope.base.builtins.builtins[type_name].get_object()
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/Users/maroxe/anaconda/lib/python3.4/site-packages/rope/base/pyobjects.py", line 20, in get_attribute
    'Attribute %s not found' % name)
rope.base.exceptions.AttributeNotFoundError: Attribute int not found
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Rope. Sadly, the current Rope maintainers are not interested in fixing these problems, so Elpy will in the future just ignore these errors and probably drop Rope support entirely. In the meantime, I'd suggest using Jedi instead – just deinstall rope.

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
