### ISSUE TITLE
Rope: Elpy Error: The backend encountered an unexpected error.

### ISSUE THREAD

**Issue by mervinbt** [jorgenschaefer/elpy#758]
Error Message

Can't convert 'NoneType' object to str implicitly

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/pbme002/.emacs.d/elpa/elpy-1.10.0/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 98, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 522, in get_calltip
    result = self._get_function_signature(pyobject, add_module=True)
  File "/usr/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 571, in _get_function_signature
    return '%s(%s)' % (location + pyfunction.get_name(),
TypeError: Can't convert 'NoneType' object to str implicitly

Rope Debug Information

```

Reproduction:

```Python

source = '''
###############################################################################
# Name:   Acroma/aggregator/BisonBase.py
# Author: Brenden T. Mervin
# Date:   Friday October 16 9:54:36 2015
# Brief:  Base classes for BisonBase
# Note:   Copyright (c) 2015 Electric Power Research Institute, Inc.
###############################################################################

import os
import collections
import numpy as np
import pandas as pd
from pint import UnitRegistry

from Archon.utils.fileUtils import get_filepath

__all__ = ["BisonInputBase",
           "BisonGeneratorBase",
           "bisonMap",
           "BisonUnits"]

###############################################################################
# BisonInput
###############################################################################


class BisonInputBase(object):

    def __init__(self, filename):

        # master dictionary containing all data
        self.db = dict()

        # list of tabular data
        self.data = dict()

        # list of tabular data filenames
        self.data_files = dict()

        # get the full path
        self.filepath = os.path.abspath(filename)

        # tags
        self.assembly_tag = "0000"
        self.rod_tag = "C00R00"

        # initialize some variables
        path = []
        current_db = self.db
        current_block = None

        with open(filename) as f:
            for line in f:

                # strip comments and any leading/trailing whitespace
                line = line.split('#')[0]
                line = line.strip()

                # skip blank lines
                if not line:
                    continue

                # entering a subblock
                elif line.startswith("[./"):
                    subblock = line.strip().lstrip("[./").rstrip("]")
                    current_db[subblock] = dict()
                    current_db = current_db[subblock]
                    current_block = subblock
                    path.append(subblock)

                # exiting a block or subblock
                elif line.endswith("[../]") or line.endswith("[]"):
                    path.pop()
                    current_db = self.db
                    for p in path:
                        current_db = current_db[p]

                # entering a new block
                elif line.startswith("["):
                    block = line[1:len(line) - 1]
                    current_db[block] = dict()
                    current_db = current_db[block]
                    current_block = block
                    path.append(block)

                # otherwise this line must contain a parameter
                elif "=" in line:
                    tokens = line.split('=')
                    param = tokens[0].strip()
                    value = tokens[1].strip()
                    if value.isdigit():
                        current_db[param] = int(value)
                    elif param == "data_file":
                        current_db[param] = value
                        # set the filepath
                        filepath = os.path.join(self.dirname, value)
                        self.data[current_block] = (
                            self.read_csv(filepath, path[-1])
                            if os.path.isfile(filepath)
                            else None)
                        self.data_files[current_block] = filepath
                    # TODO: add logic to interpret functions that are not
                    # input using .csv files
                    # elif len(value.split()) > 1:
                    #     value = value[1:-1]
                    #     tokens = value.split()
                    #     vector = [float(token) for token in tokens]
                    else:
                        try:
                            current_db[param] = float(value)
                        except:
                            current_db[param] = value

    ###########################################################################
    # == OPERATORS == #

    def __str__(self):
        raise NotImplementedError("Subclass must implement __str__.")

    ###########################################################################
    # == FUNCTION == #

    def update(self, new_db):
        """Update the input file using a dictionary.
        """
        self.db = self._update_db(self.db, new_db)

    def update_tags(self, assembly_tag, rod_tag):
        """Set the naming convention used for files.
        """
        self.assembly_tag = assembly_tag
        self.rod_tag = rod_tag
        self._update_filenames()

    def update_path(self, path):
        self.filepath = os.path.join(path, self.input_filename)
        self._update_filenames()

    def read_csv(self, filename, block):
        """Read a BISON-formatted .csv file into a DataFrame.
        """

        # build the absolute path to the file
        if not os.path.isfile(filename):
            filename = os.path.join(self.dirname, filename)

        # parse the .csv file accordingly
        if block == "lhgr_history":
            return self.read_piecewise_linear(filename, name="LHGR")
        elif block == "axial_shape_history":
            return self.read_piecewise_bilinear(filename, name="APF")
        else:
            tokens = self._parse_first_line(filename)
            if len(tokens) == 2:
                return self.read_piecewise_linear(filename)
            else:
                return self.read_piecewise_bilinear(filename)

    def read_piecewise_linear(self, filename, name=None):
        """Read a BISON-formatted linear .csv file into a DataFrame
        """

        # build the absolute path to the file
        if not os.path.isfile(filename):
            filename = os.path.join(self.dirname, filename)

        # read the .csv file into a dataframe directly
        df = pd.read_csv(filename, engine='c', comment="#",
                         dtype=np.float64, names=["Time", name])

        # reset the index to start at 1 instead of 0
        df = df.set_index([np.arange(1, df.shape[0] + 1)])
        df.index = df.index.set_names("Step")

        return df

    def read_piecewise_bilinear(self, filename, name=None):
        """Read a BISON-formatted bilinear .csv file into a DataFrame.

        This function assumes the piecewise binear format includes an initial
        row of axial heights followed by a column of 'time', [values]. Note
        that this also requires no comments to be in the header of this .csv
        file.

        Parameters
        ----------
        :param filename: name of the .csv file to read in
        :param name:     name for the data stored in the .csv file

        """

        # build the absolute path to the file
        if not os.path.isfile(filename):
            filename = os.path.join(self.dirname, filename)

        # get the axial heights
        heights = self._parse_first_line(filename)

        # load the data
        data = np.loadtxt(filename, delimiter=",", dtype=np.float64,
                          skiprows=1, comments="#")

        # build the dataframe
        t = []
        f = []
        for row in data:
            t.append(row[0])
            f.extend(row[1:])
        df = pd.DataFrame({name: f},
                          index=pd.MultiIndex.from_product(
                              [t, heights], names=["Time", "Height"]))

        # manipulate the dataframe to get all of the necessary information
        # in there including: step, time, Z, and node information
        df = df.reset_index()
        df = df.set_index(pd.MultiIndex.from_product(
            [np.arange(1, len(t) + 1),
             np.arange(1, len(heights) + 1)],
            names=['Step', 'Node']))

        return df

    def write_power_history(self, path=None):
        """Write the power history to a .csv file.

        TODO: allow input of a filename so that the update_files functions is
        not longer needed.
        """
        self.lhgr_history.to_csv(self.lhgr_history_filepath)

    def write_shape_history(self, path=None):
        """Write the power shape history to a .csv file in BISON format.
        """
        # open the output file
        out = open(self.axial_shape_history_filepath, 'w')

        # get the shape history
        shape_history = self.axial_shape_history

        # write the axial mesh
        heights = shape_history.ix[1]["Height"].values
        for height in heights[:-1]:
            out.write("%6.4e, " % height)
        out.write("%6.4e\n" % heights[-1])

        # write each time step followed by the axial shape
        times = shape_history["Time"].unique()
        for step, time in enumerate(times):
            out.write("%6.4e, " % time * 86400.0)
            shape = shape_history.ix[step + 1]["APF"].values
            for apf in shape[:-1]:
                out.write("%6.4e, " % apf)
            out.write("%6.4e\n" % shape[-1])

        # close the output file
        out.close()

    def to_string(self):
        """Output the master database to a string (~YAML format).
        """
        self.out = ""

        def print_db(db, level):
            level += 1
            for key, value in zip(db.keys(), db.values()):
                self.out += ("%s%s: " % (level * " ", key))
                if type(value) == dict:
                    self.out += "\n"
                    print_db(value, level)
                else:
                    self.out += ("  %s\n" % value)
            level -= 1
        print_db(self.db, 0)
        return self.out

    def to_file(self, filename):
        """Output the data to a BISON input file.

        TODO: consider writing this directly to the current input file
        """
        with open(filename, 'w') as out:
            def print_db(db, level):
                level += 1
                for key, value in zip(db.keys(), db.values()):
                    if type(value) == dict:
                        if level == 0:
                            out.write("[%s]\n" % key)
                        else:
                            out.write("%s[./%s]\n" % ((2 * level) * " ", key))
                        print_db(value, level)
                    else:
                        out.write("{0}{1} = {2}\n".format((2 * level) * " ",
                                                          key, value))
                level -= 1
                if level > 0:
                    out.write("%s[../]\n" % ((2 * level) * " "))
                elif level == 0:
                    out.write("[]\n")

            # identify blocks to preserve order of inputfile
            blocks = ["GlobalParams", "Problem", "Mesh", "Variables",
                      "AuxVariables", "Functions", "SolidMechanics",
                      "Kernels", "Burnup", "AuxKernels", "Contact",
                      "ThermalContact", "BCs", "CoolantChannel", "Materials",
                      "UserObjects", "Executioner", "Postprocessors",
                      "Dampers", "Outputs"]
            for key in self.db.keys():
                assert(key in blocks)

            # function subblocks must also be ordered
            subblocks = ["lhgr_history", "axial_shape_history",
                         "pressure_history", "q"]
            if "Functions" in self.db:
                for key in self.db["Functions"].keys():
                    if key not in subblocks:
                        print("WARNING Bison.py: %s not in subblocks." % key)
                        subblocks.append(key)

            # quasi-ordered printing
            for block in blocks:
                if block in self.db:
                    if block == "Functions":
                        out.write("[Functions]\n")
                        for subblock in subblocks:
                            if subblock in self.db[block]:
                                out.write("  [./%s]\n" % subblock)
                                print_db(
                                    self.db[block][subblock], 1)
                        out.write("[]\n")
                    else:
                        print_db({block: self.db[block]}, -1)

    ###########################################################################
    # == PROPERTIES == #

    @property
    def filename(self):
        return os.path.basename(self.filepath)

    @property
    def dirname(self):
        return os.path.dirname(self.filepath)

    @property
    def input_filename(self):
        return ("input_%s.%s" % (self.rod_tag, str(self)))

    @property
    def input_filepath(self):
        return os.path.join(self.dirname, self.input_filename)

    @property
    def lhgr_history(self):
        return self.data["lhgr_history"]

    @property
    def axial_shape_history(self):
        return self.data["axial_shape_history"]

    @property
    def lhgr_history_filename(self):
        return ("lhgrhistory_%s.csv" % (self.rod_tag))

    @property
    def lhgr_history_filepath(self):
        return os.path.join(self.dirname, self.lhgr_history_filename)

    @property
    def axial_shape_history_filename(self): return "axialshapehistory.csv"

    @property
    def axial_shape_history_filepath(self):
        return os.path.join(self.dirname, self.axial_shape_history_filename)

    @property
    def output_filename(self):
        return ("output_%s.%s" % (
            self.rod_tag, str(self)))

    @property
    def output_filepath(self):
        return os.path.join(self.dirname, self.output_filename)

    ###########################################################################
    # == IMPLEMENTATION == #

    def _parse_first_line(self, filename):
        # first determine the level
        line = ""
        with open(filename) as fid:
            for line in fid:
                # strip spaces and skip comments
                line.strip()
                if line.startswith("#"):
                    continue
                break
        tokens = line.split(",")
        return [np.float64(z) for z in tokens]

    def _build_file(self, base, prefix=None, postfix=None, path=None,
                    ext=".csv"):
        """Construct the paths for writing output .csv files.

        Parameters
        ----------
        :param base: base name of the file
        :param prefix: filename prefix
        :param postfix: filename postfix
        :param path: full path to the directory the file will be written to
        :param ext: file extension
        """
        # construct the output file
        filename = base
        if prefix:
            # note sure if `base` is right
            filename = prefix + "_" + base
        if postfix:
            filename += "_" + postfix
        filename += ext

        # construct the output file path
        filepath = None
        if path:
            filepath = os.path.join(path, filename)
        else:
            filepath = os.path.join(os.getcwd(), filename)

        return filename, filepath

    def _update_filenames(self):
        # first update the file names being stored
        self.data_files["lhgr_history"] = self.lhgr_history_filepath
        self.data_files["axial_shape_history"] = (
            self.axial_shape_history_filepath)

        # then update the file names in the input dictionary
        if "Functions" in self.db:
            if "lhgr_history" in self.db["Functions"]:
                self.db["Functions"]["lhgr_history"]["data_file"] = (
                    self.lhgr_history_filename)
            if "axial_shape_history" in self.db["Functions"]:
                self.db["Functions"]["axial_shape_history"]["data_file"] = (
                    self.axial_shape_history_filename)
        if "Outputs" in self.db:
            self.db["Outputs"]["file_base"] = self.output_filename

    def _update_db(self, orig_db, new_db):
        for key, value in new_db.items():
            if isinstance(value, collections.Mapping):
                result = self._update_db(orig_db.get(key, {}), value)
                orig_db[key] = result
            else:
                orig_db[key] = new_db[key]
        return orig_db


###############################################################################
# BisonGeneratorBase
###############################################################################


class BisonGeneratorBase(object):
    """Writer object which writes BISON input files using a database.
    """
    # database
    db = None
    # current path
    path = None
    # valid keys for the current levels
    valid_keys = None
    # running version of the map at the current depth
    submap = None
    # template file
    template = None
    # output stream
    ofstream = None

    def __init__(self, template=None):
        """Initialize the writer.
        Parameters
        ----------
        :param input_data: input data object
        :param assembly: assembly database object
        :param template: filename of template input file
        """
        self._ureg = BisonUnits()
        self._map = bisonMap()
        if template is None:
            template = get_filepath("../templates/input.%s" % str(self))
        self._template = template

    ###########################################################################
    # == INTERFACE == #

    def create_input(self, filename):
        """Create an input file.
        """
        raise NotImplementedError("Subclass must implement 'create_input'.")

    def write(self, assembly, tag, path):
        """Process the history data and print out the necessary data files to
        supplement the Bison input file.

        TODO: AVG_LIN_HEAT_RATE needs to be a user input
        TODO: need to make sure (i, j) index order matches across all modules

        Parameters
        ----------
        :params cycles: cycle number(s) to process data for
        :params assemblies: tag(s) of the assemblies to process data for
        :params rods: tag(s) of the rod(s) to process data for
        """

        # set path if necessary
        path = os.path.join(path, tag)
        if not os.path.exists(path):
            os.mkdir(path)

        # file name for the LHGR axial shape history data
        LHGR_axial_shape_filepath = os.path.join(
            path, "axialshapehistory.csv")

        # build the LHGR and shape history files
        lhgr, shape = assembly.reconstruct_pin_powers(5.657285)
        end_time_str = "%6.8e" % lhgr['Time'][-1]

        # write the shape history file since it is the same for all rods in
        # this assembly
        self._write_shape_history(shape, LHGR_axial_shape_filepath)

        # loop over the rods
        for j in range(0, assembly.shape[1]):
            for i in range(0, assembly.shape[0]):
                if assembly.is_fuel_rod_index(i, j):
                    rod_id = "C%sR%s" % (("%i" % i).zfill(2),
                                         ("%i" % j).zfill(2))

                    # build the template map
                    input_params = bisonMap()
                    input_filename = os.path.join(
                        path, ("input_%s.bison" % rod_id))

                    # update the input using the design database
                    input_file = self.create_input(self._template)
                    assembly.design.populate(input_params)
                    input_file.update(input_params)

                    # update the file names in the input file and write
                    # the input file to disk
                    input_file.update_tags(tag, rod_id)
                    input_file.update_path(os.path.dirname(input_filename))
                    input_file.db['Executioner']['end_time'] = end_time_str
                    input_file.to_file(input_filename)

                    # get the LHGR for this rod and write it to file
                    # TODO: surely there is an easier and better way to do
                    # this
                    rod_lhgr = lhgr.loc[tuple([slice(None), i, j]), :]
                    rod_lhgr = rod_lhgr.reset_index().set_index('Time')
                    rod_lhgr['LHGR'].to_csv(input_file.lhgr_history_filepath)

    ###########################################################################
    # == PROPERTIES == #

    @property
    def map(self): return self._map

    @property
    def template(self): return self._template

    ###########################################################################
    # == IMPLEMENTATION == #

    def _write_shape_history(self, data, filename):
        """Write the shape history data to a BISON-formatted .csv file.
        """
        out = open(filename, 'w')

        # write the axial heights
        heights = data['Height'].unique()
        for height in heights[0:-1]:
            out.write("%6.4e, " % height)
        out.write("%6.4e\n" % heights[-1])

        # write each time step followed by the axial shape
        times = data['Time'].unique()
        for time in times:
            # get the shape for this time step and write it
            shape = data.query('Time == %s' % str(time))['LHGR_axial_shape']
            # write the data if it exists
            if len(shape.values):
                # write the time
                out.write("%6.4e, " % time)
                for apf in shape[:-1]:
                    out.write("%6.4e, " % apf)
                out.write("%6.4e\n" % shape[-1])
        out.close()


###############################################################################
# bisonMap
###############################################################################


"""Mapping between BISON input parameters and the
Acroma.reactor.Design.AssemblyDesign database structure.
"""


def bisonMap():
    return {
        'GlobalParams': {
            'density': 'fuel/density',
            'a_lower': '',
            'a_upper': 'rod/fuel_length'
        },
        'Mesh': {
            'pellet_outer_radius': 'rod/fuel_outer_radius',
            'pellet_height':       'rod/fuel_length',
            'clad_gap_width':      'rod/gap_thickness',
            'clad_bot_gap_height': 'rod/lower_plenum_length',
            'clad_thickness':      '',
            'top_bot_clad_height': '',
            'plenum_fuel_ratio':   '',
            'elem_type':           '',
        },
        'Variables': {
            'temp': {
                'initial_condition': ''
            }
        },
        'AuxVariables': {
            'porosity': {
                'initial_condition': 'fuel/porosity'
            },
            'grain_radius': {
                'initial_condition': 'fuel/grain_size'
            }
        },
        'Functions': {
            'lhgr_history': {
                'data_file': ''
            },
            'axial_shape_history': {
                'data_file': ''
            },
            'pressure_ramp': {
                'data_file': ''
            }
        },
        'Burnup': {
            'burnup': {
                'fuel_inner_radius': 'rod/fuel_inner_radius',
                'fuel_outer_radius': 'rod/fuel_outer_radius',
                'fuel_volume_ratio': '',
                'i_enrich':          ''
            }
        },
        'AuxKernels': {
            'fast_neutron_flux': {
                'factor': ''
            }
        },
        'ThermalContact': {
            'thermal_contact': {
                'roughness_coef':        '',
                'roughness_fuel':        'fuel/roughness',
                'roughness_clad':        'clad/roughness',
                'initial_gas_fractions': 'gap/composition'
            }
        },
        'BCs': {
            'Pressure': {
                'coolantPressure': {
                    'factor': ''
                }
            },
            'PlenumPressure': {
                'plenumPressure': {
                    'initial_pressure': 'rod/initial_pressure'
                }
            }
        },
        'CoolantChannel': {
            'convective_clad_surface': {
                'inlet_temperature': 'coolant/inlet_temperature',
                'inlet_pressure':    'coolant/inlet_pressure',
                'inlet_massflux':    'coolant/inlet_massflux',
                'rod_diameter':      'rod/clad_outer_diameter',
                'rod_pitch':         'assembly/pitch'
            }
        },
        'Materials': {
            'fuel_mech': {
                'youngs_modulus':     'fuel/youngs_modulus',
                'poissons_ratio':     'fuel/poissons_ratio',
                'thermal_expansion':  'fuel/thermal_expansion_coefficient',
                'grain_radius':       'fuel/grain_size',
                'oxy_to_metal_ratio': 'fuel/oxygen_to_metal_ratio'
            },
            'fuel_relocation': {
                'diameter':               'rod/fuel_outer_diameter',
                'gap':                    'rod/gap_thickness_total',
                'relocation_activation1': '',
                'burnup_relocation_stop': ''
            },
            'clad_solid_mechanics': {
                'youngs_modulus':       'clad/youngs_modulus',
                'poissons_ratio':       'clad/poissons_ratio',
                'thermal_expansion':    'clad_thermal_expansion_coefficient',
                'cold_work_factor':     'clad/cold_work_factor',
                'oxygen_concentration': 'clad/oxygen_concentration'
            },
            'fission_gas_release': {
                'end_densification_burnup': '',
                'initial_grain_radius':     'fuel/grain_size',
                'initial_porosity':         'fuel/porosity',
                'total_densification':      ''
            },
            'clad_density': {
                'density': 'clad/density'
            }
        },
        'UserObjects': {
            'pbz': {
                'pellet_radius': 'rod/fuel_outer_radius'
            }
        },
        'Executioner': {
            'end_time': ''
        }
    }


###############################################################################
# BisonUnits
###############################################################################


class BisonUnits(UnitRegistry):
    """Manage the units necessary for BISON input.
    """

    def to_input_units(self, value, units):
        """Convert the value to the correct units.

        Parameters
        ----------
        :param value: numerical value to be converted
        :param units: string representation of the current units
        """
        try:
            qty = value * self._ureg[units]
            mul = 1.0
            if 'gram' in qty.units:
                mul = 0.001
            return qty.to_base_units().magnitude * mul
        except:
            return value


###############################################################################
# end of Acroma/aggregator/BisonBase.py
###############################################################################
'''

project = rope.base.project.Project(
    "/home/pbme002/src/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/home/pbme002/src/pyacroma/Acroma/aggregator/BisonBase.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 8734, resource, maxfixes=5, remove_self=True
)
```

**Comment by mervinbt** [comment]
To provide a bit more information, the error occured when I changed the following line of code:
```
            out.write("%6.4e, " % time)
```
to
```
            out.write("%6.4e, " % time * 86400.0)
```
in the BisonInputBase.write_shape_history function.

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Rope. Sadly, the current Rope maintainers are not interested in fixing these problems, so all Elpy can do is ignore Rope errors. Elpy will likely drop Rope support entirely in the foreseeable future. For now, I recommend using Jedi instead – just deinstall Rope.

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
