### ISSUE TITLE
Rope: Refactor Function Error

### ISSUE THREAD

**Issue by wxjeacen** [jorgenschaefer/elpy#759]
Configuration

Virtualenv........: venv (/home/shwang/project/venv)
RPC Python........: 2.7.8 (/home/shwang/project/venv/bin/python)
Interactive Python: ipython (/home/shwang/project/venv/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 1.2.1
Yapf..............: 0.6.2
Syntax checker....: flake8 (/home/shwang/project/venv/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/shwang/.emacs.d/el-get/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/shwang/.emacs.d/el-get/elpy/elpy/server.py", line 188, in rpc_refactor
    return ref.get_changes(method, *args)
  File "/home/shwang/.emacs.d/el-get/elpy/elpy/refactor.py", line 216, in get_changes
    return method(*args)
  File "/home/shwang/.emacs.d/el-get/elpy/elpy/refactor.py", line 310, in refactor_use_function
    refactor = UseFunction(self.project, self.resource, offset)
  File "/home/shwang/project/venv/lib/python2.7/site-packages/rope/refactor/usefunction.py", line 21, in __init__
    'Use function works for global functions, only.')
RefactoringError: Use function works for global functions, only.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Elpy should have displayed this a bit more sensibly and just told you the error: "Use function works for global functions, only" – whatever you used that refactoring option on was not a global function, apparently. Does this help?
