### ISSUE TITLE
rope: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by flamingbear** [jorgenschaefer/elpy#760]
vagrant@vsnowyhail:~$ cat elpy.error.txt
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/opt/miniconda/bin/python)
Interactive Python: python (/opt/miniconda/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/opt/miniconda/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/vagrant/.emacs.d/.cask/24.5.1/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 66, in pyname_at
    return new_pyname()
  File "/opt/miniconda/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 64, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 112, in get_primary_and_pyname_at
    return eval_str2(holding_scope, name)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 46, in eval_str2
    return eval_node2(holding_scope, node)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/evaluate.py", line 154, in _Attribute
    if pyname.get_object() != rope.base.pyobjects.get_unknown():
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pynames.py", line 131, in get_object
    if self._get_pymodule() is None:
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pynames.py", line 120, in _get_pymodule
    self.module_name, self._current_folder())
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/project.py", line 67, in get_module
    return self.pycore.resource_to_pyobject(module)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pycore.py", line 252, in get_pymodule
    force_errors=force_errors)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 225, in __init__
    init_dot_py, force_errors=force_errors).get_ast()
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/project.py", line 123, in get_pymodule
    return self.pycore.resource_to_pyobject(resource, force_errors)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pycore.py", line 255, in get_pymodule
    force_errors=force_errors)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 161, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 182, in _init_source
    source_code = fscommands.file_data_to_unicode(source_bytes)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/opt/miniconda/lib/python3.5/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

Rope Debug Information

```

Reproduction:

```Python

source = '''
import click
import datetime as dt
from datetime import date as dt_date
import yaml

import pandas as pd

from . import sedna
from . import nasateam as nt


@click.command()
@click.option('-h', '--hemisphere',
              type=click.Choice(['n', 's']), default='none',
              help='Required. Hemisphere for which to update the data.')
@click.option('-d', '--date',
              type=str,
              default=None,
              help='YYYY-MM-DD. Single date for which to update the data.')
@click.option('-c', '--configfile',
              type=str,
              default='sea_ice_statistics.yaml',
              help='Path to YAML file containing config values.')
@click.option('-s', '--start-date',
              type=str,
              default=None,
              help=('YYYY-MM-DD. Update data for a range of dates, starting here. Must be '
                    'used with --end-date.'))
@click.option('-e', '--end-date',
              type=str,
              default=None,
              help=('YYYY-MM-DD. Update data for a range of dates, ending here. Must be '
                    'used with --start-date.'))
def update_sea_ice_statistics_daily(hemisphere, date, configfile, start_date, end_date):
    """Update the data values in the data store for a given date and/or range of
    dates. If none are specified, the previous five days are used. The
    configfile is a YAML file that overrides the defaults for the following
    options:

    \b
        extent_threshold: the cutoff percentage value for extents (default: 15.0)

    \b
        interpolation_radius: the number of days before and after a date that
            should be used to fill in any missing values (default: 0)

    \b
        search_paths: a list of paths to nasateam sea ice concentration data
            (default:
            ['/projects/DATASETS/nsidc0051_gsfc_nasateam_seaice/final-gsfc',
            '/projects/DATASETS/nsidc0081_nrt_nasateam_seaice'])

    \b
        pole_hole_value: the value found in the data files representing the pole
            hole (default: 251)

    \b
        data_store: name of the file to update/create (default: ./daily.csv)

    """

    dates = _dates_to_process(date, start_date, end_date)

    config = nt.DAILY_STATISTICS_DEFAULT_CONFIG.copy()
    config.update(_load_config(configfile))
    config['hemisphere'] = _get_hemisphere(hemisphere)
    config['grid_areas'] = config['hemisphere']['grid_areas']()

    sedna.update_sea_ice_statistics_daily(
        dates=dates,
        config=config
    )


@click.command()
@click.option('-h', '--hemisphere',
              type=click.Choice(['n', 's']), default='none',
              help='Required. Hemisphere for which to update the data.')
@click.option('-m', '--month',
              type=str,
              default=None,
              help='YYYY-MM. Single month for which to update the data.')
@click.option('-c', '--configfile',
              type=str,
              default='sea_ice_statistics.yaml',
              help='Path to YAML file containing config values.')
@click.option('-s', '--start-month',
              type=str,
              default=None,
              help=('YYYY-MM. Update data for a range of months, starting here. Must be '
                    'used with --end-month.'))
@click.option('-e', '--end-month',
              type=str,
              default=None,
              help=('YYYY-MM. Update data for a range of months, ending here. Must be '
                    'used with --start-month.'))
def update_sea_ice_statistics_monthly(hemisphere, month, configfile, start_month, end_month):
    """Update the data values in the data store for a given month and/or range of
    months. If none is specified, the previous month is used. The configfile
    is a YAML file that overrides the defaults for the following options:

    \b
        extent_threshold: the cutoff percentage value for extents (default: 15.0)

    \b
        search_paths: a list of paths to nasateam sea ice concentration data
            (default:
            ['/projects/DATASETS/nsidc0051_gsfc_nasateam_seaice/final-gsfc',
            '/projects/DATASETS/nsidc0081_nrt_nasateam_seaice'])

    \b
        pole_hole_value: the value found in the data files representing the pole
            hole (default: 251)

    \b
        data_store: name of the file to update/create (default: ./monthly.csv)

    """
    months = _months_to_process(month, start_month, end_month)

    config = nt.MONTHLY_STATISTICS_DEFAULT_CONFIG.copy()
    config.update(_load_config(configfile))
    config['hemisphere'] = _get_hemisphere(hemisphere)
    config['grid_areas'] = config['hemisphere']['grid_areas']()

    sedna.update_sea_ice_statistics_monthly(
        months=months,
        config=config
    )


def _load_config(configfile):
    try:
        with open(configfile) as fp:
            config = yaml.load(fp)
    except FileNotFoundError:
        config = {}

    return config


def _get_hemisphere(hemisphere_id):
    if hemisphere_id == 'n':
        hemi = nt.NORTH
    elif hemisphere_id == 's':
        hemi = nt.SOUTH
    else:
        raise ValueError("Incorrect hemisphere string, must be 'n' or 's'")

    return hemi


def _dates_to_process(date, start_date, end_date):

    dates = set()

    try:
        dates.add(dt.datetime.strptime(date, '%Y-%m-%d').date())
    except TypeError:  # --date not specified; `date` is None instead of str
        pass

    try:
        dates.update([d.date() for d in pd.date_range(start_date, end_date)])
    except ValueError:
        if (start_date is None) and (end_date is None):
            pass  # --start-date and --end-date not specified
        else:
            raise ValueError

    if (len(dates) == 0):
        yesterday = dt_date.today() - dt.timedelta(1)
        five_days_ago = yesterday - dt.timedelta(4)
        dates.update([d.date() for d in pd.date_range(five_days_ago, yesterday)])

    return dates


def _months_to_process(month, start_month, end_month):
    """month, start_month, end_month, are all strings in the format YYYY-MM"""

    months = set()

    try:
        months.add(pd.Period(month, 'M'))
    except TypeError:  # --month not specified
        pass

    try:
        months.update([pd.Period(d, 'M') for d in pd.date_range(start_month, end_month)])
    except ValueError:
        if (start_month is None) and (end_month is None):
            pass  # --start-month and --end-month not specified
        else:
            raise ValueError

    if (len(months) == 0):
        today = dt_date.today()
        yestermonth = pd.Period(today - dt.timedelta(today.day), 'M')
        months.add(yestermonth)

    return months
'''

project = rope.base.project.Project(
    "/vagrant/source/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/vagrant/source/sedna/cli.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 186, resource, maxfixes=5, remove_self=True
)
```
vagrant@vsnowyhail:~$

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Rope. Sadly, the current maintainers of Rope are not interested in fixing such issues, so this won't be fixed upstream in the foreseeable future. Elpy will try and handle it by itself.

**Comment by jorgenschaefer** [comment]
Elpy will ignore all Rope errors in the next release, so this should not be a problem anymore. Please do not hesitate to open a new issue if there are further problems, and enjoy Elpy!
