### ISSUE TITLE
Elpy backend error trying to complete functions in the cryptography module.

### ISSUE THREAD

**Issue by gav451** [jorgenschaefer/elpy#762]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

<String: "cryptography is a package which provides cryptographic recipes">

Configuration

Virtualenv........: None
RPC Python........: 2.7.11 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 25.0.50.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 1.2.1
Yapf..............: Not found (0.6.2 available)
Syntax checker....: pyflakes (/usr/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/gav/.emacs.d/lisp/elpy/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/gav/.emacs.d/lisp/elpy/elpy/server.py", line 95, in rpc_get_completions
    get_source(source), offset)
  File "/home/gav/.emacs.d/lisp/elpy/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/gav/.emacs.d/lisp/elpy/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/usr/lib64/python2.7/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 239, in _eval_atom
    return self.eval_element(c[1])
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/__init__.py", line 247, in _eval_atom
    return [iterable.Array(self, atom)]
  File "/usr/lib64/python2.7/site-packages/jedi/evaluate/iterable.py", line 198, in __init__
    self.type = Array.mapping[atom.children[0]]
KeyError: <String: "cryptography is a package which provides cryptographic recipes">
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Jedi – can you reproduce this behavior, or was it just a one-time thing?

**Comment by gav451** [comment]
It happened trying to complete after putting a dot after "cryptography", but I cannot reproduce it any more.

**Comment by jorgenschaefer** [comment]
Thanks! Reported upstream, might be an easy case of just dealing with the key not being in the mapping :-)
