### ISSUE TITLE
Elpy fail

### ISSUE THREAD

**Issue by DrJackilD** [jorgenschaefer/elpy#765]
Sorry, I don't know, how to figure out it in more details. Elpy got an error, when I'm just work with py module. I didn't find any system in it and can't repeat that error myself. As I see in stacktrace, this error related to rope.

This is error information.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........:  (/home/drjackild/.envs/link_extractor/)
RPC Python........: 3.5.1 (/home/drjackild/.envs/link_extractor/bin/python)
Interactive Python: python (/home/drjackild/.envs/link_extractor/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/home/drjackild/.envs/link_extractor/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/drjackild/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 66, in pyname_at
    return new_pyname()
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 64, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/evaluate.py", line 112, in get_primary_and_pyname_at
    return eval_str2(holding_scope, name)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/evaluate.py", line 46, in eval_str2
    return eval_node2(holding_scope, node)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/evaluate.py", line 154, in _Attribute
    if pyname.get_object() != rope.base.pyobjects.get_unknown():
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pynames.py", line 131, in get_object
    if self._get_pymodule() is None:
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pynames.py", line 120, in _get_pymodule
    self.module_name, self._current_folder())
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/project.py", line 67, in get_module
    return self.pycore.resource_to_pyobject(module)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pycore.py", line 252, in get_pymodule
    force_errors=force_errors)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 225, in __init__
    init_dot_py, force_errors=force_errors).get_ast()
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/project.py", line 123, in get_pymodule
    return self.pycore.resource_to_pyobject(resource, force_errors)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pycore.py", line 255, in get_pymodule
    force_errors=force_errors)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 161, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/pyobjectsdef.py", line 182, in _init_source
    source_code = fscommands.file_data_to_unicode(source_bytes)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/home/drjackild/.envs/link_extractor/lib/python3.5/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

**Comment by DrJackilD** [comment]
Oh, sorry, I didn't noticed, that this error already in issue-tracker. This is repeated issue and can be deleted. Sorry.

**Comment by jorgenschaefer** [comment]
No worries, I'd rather have too many bug reports than too few! Thank you! :-)

Tracked in #760
