### ISSUE TITLE
Jedi: unhashable type: 'dict'

### ISSUE THREAD

**Issue by shelper** [jorgenschaefer/elpy#776]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

unhashable type: 'dict'

Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (c:/python34/python.exe)
Interactive Python: ipython (c:/python34/ipython.exe)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.9.4-1
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes.exe (c:/Python34/Scripts/pyflakes.exe)

Traceback

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\jedi\cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\jedi\cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zyuan\.emacs.d\elpa\elpy-20151101.401\elpy\jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "c:\python34\lib\site-packages\jedi\api\__init__.py", line 515, in call_signatures
    stmt = self._get_under_cursor_stmt(call_txt, start_pos)
  File "c:\python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi\api\__init__.py", line 309, in _get_under_cursor_stmt
    user_stmt = self._parser.user_stmt()
  File "c:\python34\lib\site-packages\jedi\cache.py", line 143, in wrapper
    result = func(self)
  File "c:\python34\lib\site-packages\jedi\parser\user_context.py", line 293, in user_stmt
    module = self.module()
  File "c:\python34\lib\site-packages\jedi\parser\user_context.py", line 339, in module
    return self._parser().module
  File "c:\python34\lib\site-packages\jedi\cache.py", line 143, in wrapper
    result = func(self)
  File "c:\python34\lib\site-packages\jedi\parser\user_context.py", line 281, in _parser
    cache.invalidate_star_import_cache(self._path)
  File "c:\python34\lib\site-packages\jedi\cache.py", line 187, in invalidate_star_import_cache
    parser_cache_item = parser_cache[path]
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\jedi\cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\jedi\cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zyuan\.emacs.d\elpa\elpy-20151101.401\elpy\jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "c:\python34\lib\site-packages\jedi\api\__init__.py", line 515, in call_signatures
    stmt = self._get_under_cursor_stmt(call_txt, start_pos)
  File "c:\python34\lib\site-packages\jedi\evaluate\cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "c:\python34\lib\site-packages\jedi\api\__init__.py", line 309, in _get_under_cursor_stmt
    user_stmt = self._parser.user_stmt()
  File "c:\python34\lib\site-packages\jedi\cache.py", line 143, in wrapper
    result = func(self)
  File "c:\python34\lib\site-packages\jedi\parser\user_context.py", line 293, in user_stmt
    module = self.module()
  File "c:\python34\lib\site-packages\jedi\parser\user_context.py", line 339, in module
    return self._parser().module
  File "c:\python34\lib\site-packages\jedi\cache.py", line 143, in wrapper
    result = func(self)
  File "c:\python34\lib\site-packages\jedi\parser\user_context.py", line 281, in _parser
    cache.invalidate_star_import_cache(self._path)
  File "c:\python34\lib\site-packages\jedi\cache.py", line 187, in invalidate_star_import_cache
    parser_cache_item = parser_cache[path]
TypeError: unhashable type: 'dict'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

``` Python
import jedi

source = '''\
def largestRectangleArea(self, height):
    height.append(0)
    size = len(height)
    no_decrease_stack = [0]
    max_size = height[0]

    i = 0
    while i < size:
        cur_num = height[i]
        if (not no_decrease_stack or
                cur_num > height[no_decrease_stack[-1]]):
            no_decrease_stack.append(i)
            i += 1
        else:
            index = no_decrease_stack.pop()
            if no_decrease_stack:
                width = i - no_decrease_stack[-1] - 1
            else:
                width = i
            max_size = max(max_size, width * height[index])

    return max_size'''

script = jedi.Script(source=source, line=1, path={}, encoding='utf-8', column=25)
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This looks like a bug in Jedi. Sadly, I can't seem to replicate the problem here with the automatically-generated reproduction case. Does this happen regularly? Do you have some kind of code that triggers it reliably?

**Comment by shelper** [comment]
cannot duplicate it either.... i restart my emacs and everything is fine with the same buffer. ...

**Comment by jorgenschaefer** [comment]
Ok. I'll report this upstream anyhow, maybe they know what's going on there – thank you for the report! :-)

**Comment by jorgenschaefer** [comment]
> script = jedi.Script(source=source, line=1, path={}, encoding='utf-8', column=25)

For some reason, `path` was set to `{}`, and also probably the cause of the error – this is very strange. I do not see how Elpy could do such a thing.
