### ISSUE TITLE
The backend encountered an unexpected error

### ISSUE THREAD

**Issue by curuxeira** [jorgenschaefer/elpy#777]
Error Message

<Name: deprecate@244,11>

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.2 (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/usr/lib/python2.7/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/lib/python2.7/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@244,11>

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Was this the full content of the buffer? It seems to be truncated at the end?

**Comment by curuxeira** [comment]
Hi Jorgen,

Thanks for your quick reply. You were right, the KeyError was missing. I'm attaching the whole buffer now:

Elpy Error

The backend encountered an unexpected error. This indicates a bug in Elpy. Please open a bug report
with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

<Name: deprecate@244,11>

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.2 (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/home/ndegara/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/usr/lib/python2.7/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/lib/python2.7/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@244,11>
```

**Comment by jorgenschaefer** [comment]
Thank you! This is the same problem as in #597, which was reported in Jedi in June already … I guess Elpy will have to ignore that error explicitly until it is fixed upstream. :-(

Thanks for the report. I'll close this issue so we can track it in one place only. Please do not hesitate to open new issues if there are other problems!
