### ISSUE TITLE
Automatic Elpy error message (about argparse).

### ISSUE THREAD

**Issue by czotti** [jorgenschaefer/elpy#781]
Hi,
on all my project when I use argparse Elpy always crash and report this kind of error.

````
% uname -a
Linux dinf-moivr2-10b 3.16.0-57-generic #77~14.04.1-Ubuntu SMP Thu Dec 17 23:20:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message



Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 25.1.50.2
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/home/local/USHERBROOKE/zotc2001/.local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/local/USHERBROOKE/zotc2001/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 347, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 449, in _load_module
    cached = cache.load_parser(path)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/cache.py", line 210, in load_parser
    return ParserPickling.load_parser(path, p_time)
  File "/home/local/USHERBROOKE/zotc2001/.local/lib/python2.7/site-packages/jedi/cache.py", line 267, in load_parser
    parser_cache_item = pickle.load(f)
EOFError

Jedi Debug Information

[N] dbg: Parsed /home/local/USHERBROOKE/zotc2001/bin/conv_to_vtk, with 0 parsers in 2 splits.
[N] dbg: eval_element Node(power, [<Name: parser@8,4>, Node(trailer, [<Operator: .>, <Name: add_arguments@8,11>])])@(8, 4)
[N] dbg: finder.filter_name "<Name: parser@8,4>" in (<eFunction of <Function: main@6-11>>): u'[<Name: parser@7,4>]'@(8, 4)
[N]  dbg: eval_statement <ExprStmt:     parser = argparse.ArgumentParser("Tools to convert medical imaging file into VTK mesh.")@7,4> (<Name: parser@7,4>)
[N]  dbg: eval_element Node(power, [<Name: argparse@7,13>, Node(trailer, [<Operator: .>, <Name: ArgumentParser@7,22>]), Node(trailer, [<Operator: (>, <String: "Tools to convert medical imaging file into VTK mesh.">, <Operator: )>])])@(7, 13)
[N]   dbg: finder.filter_name "<Name: argparse@7,13>" in (<eFunction of <Function: main@6-11>>): u'[<Name: argparse@4,7>]'@(7, 4)
[N]   dbg: search_module 'argparse' in u'/home/local/USHERBROOKE/zotc2001/bin/conv_to_vtk'

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/env python2

import os
import argparse

def main():
    parser = argparse.ArgumentParser("Tools to convert medical imaging file into VTK mesh.")
    parser.add_arguments("--in", nargs='+', help="File used as input *arg*", required=True)
    args = parser.parse_args()
    
'''

script = jedi.Script(column=30, source=source, line=8, encoding='utf-8', path=u'/home/local/USHERBROOKE/zotc2001/bin/conv_to_vtk')
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This looks like your Jedi cache has been corrupted – could you delete `~/.cache/jedi/` and see if that fixes it?

**Comment by czotti** [comment]
It's seems to work now (no issue since ~15 min, before it was every minute).

Thanks a lot.

**Comment by jorgenschaefer** [comment]
Glad to hear this! I hope there are no further problems, and enjoy Elpy :-)
