### ISSUE TITLE
'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by nbecker** [jorgenschaefer/elpy#784]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in Elpy.
Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........: None
RPC Python........: 3.4.3 (/usr/bin/python3)
Interactive Python: ipython (/home/nbecker/.local/bin/ipython)
Emacs.............: 25.1.50.2
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: pyflakes (/usr/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/nbecker/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/contrib/codeassist.py", line 40, in code_assist
    return assist()
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/contrib/codeassist.py", line 382, in __call__
    completions = list(self._code_completions().values())
  File "/home/nbecker/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 304, in code_completions
    return orig_code_completions(self)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/contrib/codeassist.py", line 451, in _code_completions
    pymodule = fixer.get_pymodule()
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/contrib/fixsyntax.py", line 27, in get_pymodule
    self.resource.read() == code:
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/resources.py", line 111, in read
    return fscommands.file_data_to_unicode(data)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/home/nbecker/.local/lib/python3.4/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

Rope Debug Information

```

Reproduction:

```Python

source = '''
# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd
import matplotlib as mpl
#mpl.rcParams['font.family'] = 'stix'
mpl.rc('font', family='DejaVu Sans')
mpl.rcParams["mathtext.fontset"] = "stix"
#mpl.rc('font', family='STIXGeneral')

df_random = pd.DataFrame.from_dict ({'λ' : (8,9,10,12), 'ber' : (8.0e-5, 1.0e-4, 1.5e-4, 1.7e-3), 'per' : (6.2e-4, 7.9e-4, .0012, .013)})
df_nonrandom = pd.DataFrame.from_dict ({'λ' : (8,9,10,12), 'ber' : (1.4e-4, 4.2e-4, .001, .015), 'per' : (7.6e-4, 1.4e-3, .0039, .032)})
df_single = pd.DataFrame.fr
#df_random = pd.DataFrame.from_dict ({'λ' : (10,12), 'ber' : (1.6e-4, 1.9e-3), 'per' : (.0012, .014)})
#df_nonrandom = pd.DataFrame.from_dict ({'λ' : (10,12), 'ber' : (.0016, .015), 'per' : (.0042, .032)})
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

from itertools import cycle
from matplotlib.lines import Line2D
m_cycle = cycle(Line2D.filled_markers)

ax.semilogy (df_random['λ'], df_random['ber'], label='burst err(random)', marker=next(m_cycle), linestyle='dotted')
ax.semilogy (df_nonrandom['λ'], df_nonrandom['ber'], label='burst err(non-random)', marker=next(m_cycle), linestyle='dotted')
ax.semilogy (df_random['λ'], df_random['per'], label='packet err(random)', marker=next(m_cycle))
ax.semilogy (df_nonrandom['λ'], df_nonrandom['per'], label='packet err(non-random)', marker=next(m_cycle))
ax.set_xlabel(u'λ')
ax.set_ylabel('prob. error')
ax.legend (loc='best')
# ax.text(0.5, 0.5, 'Draft', horizontalalignment='center', verticalalignment='center', fontsize='x-large', transform=ax.transAxes, bbox=dict(facecolor='red', alpha=0.5))
ax.grid()
plt.title (r'geometric packet length $\mu=8$, $E_s/N_0=U(3\pm 3)\rm{dB}$')
plt.show()
plt.savefig ('plot_linear_per.pdf')



'''

project = rope.base.project.Project(
    "/home/nbecker/scma-unframed.py3/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/home/nbecker/scma-unframed.py3/plot_linear_per.py",
    'file'
)
rope.contrib.codeassist.code_assist(
    project, source, 547, resource, maxfixes=5
)
```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Rope. Sadly, the current maintainers of Rope are pretty explicit in that they do not care about fixing these types of bugs, so there is very little Elpy can do. The next release of Elpy will ignore all errors thrown by Rope, which should fix this problem, too.

In the meantime, you can try and use `rope_py3k` instead of just `rope`, as the base Rope library does not support Python 2.

(Issue previously reported in e.g. #722)

**Comment by nbecker** [comment]
rope_py3k seems to fix at least this problem, thanks!
