### ISSUE TITLE
The backend encountered an unexpected error. This indicates a bug in Elpy.

### ISSUE THREAD

**Issue by ghost** [jorgenschaefer/elpy#791]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Lambda' object has no attribute 'get_subscope_by_name'

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.4.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: Not found (pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/amir/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/home/amir/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/home/amir/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/amir/.local/lib/python2.7/site-packages/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/home/amir/.local/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'

Jedi Debug Information

[N] dbg: Parsed /home/amir/Documents/python/pygame/tst_1.py, with 0 parsers in 1 splits.
[N] dbg: execute: <CompiledObject: <type 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <type 'str'>>(<Arguments: ()>)>] in <CompiledObject: <type 'str'>>
[N] dbg: search_module 'pygame' in u'/home/amir/Documents/python/pygame/tst_1.py'
[N] dbg: search_module 'pygame.locals' in paths ['/usr/lib/python2.7/dist-packages/pygame']
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: locals@23-31>>]
[N] dbg: search_module 'pygame.constants' in paths ['/usr/lib/python2.7/dist-packages/pygame']
[N] dbg: after import: [<CompiledObject: <module 'pygame.constants' from '/usr/lib/python2.7/dist-packages/pygame/constants.so'>>]
[N] dbg: eval_element Node(power, [<Name: pygame@6,0>, Node(trailer, [<Operator: .>, <Name: Surface@6,7>])])@(6, 0)
[N] dbg: finder.filter_name "<Name: pygame@6,0>" in (<ModuleWrapper: <fast.FastModule: tst_1@1-6>>): u'[<Name: pygame@1,7>]'@(6, 0)
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: pygame@20-309>>]
[N] dbg: finder._names_to_types: [<Name: pygame@1,7>] -> [<ModuleWrapper: <fast.FastModule: pygame@20-309>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: Surface@6,7>]) in scope <ModuleWrapper: <fast.FastModule: pygame@20-309>>
[N] dbg: finder.filter_name "<Name: Surface@6,7>" in (<ModuleWrapper: <fast.FastModule: pygame@20-309>>): u'[<Name: Surface@206,29>]'@None
[N]  dbg: eval_statement <ExprStmt: Surface = lambda:Missing_Function@206,29> (<Name: Surface@206,29>)
[N]  dbg: eval_element <Lambda@(206, 39)>@(206, 39)
[N]  dbg: eval_statement result [<eLambdaWrapper of <Lambda@(206, 39)>>]
[N] dbg: finder._names_to_types: [<Name: Surface@206,29>] -> [<eLambdaWrapper of <Lambda@(206, 39)>>]

```

Reproduction:

``` Python
import jedi

source = '''\
import pygame
import sys
import os
from pygame.locals import *

pygame.Surface((100))'''

script = jedi.Script(column=19, source=source, line=6, encoding='utf-8', path=u'/home/amir/Documents/python/pygame/tst_1.py')
script.completions()
```

**Comment by teymuri** [comment]
This happened to me all of the sudden as i was working in elpy. Some debugging would be great...
Cheers

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a bug in Jedi which we reported there in October last year (see #677). It seems to have been fixed, but there has not been a new release of Jedi yet. As soon as a new version of Jedi is released, this should be fixed.

In the meantime, if this happens regularly, you can set `elpy-rpc-error-timeout` to a large value, or, in the next version of Elpy (released later today), set `elpy-disable-backend-error-display` to a true value to disable these errors. Elpy will not be able to show completions anyhow, but at least the error display will be gone.

I hope this helps.
