### ISSUE TITLE
'Call' object has no attribute 'starargs'

### ISSUE THREAD

**Issue by offby1** [jorgenschaefer/elpy#794]
I'd been using OS X emacs with a previous version of elpy, and had just done `M-x package-list-packages RET` followed by `U` to upgrade everything.  I'd intended to pick up the just-released version 1.11.0 of elpy.

That seemed to work OK.  Then I switched to a buffer that already had some python code in it, and typed `C-c C-r i` to see what would happen.

```
Error Message

'Call' object has no attribute 'starargs'

Configuration

Virtualenv........:  (/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/)
RPC Python........: 3.5.1 (/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/bin/python)
Interactive Python: python3 (/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/bin/python3)
Emacs.............: 25.1.50.1
Elpy..............: 1.10.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.9.4-1
Importmagic.......: 0.1.3
Autopep8..........: 0.1.3
Syntax checker....: flake8 (/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 235, in rpc_get_unresolved_symbols
    return self.import_magic.get_unresolved_symbols(source)
  File "/Users/erichanchrow/.emacs.d/elpa/elpy-20151101.401/elpy/impmagic.py", line 88, in get_unresolved_symbols
    scope = importmagic.symbols.Scope.from_source(source)
  File "/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/lib/python3.5/site-packages/importmagic/symbols.py", line 88, in from_source
    visitor.visit(src)
  File "/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/lib/python3.5/site-packages/importmagic/symbols.py", line 183, in visit
    self.generic_visit(node)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ast.py", line 253, in generic_visit
    self.visit(item)
  File "/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/lib/python3.5/site-packages/importmagic/symbols.py", line 178, in visit
    method(node)
  File "/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/lib/python3.5/site-packages/importmagic/symbols.py", line 292, in visit_Assign
    self.visit(node.value)
  File "/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/lib/python3.5/site-packages/importmagic/symbols.py", line 178, in visit
    method(node)
  File "/Users/erichanchrow/git-repositories/me/pyramid-tinyurl-doodle/venv3.Darwin/lib/python3.5/site-packages/importmagic/symbols.py", line 374, in visit_Call
    for arg in chain(node.args, node.keywords, filter(None, [node.starargs, node.kwargs])):
AttributeError: 'Call' object has no attribute 'starargs'
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. This is a bug in importmagic which was fixed a long time ago, but there has not been a new release for some reason. :-( Previously reported as #721, I'll close this report so we can track the bug in one place.
