### ISSUE TITLE
Elpy: backend crashing with Jedi

### ISSUE THREAD

**Issue by mashu** [jorgenschaefer/elpy#797]
Hi,

I use the following simple code

```
import numpy as np

np.
```
After dot I expect company-jedi completion but I get this

```
Error Message

828018

Configuration

Virtualenv........: None
RPC Python........: 2.7.11 (/usr/bin/python)
Interactive Python: ipython (/usr/local/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.2 (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 1.2.1
Yapf..............: Not found (0.6.2 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/mateusz/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/usr/lib/python2.7/dist-packages/jedi/api/__init__.py", line 255, in _simple_complete
    for names_dict in s.names_dicts(search_global=False):
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/representation.py", line 719, in names_dicts
    for star_module in self.star_imports():
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/representation.py", line 735, in star_imports
    new = imports.ImportWrapper(self._evaluator, name).follow()
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/imports.py", line 347, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path)
  File "/usr/lib/python2.7/dist-packages/jedi/evaluate/imports.py", line 449, in _load_module
    cached = cache.load_parser(path)
  File "/usr/lib/python2.7/dist-packages/jedi/cache.py", line 210, in load_parser
    return ParserPickling.load_parser(path, p_time)
  File "/usr/lib/python2.7/dist-packages/jedi/cache.py", line 267, in load_parser
    parser_cache_item = pickle.load(f)
BadPickleGet: 828018

Jedi Debug Information

[N] dbg: Parsed /home/mateusz/test.py, with 0 parsers in 1 splits.
[N] dbg: start: u'np' in <fast.FastModule: test@3-5>
[N] dbg: eval_element <Name: np@5,3>@(5, 3)
[N] dbg: finder.filter_name "<Name: np@5,3>" in (<ModuleWrapper: <fast.FastModule: test@3-5>>): u'[<Name: np@3,16>]'@(5, 3)
[N] dbg: search_module 'numpy' in u'/home/mateusz/test.py'
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: numpy@1-230>>]
[N] dbg: finder._names_to_types: [<Name: np@3,16>] -> [<ModuleWrapper: <fast.FastModule: numpy@1-230>>]
[N] dbg: possible completion scopes: [<ModuleWrapper: <fast.FastModule: numpy@1-230>>]
[N] dbg: search_module 'numpy.core' in paths ['/usr/lib/python2.7/dist-packages/numpy']



Reproduction:

Python
import jedi

source = \
#!/usr/bin/python

import numpy as np

np.

script = jedi.Script(column=3, source=source, line=5, encoding='utf-8', path=u'/home/mateusz/test.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! It looks like your Jedi cache directory got corrupted somehow – can you try to delete `~/.cache/jedi/` and see if that fixes things?

**Comment by mashu** [comment]
Hi Jorgen,

That actually fixed the problem.

Thanks!

**Comment by jorgenschaefer** [comment]
Glad to hear so, and enjoy Elpy! :-)
