### ISSUE TITLE
Elpy error using rope

### ISSUE THREAD

**Issue by henningninneh** [jorgenschaefer/elpy#798]
Error Message

Attribute int not found

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/local/bin/python3)
Interactive Python: /usr/local/bin/python3 (/usr/local/bin/python3)
Emacs.............: 24.4.1
Elpy..............: 1.8.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/henningninneh/.emacs.d/elpa/elpy-1.8.0/elpy/ropebackend.py", line 99, in call_rope
    **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 66, in pyname_at
    return new_pyname()
  File "/usr/local/lib/python3.5/site-packages/rope/contrib/fixsyntax.py", line 64, in new_pyname
    return rope.base.evaluate.eval_location(pymodule, newoffset)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 12, in eval_location
    return eval_location2(pymodule, offset)[1]
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 18, in eval_location2
    return pyname_finder.get_primary_and_pyname_at(offset)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 112, in get_primary_and_pyname_at
    return eval_str2(holding_scope, name)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 46, in eval_str2
    return eval_node2(holding_scope, node)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 31, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/local/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/usr/local/lib/python3.5/site-packages/rope/base/ast.py", line 41, in walk
    walk(child, walker)
  File "/usr/local/lib/python3.5/site-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 195, in _Num
    self.result = self._get_builtin_name(type_name)
  File "/usr/local/lib/python3.5/site-packages/rope/base/evaluate.py", line 198, in _get_builtin_name
    pytype = rope.base.builtins.builtins[type_name].get_object()
  File "/usr/local/lib/python3.5/site-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/local/lib/python3.5/site-packages/rope/base/pyobjects.py", line 20, in get_attribute
    'Attribute %s not found' % name)
rope.base.exceptions.AttributeNotFoundError: Attribute int not found

Rope Debug Information

```

Reproduction:

```Python

source = '''
import random
def getAnswer(answerNumber):
    if answerNumber == 1:
        return 'It is certain'
    elif answerNumber == 2:
        return 'It is decidedly so'
    elif answerNumber == 3:
        return 'Yes'
    elif answerNumber == 4:
        return 'Reply hazy try again'
    elif answerNumber == 5:
        return 'Ask again later'
    elif answerNumber == 6:
        return 'Concentrate and ask again'
    elif answerNumber == 7:
        return 'My reply is no'
    elif answerNumber == 8:
        return 'Outlook not so good'
    elif answerNumber == 9:
        return 'Very doubtful'

r = random.randint(1, 0)'''

project = rope.base.project.Project(
    "/Users/henningninneh/python/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/Users/henningninneh/python/magic8ball.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 618, resource, maxfixes=5, remove_self=True
)

**Comment by emacsway-qarea** [comment]
Rope does not support Python3 currently. Use rope_py3k

**Comment by henningninneh** [comment]
thank you! that does the trick.
