### ISSUE TITLE
cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by mstry** [jorgenschaefer/elpy#805]
Traceback (most recent call last):
  File "/home/peter/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 101, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/usr/local/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 569, in get_calltip
    result = self._get_function_signature(pyobject, add_module=True)
  File "/usr/local/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 619, in _get_function_signat\
ure
    return '%s(%s)' % (location + pyfunction.get_name(),
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by emacsway** [comment]
Hi, @mstry, please, reopen thicket here: https://github.com/sergeyglazyrindev/rope and attach full info from elpy how to reproduce it. Thanks.

**Comment by jorgenschaefer** [comment]
Thanks for the report! In addition to the report to Rope, Elpy probably should handle this more sanely.

**Comment by jorgenschaefer** [comment]
Current versions of Elpy should actually ignore these errors …
