### ISSUE TITLE
error on autocomplete.

### ISSUE THREAD

**Issue by flamingbear** [jorgenschaefer/elpy#807]
May be related to https://github.com/jorgenschaefer/elpy/issues/776 ?
happens when trying to complete a function call.

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

unhashable type: 'dict'

Configuration

Virtualenv........: py3 (/Users/savoie/anaconda/envs/py3)
RPC Python........: 3.5.1 (/Users/savoie/anaconda/envs/py3/bin/python)
Interactive Python: python (/Users/savoie/anaconda/envs/py3/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: 1.2.1
Yapf..............: Not found (0.6.2 available)
Syntax checker....: flake8 (/Users/savoie/anaconda/envs/py3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20160131.118/elpy/server.py", line 107, in rpc_get_completion_docstring
    None, completion)
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/savoie/mhs/emacs-config/.cask/24.5.1/elpa/elpy-20160131.118/elpy/jedibackend.py", line 48, in rpc_get_completion_docstring
    proposal = self.completions.get(completion)
TypeError: unhashable type: 'dict'
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This looks quite weird, the `completion` at that point should never be a dictionary … I'll try to figure out how this might happen.
