### ISSUE TITLE
'in <string>' requires string as left operand, not in

### ISSUE THREAD

**Issue by panditarevolution** [jorgenschaefer/elpy#808]
I just started to use a python3 virtual environment for the first time and got the error in the title when trying to do refactoring on a python file.

To reproduce, use the below configuration, Debian 8.2, an hit `C-c C-r r` to try to get the refactoring menu up.

Not sure if there's some conflict on my side ....

```
Configuration

Virtualenv........: py3 (/home/userdir/Envs/py3)
RPC Python........: 3.4.2 (/home/userdir/Envs/py3/bin/python3)
Interactive Python: ipython (/home/userdir/Envs/py3/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 1.2.1
Yapf..............: 0.6.2
Syntax checker....: flake8 (/home/userdir/Envs/py3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/userdir/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/userdir/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 172, in rpc_get_refactor_options
    return ref.get_refactor_options(start, end)
  File "/home/userdir/.emacs.d/elpa/elpy-20160131.118/elpy/refactor.py", line 137, in get_refactor_options
    is_on_symbol = self._is_on_symbol(start)
  File "/home/userdir/.emacs.d/elpa/elpy-20160131.118/elpy/refactor.py", line 165, in _is_on_symbol
    data = self.resource.read()
  File "/home/userdir/Envs/py3/lib/python3.4/site-packages/rope/base/resources.py", line 111, in read
    return fscommands.file_data_to_unicode(data)
  File "/home/userdir/Envs/py3/lib/python3.4/site-packages/rope/base/fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "/home/userdir/Envs/py3/lib/python3.4/site-packages/rope/base/fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "/home/userdir/Envs/py3/lib/python3.4/site-packages/rope/base/fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "/home/userdir/Envs/py3/lib/python3.4/site-packages/rope/base/fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int
```
```

**Comment by emacsway** [comment]
Use rope_py3k or rope from [devel branch](https://github.com/python-rope/rope/tree/devel)

**Comment by jorgenschaefer** [comment]
Thanks for the report! As @emacsway says, this is a problem in Rope because the current release does not support Python 3 by default. This will change in the next release. Until then, you have to use the `rope_py3k` package instead of the `rope` package. Does this solve the problem? :-)

**Comment by panditarevolution** [comment]
Hi @emacsway  and @jorgenschaefer yes this seems to work well. I pip uninstalled `rope` in my virtualenvironment and installed `rope_py3k` and based on testing it for a few minutes refactoring works again like a charm. Thanks for this :) Is there any real difference between `rope` and `rope_py3k` in terms of intended functionality?

**Comment by jorgenschaefer** [comment]
`rope_py3k` is, right now, an older version of rope, but the main difference are a few bugfixes. There are no real feature differences. The next release of rope will get rid of this artificial distinction, though.

**Comment by panditarevolution** [comment]
Very good! Thanks again.

**Comment by jorgenschaefer** [comment]
You're quite welcome, and enjoy Elpy! :-)

**Comment by panditarevolution** [comment]
Elpy is great! It's one of the main things that made me move to emacs :)
