### ISSUE TITLE
[Errno 13] Permission denied: '/root'

### ISSUE THREAD

**Issue by pxcluster** [jorgenschaefer/elpy#809]
Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.2 (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: Not found (pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/dc/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 96, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/usr/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 509, in get_calltip
    pyobject = pyobject['__call__'].get_object()
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 202, in get_attribute
    if name in self._get_structural_attributes():
  File "/usr/lib/python2.7/dist-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 184, in _get_structural_attributes
    self.structural_attributes = self._create_structural_attributes()
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 232, in _create_structural_attributes
    for name, resource in self._get_child_resources().items():
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 246, in _get_child_resources
    for child in self.resource.get_children():
  File "/usr/lib/python2.7/dist-packages/rope/base/resources.py", line 118, in get_children
    for name in os.listdir(self.real_path):
OSError: [Errno 13] Permission denied: '/root'

Rope Debug Information

```

Reproduction:

```Python

source = '''
#!/usr/bin/python3
### init.py --- 
## 
## Filename     : init.py
## Description  : Initialize all variables used by PxCluster server
## Author       : Daniel Cordey, dc@pxcluster.com
## Maintainer   : Daniel Cordey
## Created      : Mon Jun  8 16:34:14 2015
## Version      : 1.0.0
## Last-Updated : 23/02/2016 00:06:51 (+0100)
##           By : Daniel Cordey, dc@PxClsuster.com
##     Update # : 114
## Keywords     : PxCluster
## Compatibility: Python 3.0 (?)
## 
######################################################################
## 
### Commentary   : 
## 
## 

## 
######################################################################
## 
### Change log:
## 
## 
######################################################################
## 
######################################################################
## 
### Code         :


from __future__ import generators, division, print_function, unicode_literals
from io import open

#from pxcluster import Version

# Test settings
testing_module = __name__ == str('__{}__'.format('main'))

__version__ = b'1.0.0.' #Version('1.0.0')

# Don't want to generate huge lists in memory... use standard range for Python 3.*
range = xrange if isinstance(range(2),
                             list) else range

############################# USER CODE #############################

__all__ = ('dbm', 'now', 'default_sys_id', 'root_dir', 'progname', 'store_pid'
           'current_process')

import os
import os.path
import sys

from root import Root

from db import Dbm
from time import time

# Default DB location
dbm = Dbm()

# Other default values
now = time
root_dir = '/run/pxcluster'


          
############################# TESTING #############################
if testing_module :

    import platform

    from sys import argv, exit
    from os.path import basename
    from argparse import ArgumentParser

    from pxcluster import ptest, pok, perror, test_diff

    progname = basename(argv[0])

    #version = Version(__version__)
    parser = ArgumentParser(description = 'PxCluster Init module',
                            prog = progname)

    parser.add_argument('--version',
                        action = 'version',
                        version = '{} : {}'.format(progname,
                                                   str(__version__)))

    args = parser.parse_args()
    options = vars(args)

    ############################# TEST CODE #############################


######################################################################
### init.py ends here
'''

project = rope.base.project.Project(
    "/home/dc/pxcluster/pxcluster/server/pxcluster_server/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/home/dc/pxcluster/pxcluster/server/pxcluster_server/src/init.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 1486, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This seems to be a bug in Rope, for some reason it is trying to access `/root/` … I do not know how this happens, but will talk with the Rope authors about it.

**Comment by pxcluster** [comment]
Don't hesitate ton contact me if you need to do some test, even bizarre ones :-)
