### ISSUE TITLE
'Operator' object has no attribute 'get_definition'

### ISSUE THREAD

**Issue by rpodgorny** [jorgenschaefer/elpy#810]
```
Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/radek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/radek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

Jedi Debug Information

[N] dbg: Parsed /home/radek/asterix/pycontrol/control_gui.py, with 0 parsers in 36 splits.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
[N] dbg: search_module 'PySide' in '/home/radek/asterix/pycontrol/control_gui.py'
[N] dbg: search_module 'PySide.QtGui' in paths ['/usr/lib/python3.5/site-packages/PySide']
[N] dbg: after import: [<CompiledObject: <module 'PySide.QtGui' from '/usr/lib/python3.5/site-packages/PySide/QtGui.so'>>]
[N] dbg: search_module 'PySide.QtCore' in paths ['/usr/lib/python3.5/site-packages/PySide']
[N] dbg: after import: [<CompiledObject: <module 'PySide.QtCore' from '/usr/lib/python3.5/site-packages/PySide/QtCore.so'>>]
[N] dbg: search_module 'atxutils' in '/home/radek/asterix/pycontrol/control_gui.py'
[W] warning: /home/radek/asterix/pycontrol/control_gui.py:8:5: E3 Potential ImportError.
[N] dbg: after import: []
[N] dbg: eval_element Node(power, [<Name: urllib@30,6>, Node(trailer, [<Operator: .>, <Name: request@30,13>]), Node(trailer, [<Operator: .>, <Name: urlopen@30,21>])])@(30, 6)
[N] dbg: finder.filter_name "<Name: urllib@30,6>" in (<eFunction of <Function: urlopen@29-34>>): '[<Name: urllib@11,7>]'@(30, 6)
[N] dbg: search_module 'urllib' in '/home/radek/asterix/pycontrol/control_gui.py'
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: urllib@1-1>>]
[N] dbg: finder._names_to_types: [<Name: urllib@11,7>] -> [<ModuleWrapper: <fast.FastModule: urllib@1-1>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: request@30,13>]) in scope <ModuleWrapper: <fast.FastModule: urllib@1-1>>
[N] dbg: finder.filter_name "<Name: request@30,13>" in (<ModuleWrapper: <fast.FastModule: urllib@1-1>>): '[<FakeName: request@0,0>]'@None
[N] dbg: search_module 'urllib.request' in paths ['/usr/lib/python3.5/urllib']
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: request@1-2630>>]
[N] dbg: finder._names_to_types: [<FakeName: request@0,0>] -> [<ModuleWrapper: <fast.FastModule: request@1-2630>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: urlopen@30,21>]) in scope <ModuleWrapper: <fast.FastModule: request@1-2630>>
[N] dbg: finder.filter_name "<Name: urlopen@30,21>" in (<ModuleWrapper: <fast.FastModule: request@1-2630>>): '[<Name: urlopen@139,4>]'@None
[N] dbg: finder._names_to_types: [<FakeName: urlopen@139,4>] -> [<eFunction of <Function: urlopen@139-164>>]

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/bin/python3

from version import __version__

from PySide.QtGui import *
from PySide.QtCore import *
from libshwrapper import LibSh
from atxutils import *
import logging
from quitfile import QuitFile
import urllib.request
import json


def set_bg(widget, color):
	#if widget.BackgroundColour != color: widget.BackgroundColour = color
	p = widget.palette()
	if p.color(widget.backgroundRole()) != color:
		p.setColor(widget.backgroundRole(), color)
		widget.setPalette(p)
	widget.setAutoFillBackground(True)


def set_text(widget, label):
	if widget.text() != label:
		widget.setText(label)


def urlopen(url):
	with urllib.request.urlopen(url) as r:
		return json.loads(r.read().decode('utf-8'))


class App(QApplication):
	def __init__(self):
		QApplication.__init__(self)
		self.init_frame()

	def init_frame(self):
		self.frame = Frame(None)
		self.frame.Show()
		self.SetTopWindow(self.frame)


class Frame(QFrame):
	def __init__(self, urlbase):
		super().__init__()
		#QFrame.__init__(self, parent, title='control_gui', size=(200,200), style=wx.DEFAULT_FRAME_STYLE&~wx.MAXIMIZE_BOX|wx.STAY_ON_TOP)

		self.urlbase = urlbase

		self.plant_state = {}

		# TODO: hackish - take from command line?
		self.output_min = 80
		self.output_max = 200

		self.output_step = 5

		# TODO: hackish - take from command line?
		self.truck_capacity_min = 5
		self.truck_capacity_max = 15

		self.mem = LibSh()

		self.setupUi()

		#self.set_cem_buttons()

		self.displaying_message = False

		self.startTimer(100)

	def setupUi(self):
		layout = QVBoxLayout(self)

		self.button_output_minus = QPushButton('-', self)
		self.textctrl = QLineEdit(self)
		self.button_output_plus = QPushButton('+', self)

		layout_output = QHBoxLayout()
		layout_output.addWidget(self.button_output_minus)
		layout_output.addWidget(self.textctrl)
		layout_output.addWidget(self.button_output_plus)

		self.button = QPushButton(self)
		#self.button_mixer_cover = QPushButton(self)

		layout_material = QHBoxLayout()
		self.textctrl_material_level_warning = QLineEdit(self)
		self.textctrl_material_level_error = QLineEdit(self)
		self.button_material_problem = QPushButton('MAT', self)

		layout_material = QHBoxLayout()
		layout_material.addWidget(self.textctrl_material_level_warning)
		layout_material.addWidget(self.textctrl_material_level_error)
		layout_material.addWidget(self.button_material_problem)

		self.button_mixer = []
		#for i in ['A', '0', '-', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']:
		for i in ['A', '0', '1', '2', '3', ]:
			self.button_mixer.append(QPushButton(i, self))

		self.button_mixer_cont = []
		for i in ['A', '0', '\u00bc', '\u00bd', '\u00be', '1', ]:
			self.button_mixer_cont.append(QPushButton(i, self))

		layout_mixer = QHBoxLayout()
		for i in range(len(self.button_mixer)):
			layout_mixer.addWidget(self.button_mixer[i])

		layout_mixer_cont = QHBoxLayout()
		for i in range(len(self.button_mixer_cont)):
			layout_mixer_cont.addWidget(self.button_mixer_cont[i])

		self.button_funnel_a = QPushButton('A', self)
		self.button_funnel_0 = QPushButton('0', self)
		self.button_funnel_1 = QPushButton('1', self)

		layout_funnel = QHBoxLayout()
		layout_funnel.addWidget(self.button_funnel_a)
		layout_funnel.addWidget(self.button_funnel_0)
		layout_funnel.addWidget(self.button_funnel_1)

		self.button_truck_minus = QPushButton('-', self)
		self.textctrl_truck = QLineEdit(self)
		self.button_truck_plus = QPushButton('+', self)

		layout_truck = QHBoxLayout()
		layout_truck.addWidget(self.button_truck_minus)
		layout_truck.addWidget(self.textctrl_truck)
		layout_truck.addWidget(self.button_truck_plus)

		#self.button_conveyer3_left = QPushButton('<<', self)
		#self.button_conveyer3_center = QPushButton(self)
		#self.button_conveyer3_right = QPushButton('>>', self)

		#layout_conveyer3 = QHBoxLayout()
		#layout_conveyer3.addWidget(self.button_conveyer3_left)
		#layout_conveyer3.addWidget(self.button_conveyer3_center)
		#layout_conveyer3.addWidget(self.button_conveyer3_right)

		#self.button_c1 = QPushButton(self)
		#self.button_c2 = QPushButton(self)

		#layout_cem = QHBoxLayout()
		#layout_cem.addWidget(self.button_c1)
		#layout_cem.addWidget(self.button_c2)

		layout.addLayout(layout_output)
		layout.addWidget(self.button)
		layout.addLayout(layout_material)
		#layout.addLayout(layout_cem)
		#layout.addWidget(self.button_mixer_cover)
		layout.addLayout(layout_mixer_cont)
		layout.addLayout(layout_mixer)
		layout.addLayout(layout_funnel)
		layout.addLayout(layout_truck)
		#layout.addLayout(layout_conveyer3)

		layout.setContentsMargins(0, 0, 0, 0)

		self.setLayout(layout)  # TODO: not needed?

		self.textctrl.returnPressed.connect(self.OnEnter)
		self.textctrl_truck.returnPressed.connect(self.OnTruckEnter)
		self.button.clicked.connect(self.OnButton)

		self.button_output_minus.clicked.connect(self.OnButtonOutputMinus)
		self.button_output_plus.clicked.connect(self.OnButtonOutputPlus)

		self.textctrl_material_level_warning.returnPressed.connect(self.OnMaterialLevelWarningEnter)
		self.textctrl_material_level_error.returnPressed.connect(self.OnMaterialLevelErrorEnter)
		self.button_material_problem.clicked.connect(self.OnMaterialProblemButton)

		self.button_truck_minus.clicked.connect(self.OnButtonTruckMinus)
		self.button_truck_plus.clicked.connect(self.OnButtonTruckPlus)

		#self.button_c1.clicked.connect(self.OnButtonC1)
		#self.button_c2.clicked.connect(self.OnButtonC2)
		#self.button_mixer_cover.clicked.connect(self.OnButtonMixerCover)

		for i in range(len(self.button_mixer)):
			self.button_mixer[i].clicked.connect(self.OnButtonMixer)

		for i in range(len(self.button_mixer_cont)):
			self.button_mixer_cont[i].clicked.connect(self.OnButtonMixerCont)

		self.button_funnel_a.clicked.connect(self.OnButtonFunnelA)
		self.button_funnel_0.clicked.connect(self.OnButtonFunnel0)
		self.button_funnel_1.clicked.connect(self.OnButtonFunnel1)

		#self.button_conveyer3_left.clicked.connect(self.OnButtonConveyer3Left)
		#self.button_conveyer3_center.clicked.connect(self.OnButtonConveyer3Center)
		#self.button_conveyer3_right.clicked.connect(self.OnButtonConveyer3Right)

		# TODO: this hard-coded shit is so hackish!
		'''
		self.Fit()
		size = self.ClientSize
		size[0] = 130
		self.ClientSize = size
		'''

		self.setMinimumSize(10, 10)  # TODO: why is this needed?
		self.resize(150, 200)

		# TODO: hard-coded shit!!!
		self.move(5, 275)

	def OnButton(self):
		self.mem['MEMSH_ProductionMode'] = not self.mem['MEMSH_ProductionMode']

	def OnMaterialProblemButton(self):
		self.mem['MEMSH_MaterialProblem'] = 0

	def OnButtonOutputMinus(self):
		output = self.mem['MEMSH_ProductionOutput']
		output -= self.output_step
		output = max(output, self.output_min)
		self.mem['MEMSH_ProductionOutput'] = output

	def OnButtonOutputPlus(self):
		output = self.mem['MEMSH_ProductionOutput']
		output += self.output_step
		output = min(output, self.output_max)
		self.mem['MEMSH_ProductionOutput'] = output

	def OnButtonTruckMinus(self):
		truck_capacity = self.mem['MEMSH_TruckCapacity']
		truck_capacity -= 1
		truck_capacity = max(truck_capacity, self.truck_capacity_min)
		self.mem['MEMSH_TruckCapacity'] = truck_capacity

	def OnButtonTruckPlus(self):
		truck_capacity = self.mem['MEMSH_TruckCapacity']
		truck_capacity += 1
		truck_capacity = min(truck_capacity, self.truck_capacity_max)
		self.mem['MEMSH_TruckCapacity'] = truck_capacity

	def OnButtonC1(self):
		# TODO: hard-coded shit
		self.mem['IORSH_DO_016'] = not self.mem['IORSH_DO_016']

	def OnButtonC2(self):
		# TODO: hard-coded shit
		self.mem['IORSH_DO_017'] = not self.mem['IORSH_DO_017']

	def OnButtonMixerCover(self):
		# TODO: hard-coded shit
		self.mem['IORSH_DO_035'] = not self.mem['IORSH_DO_035']

	def OnButtonMixer(self):
		sender = self.sender()
		for i in range(len(self.button_mixer)):
			if self.button_mixer[i] == sender:
				self.mem['MEMSH_MixerOpenForce'] = i
				break

	def OnButtonMixerCont(self):
		sender = self.sender()
		for i in range(len(self.button_mixer_cont)):
			if self.button_mixer_cont[i] == sender:
				self.mem['MEMSH_MixerContOpenForce'] = i
				break

	def OnButtonFunnelA(self):
		with urllib.request.urlopen('%s/Funnel1/set_open/' % self.urlbase) as r:
			json.loads(r.read().decode('utf-8'))

	def OnButtonFunnel0(self):
		with urllib.request.urlopen('%s/Funnel1/set_open/0' % self.urlbase) as r:
			json.loads(r.read().decode('utf-8'))

	def OnButtonFunnel1(self):
		with urllib.request.urlopen('%s/Funnel1/set_open/1' % self.urlbase) as r:
			json.loads(r.read().decode('utf-8'))

	def OnButtonConveyer3Left(self):
		if self.mem['MEMSH_Conveyer3Force'] == 1:
			self.mem['MEMSH_Conveyer3Force'] = 4
		else:
			self.mem['MEMSH_Conveyer3Force'] = 1

	def OnButtonConveyer3Center(self):
		if self.mem['MEMSH_Conveyer3Force'] == 0:
			self.mem['MEMSH_Conveyer3Force'] = 3
		else:
			self.mem['MEMSH_Conveyer3Force'] = 0

	def OnButtonConveyer3Right(self):
		if self.mem['MEMSH_Conveyer3Force'] == 2:
			self.mem['MEMSH_Conveyer3Force'] = 5
		else:
			self.mem['MEMSH_Conveyer3Force'] = 2

	def OnEnter(self):
		output = int(self.textctrl.Value)
		self.output_min = min(output, self.output_min)
		self.output_max = max(output, self.output_max)
		self.mem['MEMSH_ProductionOutput'] = output
		self.textctrl.setValue(str(output))

	def OnMaterialLevelWarningEnter(self):
		level = int(self.textctrl_material_level_warning.text())
		level = max(0, level)
		level = min(level, 100)
		self.mem['MEMSH_MaterialLevelWarning'] = level
		self.textctrl_material_level_warning.setText(str(level))

	def OnMaterialLevelErrorEnter(self):
		level = int(self.textctrl_material_level_error.text())
		level = max(0, level)
		level = min(level, 100)
		self.mem['MEMSH_MaterialLevelError'] = level
		self.textctrl_material_level_error.setText(str(level))

	def OnTruckEnter(self):
		truck_capacity = int(self.textctrl_truck.text())
		truck_capacity = max(truck_capacity, self.truck_capacity_min)
		truck_capacity = min(truck_capacity, self.truck_capacity_max)
		self.mem['MEMSH_TruckCapacity'] = truck_capacity
		self.textctrl_truck.setText(str(truck_capacity))

	def timerEvent(self, e):
		if not self.textctrl.hasFocus() \
		and self.textctrl.text() != str(int(self.mem['MEMSH_ProductionOutput'])):
			self.textctrl.setText(str(int(self.mem['MEMSH_ProductionOutput'])))

		if not self.textctrl_truck.hasFocus() \
		and self.textctrl_truck.text() != str(int(self.mem['MEMSH_TruckCapacity'])):
			self.textctrl_truck.setText(str(int(self.mem['MEMSH_TruckCapacity'])))

		if not self.textctrl_material_level_warning.hasFocus() \
		and self.textctrl_material_level_warning.text() != str(int(self.mem['MEMSH_MaterialLevelWarning'])):
			self.textctrl_material_level_warning.setText(str(int(self.mem['MEMSH_MaterialLevelWarning'])))

		if not self.textctrl_material_level_error.hasFocus() \
		and self.textctrl_material_level_error.text() != str(int(self.mem['MEMSH_MaterialLevelError'])):
			self.textctrl_material_level_error.setText(str(int(self.mem['MEMSH_MaterialLevelError'])))

		if self.mem['MEMSH_ProductionMode'] == 0:
			set_bg(self.button, 'red')
			set_text(self.button, 'STOP')
		else:
			set_bg(self.button, 'green')
			set_text(self.button, 'OK')

		if self.mem['MEMSH_MaterialProblem'] != 0:
			set_bg(self.button_material_problem, 'red')
			#set_text(self.button_material_problem, 'MAT')
		else:
			set_bg(self.button_material_problem, 'green')
			#set_text(self.button_material_problem, 'MAT')

		#self.set_cem_buttons()

		#if self.mem['IORSH_DO_035'] == 0:
		#	set_bg(self.button_mixer_cover, wx.GREEN)
		#	set_text(self.button_mixer_cover, 'zajisteno')
		#else:
		#	set_bg(self.button_mixer_cover, wx.RED)
		#	set_text(self.button_mixer_cover, 'odjisteno')

		for i in range(len(self.button_mixer)):
			if self.mem['MEMSH_MixerOpenForce'] == i:
				if i == 0:
					set_bg(self.button_mixer[i], 'green')
				else:
					set_bg(self.button_mixer[i], 'red')
			else:
				set_bg(self.button_mixer[i], 'light grey')

		for i in range(len(self.button_mixer_cont)):
			if self.mem['MEMSH_MixerContOpenForce'] == i:
				if i == 0:
					set_bg(self.button_mixer_cont[i], 'green')
				else:
					set_bg(self.button_mixer_cont[i], 'red')
			else:
				set_bg(self.button_mixer_cont[i], 'light grey')

		if self.mem['MEMSH_FunnelOpenForce'] == 0:
			set_bg(self.button_funnel_a, 'green')
			set_bg(self.button_funnel_0, 'light grey')
			set_bg(self.button_funnel_1, 'light grey')
		elif self.mem['MEMSH_FunnelOpenForce'] == 1:
			set_bg(self.button_funnel_a, 'light grey')
			set_bg(self.button_funnel_0, 'red')
			set_bg(self.button_funnel_1, 'light grey')
		elif self.mem['MEMSH_FunnelOpenForce'] == 2:
			set_bg(self.button_funnel_a, 'light grey')
			set_bg(self.button_funnel_0, 'light grey')
			set_bg(self.button_funnel_1, 'red')

		# TODO: the LIGHT_GREY constants are hackish! find something like DEFAULT_COLOUR.
		'''
		if self.mem['MEMSH_Conveyer3Force'] == 0:
			set_bg(self.button_conveyer3_left, 'light grey')
			set_bg(self.button_conveyer3_center, 'green')
			set_bg(self.button_conveyer3_right, 'light grey')

			set_text(self.button_conveyer3_center, 'AUTO')
		elif self.mem['MEMSH_Conveyer3Force'] == 1:
			set_bg(self.button_conveyer3_left, 'green')
			set_bg(self.button_conveyer3_center, 'light grey')
			set_bg(self.button_conveyer3_right, 'light grey')

			set_text(self.button_conveyer3_center, 'AUTO')
		elif self.mem['MEMSH_Conveyer3Force'] == 2:
			set_bg(self.button_conveyer3_left, 'light grey')
			set_bg(self.button_conveyer3_center, 'light grey')
			set_bg(self.button_conveyer3_right, 'green')

			set_text(self.button_conveyer3_center, 'AUTO')
		elif self.mem['MEMSH_Conveyer3Force'] == 3:
			set_bg(self.button_conveyer3_left, 'light grey')
			set_bg(self.button_conveyer3_center, 'red')
			set_bg(self.button_conveyer3_right, 'light grey')

			set_text(self.button_conveyer3_center, 'STOP')
		elif self.mem['MEMSH_Conveyer3Force'] == 4:
			set_bg(self.button_conveyer3_left, 'red')
			set_bg(self.button_conveyer3_center, 'light grey')
			set_bg(self.button_conveyer3_right, 'light grey')

			set_text(self.button_conveyer3_center, '')
		elif self.mem['MEMSH_Conveyer3Force'] == 5:
			set_bg(self.button_conveyer3_left, 'light grey')
			set_bg(self.button_conveyer3_center, 'light grey')
			set_bg(self.button_conveyer3_right, 'red')

			set_text(self.button_conveyer3_center, '')
		'''

		msg = self.mem['MEMSH_Message'].decode('cp1250')
		if msg and not self.displaying_message:
			logging.info('displaying message %s' % msg)
			self.displaying_message = True
			msgbox = QMessageBox(QMessageBox.Warning, 'Chyba', msg, QMessageBox.Ok)
			res = msgbox.exec_()
			#self.mem['MEMSH_MessageAnswer'] = ret  # TODO: this is not used - remove or something...
			self.mem['MEMSH_Message'] = ''.encode()
			self.displaying_message = False

	def set_cem_buttons(self):
		# TODO: hard-coded shit
		if self.mem['IORSH_DO_016'] == 1:
			set_text(self.button_c1, 'C1')
		else:
			set_text(self.button_c1, '')

		# TODO: hard-coded shit
		if self.mem['IORSH_DO_017'] == 1:
			set_text(self.button_c2, 'C2')
		else:
			set_text(self.button_c2, '')

		# TODO: hard-coded shit
		if self.mem['IORSH_DO_016'] != 1 and self.mem['IORSH_DO_017'] != 1:
			set_bg(self.button_c1, 'red')
			set_bg(self.button_c2, 'red')
		else:
			set_bg(self.button_c1, 'light grey')
			set_bg(self.button_c2, 'light grey')


def quit_file_handler(func):
	logging.info('quit file handler executing')
	func()


def main():
	logging_setup('DEBUG', 'control_gui.log')
	logging.info('*' * 40)
	logging.info('starting control_gui v%s' % __version__)

	# TODO: this is hard-coded (=shit!)
	quit_fn = 'quit_gui'
	qf = QuitFile(quit_fn)
	if qf.check_and_delete():
		logging.info('stale quit file found, deleted')

	urlbase = 'http://127.0.0.1:7778'  # TODO: hard-coded shit

	a = QApplication(sys.argv[1:])
	f = Frame(urlbase)

	qf.start_checking(quit_file_handler, (f.close, ))

	f.show()
	a.exec_()

	logging.info('exiting')

	qf.stop_checking()


if __name__ == '__main__':
	main()
'''

script = jedi.Script(line=30, encoding='utf-8', column=32, source=source, path='/home/radek/asterix/pycontrol/control_gui.py')
script.completions()
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a bug in Jedi, which still has issues with Python 3.5. :-( I'm still hoping for a new release of Jedi soon, and I hope this will be fixed, too, then.
