### ISSUE TITLE
ob-ipython code block error

### ISSUE THREAD

**Issue by reconmaster** [jorgenschaefer/elpy#812]
I am trying to test out using [ob-ipython](https://github.com/gregsexton/ob-ipython/) for connecting org-mode code blocks to ipython. So far it looks like it will all work out. However while I was trying to move the cursor up to the magic command starting with % in the below block:

```org
#+BEGIN_SRC ipython :session
  %matplotlib inline
  import matplotlib.pyplot as plt
  import numpy as np

#+END_SRC
```

When doing that, elpy drops the following:

```
Error Message

'dict' object has no attribute 'startswith'

Configuration

Virtualenv........: research (/home/reconmaster/.virtualenvs/research)
RPC Python........: 2.7.11 (/home/reconmaster/.virtualenvs/research/bin/python)
Interactive Python: ipython (/home/reconmaster/.virtualenvs/research/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3
Autopep8..........: Not found (1.2.2 available)
Yapf..............: Not found (0.6.2 available)
Syntax checker....: flake8 (/home/reconmaster/.virtualenvs/research/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/reconmaster/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 340, in run_with_debug
    script = jedi.Script(*args, **kwargs)
  File "/home/reconmaster/.virtualenvs/research/lib/python2.7/site-packages/jedi/api/__init__.py", line 87, in __init__
    self.path = None if path is None else os.path.abspath(path)
  File "/home/reconmaster/.virtualenvs/research/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/home/reconmaster/.virtualenvs/research/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'dict' object has no attribute 'startswith'

Jedi Debug Information

Jedi did not emit any debug info.

```

Reproduction:

```Python
import jedi

source = '''\
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
'''

script = jedi.Script(column=6, source=source, line=3, encoding='utf-8', path={})
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

> `script = jedi.Script(column=6, source=source, line=3, encoding='utf-8', path={})`

Elpy should never send an empty dict as a path … this is weird. Probably `buffer-file-name` is set to `nil` in this org-specific situation, and json.el somehow manages to encode that as an empty dict. Guess Elpy has to special-case that in the backend.
