### ISSUE TITLE
Backend error? 

### ISSUE THREAD

**Issue by IanQS** [jorgenschaefer/elpy#814]
hi! I'm having an error with elpy but I'm not sure what's happening. I read through the first few lines of the error but couldn't figure anything out.

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

```
Error Message

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3
Autopep8..........: 1.2.1 (1.2.2 available)
Yapf..............: 0.6.2
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ian/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 186, in eval_element
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ian/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/__init__.py", line 186, in eval_element
    raise NotImplementedError
NotImplementedError

Jedi Debug Information

[N] dbg: Parsed /home/ian/Desktop/Dropbox/dbDesktop/CMU/S-16/16-264/project/chainer-test/script.py, with 0 parsers in 1 splits.
[W] warning: No statement under the cursor.
[N] dbg: start: 'c' in <fast.FastModule: script@2-14>
[N] dbg: eval_element <Name: c@13,2>@(13, 2)
[N] dbg: finder.filter_name "<Name: c@13,2>" in (<ModuleWrapper: <fast.FastModule: script@2-14>>): '[<Name: c@12,0>]'@(13, 2)
[N]  dbg: eval_statement <ExprStmt: c = a**2 + b**2@12,0> (<Name: c@12,0>)
[N]  dbg: eval_element Node(arith_expr, [Node(power, [<Name: a@12,4>, <Operator: **>, <Number: 2>]), <Operator: +>, Node(power, [<Name: b@12,11>, <Operator: **>, <Number: 2>])])@(12, 4)
[N]  dbg: eval_element Node(power, [<Name: a@12,4>, <Operator: **>, <Number: 2>])@(12, 4)
[N]   dbg: finder.filter_name "<Name: a@12,4>" in (<ModuleWrapper: <fast.FastModule: script@2-14>>): '[<Name: a@10,0>]'@(12, 0)
[N]    dbg: eval_statement <ExprStmt:  a = Variable(np.array([3], dtype=np.float32))@10,0> (<Name: a@10,0>)
[N]    dbg: eval_element Node(power, [<Name: Variable@10,4>, Node(trailer, [<Operator: (>, Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])]), <Operator: )>])])@(10, 4)
[N]     dbg: finder.filter_name "<Name: Variable@10,4>" in (<ModuleWrapper: <fast.FastModule: script@2-14>>): '[<Name: Variable@6,33>]'@(10, 0)
[N]     dbg: search_module 'chainer' in '/home/ian/Desktop/Dropbox/dbDesktop/CMU/S-16/16-264/project/chainer-test/script.py'
[N]      dbg: finder.filter_name "'Variable'" in (<ModuleWrapper: <fast.FastModule: chainer@1-70>>): '[<Name: Variable@28,0>]'@None
[N]       dbg: eval_statement <ExprStmt: Variable = variable.Variable@28,0> (<Name: Variable@28,0>)
[N]       dbg: eval_element Node(power, [<Name: variable@28,11>, Node(trailer, [<Operator: .>, <Name: Variable@28,20>])])@(28, 11)
[N]        dbg: finder.filter_name "<Name: variable@28,11>" in (<ModuleWrapper: <fast.FastModule: chainer@1-70>>): '[<Name: variable@12,20>]'@(28, 0)
[N]         dbg: finder.filter_name "'variable'" in (<ModuleWrapper: <fast.FastModule: chainer@1-70>>): '[<Name: variable@12,20>]'@None
[N]         dbg: finder._names_to_types: [<Name: variable@12,20>] -> []
[N]        dbg: search_module 'chainer.variable' in paths ['/usr/lib/python3.5/site-packages/chainer']
[N]        dbg: after import: [<ModuleWrapper: <fast.FastModule: variable@1-448>>]
[N]        dbg: finder._names_to_types: [<Name: variable@12,20>] -> [<ModuleWrapper: <fast.FastModule: variable@1-448>>]
[N]       dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: Variable@28,20>]) in scope <ModuleWrapper: <fast.FastModule: variable@1-448>>
[N]        dbg: finder.filter_name "<Name: Variable@28,20>" in (<ModuleWrapper: <fast.FastModule: variable@1-448>>): '[<Name: Variable@51,6>]'@None
[N]        dbg: finder._names_to_types: [<FakeName: Variable@51,6>] -> [<eClass of <Class: Variable@51-152>>]
[N]       dbg: eval_statement result [<eClass of <Class: Variable@51-152>>]
[N]      dbg: finder._names_to_types: [<Name: Variable@28,0>] -> [<eClass of <Class: Variable@51-152>>]
[N]     dbg: after import: [<eClass of <Class: Variable@51-152>>]
[N]     dbg: finder._names_to_types: [<Name: Variable@6,33>] -> [<eClass of <Class: Variable@51-152>>]
[N]    dbg: eval_trailer: Node(trailer, [<Operator: (>, Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])]), <Operator: )>]) in scope <eClass of <Class: Variable@51-152>>
[N]     dbg: execute: <eClass of <Class: Variable@51-152>> <Arguments: Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])])>
[N]     dbg: eval_element <Name: object@51,15>@(51, 15)
[N]      dbg: finder.filter_name "<Name: object@51,15>" in (<eClass of <Class: Variable@51-152>>): '[<CompiledName: (builtins).object>]'@(51, 15)
[N]      dbg: finder._names_to_types: [<CompiledName: (builtins).object>] -> [<CompiledObject: <class 'object'>>]
[N]      dbg: execute: <InstanceElement of <eFunction of <Function: __init__@89-101>>> <Arguments: Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])])>
[N]      dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@89-101>>>
[N]     dbg: execute result: [<eInstance of <eClass of <Class: Variable@51-152>>(<Arguments: Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])])>)>] in <eClass of <Class: Variable@51-152>>
[N]    dbg: eval_statement result [<eInstance of <eClass of <Class: Variable@51-152>>(<Arguments: Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])])>)>]
[N]   dbg: finder._names_to_types: [<Name: a@10,0>] -> [<eInstance of <eClass of <Class: Variable@51-152>>(<Arguments: Node(power, [<Name: np@10,13>, Node(trailer, [<Operator: .>, <Name: array@10,16>]), Node(trailer, [<Operator: (>, Node(arglist, [Node(atom, [<Operator: [>, <Number: 3>, <Operator: ]>]), <Operator: ,>, Node(argument, [<Name: dtype@10,27>, <Operator: =>, Node(power, [<Name: np@10,33>, Node(trailer, [<Operator: .>, <Name: float32@10,36>])])])]), <Operator: )>])])>)>]

```

Reproduction:

```Python
import jedi

source = '''\
#Matplotlib and NumPy
import numpy as np
import matplotlib.pyplot as plt

#Chainer Specific
from chainer import FunctionSet, Variable, optimizers, serializers
import chainer.functions as F
import chainer.links as L

a = Variable(np.array([3], dtype=np.float32))
b = Variable(np.array([4], dtype=np.float32))
c = a**2 + b**2
c.
'''

script = jedi.Script(encoding='utf-8', source=source, path='/home/ian/Desktop/Dropbox/dbDesktop/CMU/S-16/16-264/project/chainer-test/script.py', column=2, line=13)
script.completions()
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This is a bug in Jedi – it was reported a while back, but has not been fixed upstream yet. This is the same error as in #779, I'll close this issue so we can keep the discussion in one place.

Elpy should probably just ignore this error until Jedi catches up.
