### ISSUE TITLE
Permission denied on... /root

### ISSUE THREAD

**Issue by pxcluster** [jorgenschaefer/elpy#818]
Jorgen,

I think I found the problem... It's when I edit a line in a file, which contains an import of a module named 'root' from the current directory... Why, I don't know... but this is when this error happened (for the second time).

Best regards,

Daniel Cordey

Error Message

[Errno 13] Permission denied: '/root'

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.2 (0.10.3 available)
Importmagic.......: Not found (0.1.3 available)
Autopep8..........: Not found (0.1.3 available)
Syntax checker....: Not found (pyflakes)

Traceback

Traceback (most recent call last):
  File "/home/dc/.emacs.d/elpa/elpy-20151101.401/elpy/ropebackend.py", line 100, in call_rope
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 96, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/usr/lib/python2.7/dist-packages/rope/contrib/codeassist.py", line 509, in get_calltip
    pyobject = pyobject['__call__'].get_object()
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 202, in get_attribute
    if name in self._get_structural_attributes():
  File "/usr/lib/python2.7/dist-packages/rope/base/utils.py", line 28, in newfunc
    return func(self, *args, **kwds)
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 184, in _get_structural_attributes
    self.structural_attributes = self._create_structural_attributes()
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 232, in _create_structural_attributes
    for name, resource in self._get_child_resources().items():
  File "/usr/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 246, in _get_child_resources
    for child in self.resource.get_children():
  File "/usr/lib/python2.7/dist-packages/rope/base/resources.py", line 118, in get_children
    for name in os.listdir(self.real_path):
OSError: [Errno 13] Permission denied: '/root'

Rope Debug Information

```

Reproduction:

```Python

source = '''
#!/usr/bin/python3
### root.py --- 
## 
## Filename     : root.py
## Description  : The PxCluster Home page
## Author       : Daniel Cordey
## Maintainer   : Daniel Cordey
## Created      : Sun Jul  5 00:37:53 2015
## Version      : 1.0.0
## Last-Updated : 05/03/2016 15:23:53 (+0100)
##           By : Daniel Cordey, dc@PxClsuster.com
##     Update # : 137
## URL          : 
## Keywords     : 
## Compatibility: 
## 
######################################################################
## 
### Commentary   : 
## 
## 
## 
######################################################################
## 
### Change log:
## 
## 
### Code         :

from io import open

#from pxcluster import Version

# Test settings
testing_module = __name__ == '__{}__'.format('main')

__version__ = b'1.0.0.' #Version('1.0.0')

############################# USER CODE #############################

import sys

from time import time as now

from pxcluster import get_list
from pxcluster.html import Body, Doctype, Head, Html, Script

try :
    from .css import css
    from .js import js
    from .meta import meta as metas
    from .title import title

except ImportError as e :
    # Local test outside a package environment (not relative import)
    from css import css
    from js import js
    from meta import meta as metas
    from title import title
    from root import root


def root(indent = 0) :
    page = Doctype(mode = 'html')
    html = Html(parent = page)
    head = Head(parent = html)
    metas.generate(parent = head)
    title.generate(parent = head)
    css.generate(parent = head)
    js.generate(parent = head)

    # Start Body
    body = Body(parent = html)
    home = home.generate(parent = body)

    return page.html(indent = indent)



############################# TESTING #############################
if testing_module :
 ...

**Comment by pxcluster** [comment]
As far as I know, it's supposed to be running python3.4, not python 2.7... Maybe, elpy is using the default python configured in my system (which is 1.7 at the moment). How can this be changed in the elpy.el file ? It's quiet large and I'm scared to screw up some variables.

**Comment by jorgenschaefer** [comment]
You can change the Python interpreter used by changing the `elpy-rpc-python-command` variable, either manually in your init file, or my using `M-x customize-variable RET elpy-rpc-python-command RET`. Alternatively, I can highly recommend using virtualenvs. :-) There should never be a reason to edit elpy.el directly.

That Elpy fails for a `root` module is interesting. It does change the current directory to `/` to avoid bogus imports, and that means it _could_ try to open `/root` as a package, but I have not been able to reproduce this. Do you have some minimal reproduction steps that cause this to happen?

**Comment by pxcluster** [comment]
Thanks for the tip !

Reproducing the problem : Let me try to find the minimal set of code needed to reproduce it... gime some time :-)

**Comment by pxcluster** [comment]
I still haven't been able to reproduce the problem. It seems it has something to do with some key-binding which triggers some python interpretation while I edit a line like 'from root import root'. However, I've tried many different interpretation/syntax-check/etc. but none of them showed the problem...

I'll continue to monitor this issue and will let you know as soon as I'm able to reproduce it. Strange... :-)

**Comment by jorgenschaefer** [comment]
Thank you for the work!
