### ISSUE TITLE
Elpy Error after updating anaconda-mode

### ISSUE THREAD

**Issue by teigkringel** [jorgenschaefer/elpy#831]
Elpy Error

Occured after installing new version of anaconda-mode. 

The backend encountered an unexpected error. This indicates a bug in Elpy.
Please open a bug report with the data below in the Elpy bug tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

argument should be string, bytes or integer, not dict

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/sbin/python)
Interactive Python: ipython (/usr/sbin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: Not found (0.9.0 available)
Rope..............: 0.10.3
Importmagic.......: Not found (0.1.5 available)
Autopep8..........: 1.2.1 (1.2.2 available)
Yapf..............: Not found (0.6.3 available)
Syntax checker....: Not found (pyflakes)

Traceback

Traceback (most recent call last):
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 88, in rpc_get_calltip
    get_source(source), offset)
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/ropebackend.py", line 165, in rpc_get_calltip
    remove_self=True
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/ropebackend.py", line 93, in call_rope
    resource = self.get_resource(filename)
  File "~/.emacs.d/elpa/elpy-20160131.118/elpy/ropebackend.py", line 68, in get_resource
    if filename is not None and os.path.exists(filename):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not dict
```

**Comment by jorgenschaefer** [comment]
Thank you for the report … I positively remember this reported in another issue, but I can't find it now. For some reason, elpy is passing an empty object as the project path, that should not happen.

**Comment by jorgenschaefer** [comment]
Ah yes, #812 also has `project_root` as a dict. Probably due to a json.el encoding error. Closing this issue to track the problem in a single spot. Thanks for the report!
