### ISSUE TITLE
Elpy error when typing unittest.main(war with jedi backend

### ISSUE THREAD

**Issue by lgp171188** [jorgenschaefer/elpy#838]
Here is the error

    Elpy Error
    
    The backend encountered an unexpected error. This indicates a bug in
    Elpy. Please open a bug report with the data below in the Elpy bug
    tracker:
    
    https://github.com/jorgenschaefer/elpy/issues/new
    
    ```
    Error Message
    
    'Operator' object has no attribute 'get_definition'
    
    Configuration
    
    Virtualenv........: venv (/Users/gnarayan/dev/py/obeythetestinggoat/venv)
    RPC Python........: 3.5.1 (/Users/gnarayan/dev/py/obeythetestinggoat/venv/bin/python)
    Interactive Python: python (/Users/gnarayan/dev/py/obeythetestinggoat/venv/bin/python)
    Emacs.............: 24.5.1
    Elpy..............: 1.11.0
    Jedi..............: 0.9.0
    Rope..............: Not found (0.10.3 available)
    Importmagic.......: 0.1.7
    Autopep8..........: Not found (1.2.2 available)
    Yapf..............: Not found (0.6.3 available)
    Syntax checker....: flake8 (/Users/gnarayan/dev/py/obeythetestinggoat/venv/bin/flake8)
    
    Traceback
    
    Traceback (most recent call last):
      File "/Users/gnarayan/.emacs.d/elpa/elpy-1.11.0/elpy/jedibackend.py", line 227, in run_with_debug
        return getattr(script, name)()
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
        for p in call_sig.params:
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
        return [_Param(self._evaluator, p.name) for p in params]
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
        return [_Param(self._evaluator, p.name) for p in params]
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
        return super(CachedMetaClass, self).__call__(*args, **kwargs)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
        super(Definition, self).__init__(evaluator, definition)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
        self._definition = evaluator.wrap(self._name.get_definition())
    AttributeError: 'Operator' object has no attribute 'get_definition'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/gnarayan/.emacs.d/elpa/elpy-1.11.0/elpy/jedibackend.py", line 341, in run_with_debug
        return getattr(script, name)()
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
        for p in call_sig.params:
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
        return [_Param(self._evaluator, p.name) for p in params]
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
        return [_Param(self._evaluator, p.name) for p in params]
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
        return super(CachedMetaClass, self).__call__(*args, **kwargs)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
        super(Definition, self).__init__(evaluator, definition)
      File "/Users/gnarayan/dev/py/obeythetestinggoat/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
        self._definition = evaluator.wrap(self._name.get_definition())
    AttributeError: 'Operator' object has no attribute 'get_definition'
    
    Jedi Debug Information
    
    [N] dbg: Parsed /Users/gnarayan/dev/py/obeythetestinggoat/superlists/functional_tests.py, with 0 parsers in 6 splits.
    [W] warning: No statement under the cursor.
    [N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
    [N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
    [N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
    [N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
    [N] dbg: eval_element Node(power, [<Name: unittest@51,4>, Node(trailer, [<Operator: .>, <Name: main@51,13>])])@(51, 4)
    [N] dbg: finder.filter_name "<Name: unittest@51,4>" in (<ModuleWrapper: <fast.FastModule: functional_tests@1-52>>): '[<Name: unittest@9,7>]'@(51, 4)
    [N] dbg: Found django path: '/Users/gnarayan/dev/py/obeythetestinggoat/superlists/functional_tests.py'
    [N] dbg: search_module 'unittest' in '/Users/gnarayan/dev/py/obeythetestinggoat/superlists/functional_tests.py'
    [N] dbg: after import: [<ModuleWrapper: <fast.FastModule: unittest@1-79>>]
    [N] dbg: finder._names_to_types: [<Name: unittest@9,7>] -> [<ModuleWrapper: <fast.FastModule: unittest@1-79>>]
    [N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: main@51,13>]) in scope <ModuleWrapper: <fast.FastModule: unittest@1-79>>
    [N] dbg: finder.filter_name "<Name: main@51,13>" in (<ModuleWrapper: <fast.FastModule: unittest@1-79>>): '[<Name: main@64,31>]'@None
    [N] dbg: search_module 'unittest.main' in paths ['/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest']
    [N]  dbg: finder.filter_name "'main'" in (<ModuleWrapper: <fast.FastModule: main@1-260>>): '[<Name: main@259,0>]'@None
    [N]   dbg: eval_statement <ExprStmt: main = TestProgram@259,0> (<Name: main@259,0>)
    [N]   dbg: eval_element <Name: TestProgram@259,7>@(259, 7)
    [N]    dbg: finder.filter_name "<Name: TestProgram@259,7>" in (<ModuleWrapper: <fast.FastModule: main@1-260>>): '[<Name: TestProgram@48,6>]'@(259, 0)
    [N]    dbg: finder._names_to_types: [<FakeName: TestProgram@48,6>] -> [<eClass of <Class: TestProgram@48-259>>]
    [N]   dbg: eval_statement result [<eClass of <Class: TestProgram@48-259>>]
    [N]  dbg: finder._names_to_types: [<Name: main@259,0>] -> [<eClass of <Class: TestProgram@48-259>>]
    [N] dbg: after import: [<eClass of <Class: TestProgram@48-259>>]
    [N] dbg: finder._names_to_types: [<Name: main@64,31>] -> [<eClass of <Class: TestProgram@48-259>>]
    [N] dbg: eval_element <Name: object@48,18>@(48, 18)
    [N] dbg: finder.filter_name "<Name: object@48,18>" in (<eClass of <Class: TestProgram@48-259>>): '[<CompiledName: (builtins).object>]'@(48, 18)
    [N] dbg: finder._names_to_types: [<CompiledName: (builtins).object>] -> [<CompiledObject: <class 'object'>>]
    
    ```
    
    Reproduction:
    
    ```Python
    import jedi
    
    source = '''\
    from selenium import webdriver
    
    
    browser = webdriver.Firefox()
    
    
    browser.quit()
    
    import unittest
    
    
    class NewVisitorTest(unittest.TestCase):
    
        def setUp(self):
            self.browser = webdriver.Firefox()
    
        def tearDown(self):
            self.browser.quit()
    
        def test_can_start_a_list_and_retrieve_it_later(self):
    
            # Edit has heard about a cool new online to-do app. She goes
            # to check out its homepage
            self.browser.get('http://localhost:8000')
    
            # She notices the page title and header mention to-do lists
            assert 'To-Do' in self.browser.title, "Browser title was " + self.browser.title
    
            # She is invited to enter a to-do item straight away
    
            # She types "Buy peacock feathers" into a text box (Edith's hobby
            # is tying fly-fishing lures
    
            # When she hits enter, the page updates, and now the page lists
            # "1: Buy peacock feathers" as an item in a to-do list
    
            # There is still a text box inviting her to add another item. She
            # Enters "Use peacock feathers to make a fly" (Edith is very methodical)
    
            # The page updates again, and now shows both items on her list
    
            # Edith wonders whether the site will remember her list. Then she sees
            # that the site has generated a unique URL for her -- there is some
            # explanatory text to that effect.
    
            # She visits that URL - her to-do list is still there.
    
            # Satisfied, she goes back to sleep
    
    if __name__ == '__main__':
        unittest.main(war
    '''
    
    script = jedi.Script(source=source, line=51, path='/Users/gnarayan/dev/py/obeythetestinggoat/superlists/functional_tests.py', encoding='utf-8', column=21)
    script.completions()
    ```

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the report! This is a known bug in Jedi related to Python 3.5, which was reported here as #810 and reported upstream as well … I'm afraid there is not a lot Elpy can do about it :-( If this happens repeatedly, you can set `elpy-disable-backend-error-display` to a true value, which will at least prevent this error.

**Comment by lgp171188** [comment]
@jorgenschaefer Thanks for the quick response. Sorry for not searching existing issues reporting the same problem and filing a duplicate bug report.

**Comment by jorgenschaefer** [comment]
No problem at all. I'd rather get duplicate reports than no reports. Never feel bad about reporting an issue! :-) I'll close this one so we can keep track of the problem in one spot, but do not hesitate to open a new issue if you have any further problems. Hopefully you don't, though. Enjoy Elpy! :-)
