### ISSUE TITLE
Jedi crashes on certain import structures

### ISSUE THREAD

**Issue by nsp** [jorgenschaefer/elpy#844]
Almost certainly a Jedi only issue, but I'm not sure how it's being invoked. The error happens when I M-. in api.py on anything to do with foo.bar.baz.

```
Error Message

local variable 'module_path' referenced before assignment

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2
Yapf..............: 0.6.3
Syntax checker....: flake8 (/home/nate/.local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/nate/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 362, in goto_definitions
    definitions = set(self._prepare_goto(goto_path))
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/home/nate/.local/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 316, in _do_import
    module_path = None
UnboundLocalError: local variable 'module_path' referenced before assignment

Jedi Debug Information

[N] dbg: Parsed /home/nate/prj/jediproblem/python/foo.bar.zip.zop/foo/bar/zip/zop/api.py, with 0 parsers in 1 splits.
[N] dbg: start: u'Baz' in <fast.FastModule: api@1-5>
[N] dbg: eval_element <Name: Baz@3,0>@(3, 0)
[N] dbg: finder.filter_name "<Name: Baz@3,0>" in (<ModuleWrapper: <fast.FastModule: api@1-5>>): u'[<Name: Baz@1,24>]'@(3, 0)
[N] dbg: search_module 'foo' in u'/home/nate/prj/jediproblem/python/foo.bar.zip.zop/foo/bar/zip/zop/api.py'
[N] dbg: search_module 'foo.bar' in paths [u'/home/nate/prj/jediproblem/python/foo.bar.zip.zop/foo']
[N] dbg: search_module 'foo.bar.baz' in paths []

```

Reproduction:

```Python
import jedi

source = '''\
from foo.bar.baz import Baz

b = Baz()
b.report()
'''

script = jedi.Script(encoding='utf-8', column=4, source=source, path=u'/home/nate/prj/jediproblem/python/foo.bar.zip.zop/foo/bar/zip/zop/api.py', line=3)
script.goto_definitions()
```

I've recreated my project's directory hierarchy with generic identifiers, and minimal code. For context, the output of `tree` is 

```/home/nate/prj/jediproblem/python
├── foo.bar.baz
│   └── foo
│       ├── bar
│       │   ├── baz.py
│       │   └── __init__.py
│       └── __init__.py
└── foo.bar.zip.zop
    └── foo
        ├── bar
        │   ├── __init__.py
        │   └── zip
        │       ├── __init__.py
        │       └── zop
        │           ├── api.py
        │           └── __init__.py
        └── __init__.py
```

And the content of baz.py is simply

```class Baz():
    def report(self):
        print 'In baz'```

**Comment by jorgenschaefer** [comment]
Thank you for the report! I'll forward this upstream to Jedi, so it can be fixed there. :-)
