### ISSUE TITLE
'NoneType' object has no attribute 'names_dicts' editing remote python file

### ISSUE THREAD

**Issue by reconmaster** [jorgenschaefer/elpy#845]
As elpy doesn't work with tramp, my usual workflow is just to clone my virtualenv from the remote computational machine and then just use tramp to modify different files prior to remotely testing them on those servers. When I was editing one such file for a project, I got the following error message:

```
Error Message

'NoneType' object has no attribute 'names_dicts'

Configuration

Virtualenv........: recon (/home/reconmaster/.virtualenvs/recon)
RPC Python........: 2.7.11 (/home/reconmaster/.virtualenvs/recon/bin/python)
Interactive Python: ipython (/home/reconmaster/.virtualenvs/recon/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3 (0.1.7 available)
Autopep8..........: Not found (1.2.2 available)
Yapf..............: Not found (0.6.3 available)
Syntax checker....: flake8 (/home/reconmaster/.virtualenvs/recon/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/reconmaster/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/reconmaster/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 95, in rpc_get_completions
    get_source(source), offset)
  File "/home/reconmaster/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/reconmaster/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/home/reconmaster/.virtualenvs/recon/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
AttributeError: 'NoneType' object has no attribute 'names_dicts'
```

Even without the RPC support for running the python code via tramp on a remote machine, elpy is still incredibly useful for developing python code. Maybe there is a way to use elpy from the local machine environement for editing remote code by treating the buffer as an instance of the local virtualenv?

The main reason for this approach is a lot of the computation methods are resource intensive and have a lot of cuda/fortran backends compiled explicitly for that computation machines architecture. Other than periodic errors like this, most of the elpy functionality works rather well with this approach. The only feature besides running the code that would be useful with this workflow is the elpy-doc functionality.

My guess is this error arose because I was editing such a remote file with a tramp buffer. Let me know if you have any ideas/suggestions about this approach or error.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is actually unrelated to remoteness of the file, and a bug in Jedi – this should be the same as #569, reported upstream as davidhalter/jedi#593 … I hope Jedi does a new release with these fixes soon :-(

I will close this issue as we already have one tracking this particular problem, but please do not hesitate to open a new issue if you have further problems!
