### ISSUE TITLE
Elpy Error : Backend encountered unexpected error.

### ISSUE THREAD

**Issue by bibek22** [jorgenschaefer/elpy#850]
```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (0.1.7 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bibek/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

Jedi Debug Information

[N] dbg: Parsed /home/bibek/templates/python/selenium/OmegleBot/api.py, with 0 parsers in 9 splits.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
[N] dbg: eval_element Node(power, [<Name: threading@146,0>, Node(trailer, [<Operator: .>, <Name: Thread@146,10>])])@(146, 0)
[N] dbg: finder.filter_name "<Name: threading@146,0>" in (<ModuleWrapper: <fast.FastModule: api@4-149>>): '[<Name: threading@8,7>]'@(146, 0)
[N] dbg: search_module 'threading' in '/home/bibek/templates/python/selenium/OmegleBot/api.py'
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: threading@1-1353>>]
[N] dbg: finder._names_to_types: [<Name: threading@8,7>] -> [<ModuleWrapper: <fast.FastModule: threading@1-1353>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: Thread@146,10>]) in scope <ModuleWrapper: <fast.FastModule: threading@1-1353>>
[N] dbg: finder.filter_name "<Name: Thread@146,10>" in (<ModuleWrapper: <fast.FastModule: threading@1-1353>>): '[<Name: Thread@736,6>]'@None
[N] dbg: finder._names_to_types: [<FakeName: Thread@736,6>] -> [<eClass of <Class: Thread@736-1156>>]

```

Reproduction:

```Python
import jedi

source = '''\
#!/usr/bin/python

# Python Omegle bot.
from urllib import request, parse
import _thread as thr
from time import sleep
import json
import threading
idList = list()


def console(id):
    global checkMale
    while True:
        print(">>> ", end="")
        get = input()
        if len(get) == 0:
            continue
        else:
            try:
                sendOmegle(get, recId=id)
            except Exception as e:
                print(e)


def disconnect(id):
    request.urlopen('http://omegle.com/disconnect',
                    parse.urlencode({'id': id}).encode('utf-8'))


# for posting things
def sendOmegle(msg, sendId=None, recId=None):
    '''if id is None, send to all'''
    if recId is not None:
        if sendId is not None:
            print('*** Not supported yet.')
        else:
            # send msg from bot to one person
            request.urlopen('http://omegle.com/send',
                            parse.urlencode({'id': recId,
                                             'msg': msg}).encode('utf-8'))
            # print(msg)
    else:
        if sendId is not None:
            # send msg from one person to all
            sentMsg = sendId + ': ' + msg
            for id in idList:
                if id != sendId:
                    request.urlopen(
                        'http://omegle.com/send',
                        parse.urlencode({'id': id,
                                         'msg': sentMsg}).encode('utf-8'))
            try:
                print(sendId + ': ' + msg.decode('utf-8'))
            except:
                print('*** OH GOD AN EXCEPTION')
                # print(sentMsg)
        else:
            # send msg from bot to all
            for id in idList:
                request.urlopen('http://omegle.com/send',
                                parse.urlencode({'id': id,
                                                 'msg': msg}).encode('utf-8'))
            # print(msg)


def fmtId(string):
    dic = json.loads(string)
    return dic["clientID"]


def connect():
    # start omegle
    site = str(request.urlopen('http://front14.omegle.com/start?rcs=1&firstevents=1&spid=&randid=PQTG4JC9&group=unmon&lang=en').read(), 'utf-8')
    # get id
    id = fmtId(site)

    idList.append(id)

    # connect
    req = request.Request('http://omegle.com/events',
                          parse.urlencode({'id': id}).encode('utf-8'))

    print('*** Getting a stranger...')

    site = request.urlopen(req)
    rec = json.loads(str(site.read(), 'utf-8'))
    sleep(.5)
    if 'connected' in str(rec):
        print('*** You have connected!')
        runOne(id)


def runAll():
    for id in idList:
        thr.start_new_thread(runOne, (id,))
    while len(idList) != 0:
        pass
    print('*** Everyone left.')


def runOne(id):
    print("NEW RUN!!")
    global idList
    while len(idList) != 0:
        isDisconnected = False
        site = request.urlopen('http://omegle.com/events',
                               parse.urlencode({'id': id}).encode('utf-8'))
        rec = str(site.read(), "utf-8")
        # prompt to send message
        consolee = threading.Thread(target=console(id))
        consolee.start()
        print("moving on...")
        if rec != 'null':
            inputs = eval(rec)
            for inp in inputs:
                if inp[0] == "strangerDisconnected":
                    idList.remove(id)
                    if len(idList) > 1:
                        sendOmegle(id + ' disconnected, ' +
                                   str(len(idList) - 1) + ' other(s) left.')
                    else:
                        sendOmegle('Everyone but you disconnected, so I\'m out. \
Have a nice day!')
                        disconnect(idList[0])
                        idList = list()
                    isDisconnected = True
                elif inp[0] == "gotMessage":
                    print("Stranger: ", inp[1])
                    if inp[1] == 'list':
                        print('***', id, 'has requested a list of IDs.')
                        sendOmegle('List of all IDs:', None, id)
                        for dispId in idList:
                            sendOmegle(dispId, None, id)
                    elif inp[1] == 'info':
                        print('***', id, 'has requested info about the bot.')
                        sendOmegle('This bot is not affiliated in any way with Omegle. \
It was just made by a nerd with no life. It\'s in Python!', None, id)
                    else:
                        # sendOmegle(inp[1].decode('raw_unicode_escape').encode('utf-8'), id, None)
                        pass
        if isDisconnected:
            break


main = threading.Thread(tar)
while(True):
    connect()
'''

script = jedi.Script(path='/home/bibek/templates/python/selenium/OmegleBot/api.py', source=source, column=27, encoding='utf-8', line=146)
script.completions()
```

**Comment by bibek22** [comment]
Hey, maybe i should open a new thread, but i took this opportunity to ask this. 
is there a way to automatically correct the syntax as checked by flake8?
I mean the complaints like "whitespace expected after , ", "two blank lines expected before ..", and things like that? 
does something like this alrady exist? if not is this doable? (if it is maybe i'll try to implement something like this) thank you.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a known bug in Jedi, and should be the same as reported in #810 … I'm afraid there's not a lot Elpy can do about it, I still hope for a new release of Jedi.

I'll close this issue so we can keep track of the problem in the existing one, but please never hesitate to open a new issue if you have any further problems. And enjoy Elpy!

**Comment by jorgenschaefer** [comment]
> is there a way to automatically correct the syntax as checked by flake8?

You can try `C-c C-r f` (refactor, format code), which uses either yapf or autopep8, depending on which is installed. :-)

**Comment by bibek22** [comment]
perfect!
