### ISSUE TITLE
'Token' object has no attribute 'name'

### ISSUE THREAD

**Issue by j-wang** [jorgenschaefer/elpy#855]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'Token' object has no attribute 'name'

Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (0.1.7 available)
Syntax checker....: pyflakes (/usr/local/bin/pyflakes)

Traceback

Traceback (most recent call last):
  File "/Users/James/.emacs.d/elpa/elpy-20151101.401/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/James/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/Users/James/.emacs.d/elpa/elpy-20151101.401/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/James/.emacs.d/elpa/elpy-20151101.401/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/Library/Python/2.7/site-packages/jedi/api/classes.py", line 501, in type
  File "/Library/Python/2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    if default is not NO_DEFAULT:
  File "/Library/Python/2.7/site-packages/jedi/api/classes.py", line 533, in follow_definition
    'def f'
  File "/Library/Python/2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    if default is not NO_DEFAULT:
  File "/Library/Python/2.7/site-packages/jedi/api/classes.py", line 518, in _follow_statements_imports
    >>> from jedi import Script
  File "/Library/Python/2.7/site-packages/jedi/evaluate/imports.py", line 341, in follow
    source = module_file.read()
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 260, in follow_path
    elif trailer_op == '[':
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 309, in _follow_path
  File "/Library/Python/2.7/site-packages/jedi/evaluate/imports.py", line 482, in follow_imports
    module = _load_module(evaluator, path, source)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/imports.py", line 203, in follow
    path = module.py__file__()
  File "/Library/Python/2.7/site-packages/jedi/evaluate/imports.py", line 203, in <genexpr>
    path = module.py__file__()
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 260, in follow_path
    elif trailer_op == '[':
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 308, in _follow_path
    return self.eval_element(call)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 113, in find_types
    :param position: Position of the last statement -> tuple of line, column
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    try:
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 47, in find
    names_new.append(n)
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 222, in _names_to_types
    while not isinstance(until, er.FunctionExecution):
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 260, in _remove_statements
    return result
  File "/Library/Python/2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    if default is not NO_DEFAULT:
  File "/Library/Python/2.7/site-packages/jedi/evaluate/recursion.py", line 24, in run
    rec_detect.pop_stmt()
  File "/Library/Python/2.7/site-packages/jedi/debug.py", line 51, in wrapper
    try:
  File "/Library/Python/2.7/site-packages/jedi/evaluate/__init__.py", line 158, in eval_statement
    return types
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 563, in find_assignments
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 544, in _assign_tuples
    if isinstance(instance, compiled.CompiledObject):
  File "/Library/Python/2.7/site-packages/jedi/evaluate/finder.py", line 564, in find_assignments
AttributeError: 'Token' object has no attribute 'name'
```

**Comment by j-wang** [comment]
Saw [issue 372](https://github.com/jorgenschaefer/elpy/issues/372), upgraded Jedi from 0.8, but am still having the particular error pop up every few seconds. Nothing particularly novel about the code I'm working on or setup of the environment I'm using to write it right now.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Did you restart the RPC backend after upgrading (using `M-x elpy-rpc-restart`)?

**Comment by j-wang** [comment]
Finished out for the night, but I'll try it out and report back.

**Comment by j-wang** [comment]
Haven't encountered the error again after generally restarting Emacs/computer. Will let you know if I come across it again.

**Comment by jorgenschaefer** [comment]
Great. Please do not hesitate to open a new issue if you have any other problems, and enjoy Elpy! :-)
