### ISSUE TITLE
Jedi: NotImplementedError

### ISSUE THREAD

**Issue by kirang89** [jorgenschaefer/elpy#859]
For some reason Elpy keeps crashing up on me with the trace as below. Any idea as to what might be causing this ?

```
Error Message



Configuration

Virtualenv........: None
RPC Python........: 2.7.10 (/Library/Frameworks/Python.framework/Versions/2.7/bin/python)
Interactive Python: python (/Library/Frameworks/Python.framework/Versions/2.7/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.3 (0.1.7 available)
Autopep8..........: 1.2.1 (1.2.2 available)
Yapf..............: 0.6.2 (0.6.3 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/kiran/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 159, in names_dict_lookup
    stmt, origin_scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/flow_analysis.py", line 48, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/flow_analysis.py", line 65, in _break_check
    reachable = _check_if(evaluator, node)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/flow_analysis.py", line 79, in _check_if
    types = evaluator.eval_element(node)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 364, in py__call__
    return Function.py__call__(self, evaluator, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/_compatibility.py", line 122, in <lambda>
    return lambda *args, **kwargs: self.func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 100, in run
    result = func(execution, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/representation.py", line 620, in get_return_types
    check = flow_analysis.break_check(self._evaluator, self, r)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/flow_analysis.py", line 48, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/flow_analysis.py", line 65, in _break_check
    reachable = _check_if(evaluator, node)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/flow_analysis.py", line 79, in _check_if
    types = evaluator.eval_element(node)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/precedence.py", line 61, in calculate_children
    evaluator.eval_element(right))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/precedence.py", line 61, in calculate_children
    evaluator.eval_element(right))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/precedence.py", line 61, in calculate_children
    evaluator.eval_element(right))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 186, in eval_element
    raise NotImplementedError
NotImplementedError

```

**Comment by ChillarAnand** [comment]
Might be a bug in jedi https://github.com/jorgenschaefer/elpy/issues/779

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! As @ChillarAnand says, this is a bug in Jedi. We reported this problem with Jedi in January, but it apparently has not been fixed yet.

If this interferes with your work, set `elpy-disable-backend-error-display` to a true value. That won't fix the error, but it will prevent these popups.

I'll close this issue so we can keep track of the problem in one place, #779, but please do not hesitate to open a new issue if you have any further problems!

**Comment by kirang89** [comment]
Sure, thanks @ChillarAnand and @jorgenschaefer
