### ISSUE TITLE
Jedi: KeyError: '¹è'

### ISSUE THREAD

**Issue by frankning2015** [jorgenschaefer/elpy#863]
```
Error Message

'¹è'

Configuration

Virtualenv........:  (/Users/frankning/python/duobao/venv/)
RPC Python........: 3.5.0 (/Users/frankning/python/duobao/venv/bin/python)
Interactive Python: ipython (/Users/frankning/python/duobao/venv/bin/ipython)
Emacs.............: 25.0.91.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.7
Autopep8..........: 0.1.7
Syntax checker....: flake8 (/Users/frankning/python/duobao/venv/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/Users/frankning/.emacs.d/elpa/elpy-1.10.0/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/Users/frankning/.emacs.d/elpa/elpy-1.10.0/elpy/server.py", line 94, in rpc_get_completions
    get_source(source), offset)
  File "/Users/frankning/.emacs.d/elpa/elpy-1.10.0/elpy/server.py", line 49, in _call_backend
    return meth(*args, **kwargs)
  File "/Users/frankning/.emacs.d/elpa/elpy-1.10.0/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/Users/frankning/.emacs.d/elpa/elpy-1.10.0/elpy/jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 347, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 450, in _load_module
    module = load(source) if cached is None else cached.module
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 445, in load
    p = fast.FastParser(evaluator.grammar, common.source_to_unicode(source), p)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/fast.py", line 106, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/fast.py", line 243, in __init__
    self.update(source)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/fast.py", line 397, in _parse
    line_offset, nodes)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/pgen2/parse.py", line 105, in parse
    for type, value, prefix, start_pos in tokenizer:
  File "/Users/frankning/python/duobao/venv/lib/python3.5/site-packages/jedi/parser/__init__.py", line 343, in _tokenize
    typ = token.opmap[value]
KeyError: '¹è'
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! That's a weird error – can you share the source file that causes it?
