### ISSUE TITLE
Elpy Error report

### ISSUE THREAD

**Issue by TomKealy** [jorgenschaefer/elpy#864]
Dear Jorgen, Elpy told me to tell you this:

```
Error Message

cannot concatenate 'str' and 'NoneType' objects

Configuration

Virtualenv........: None
RPC Python........: 2.7.6 (/usr/bin/python)
Interactive Python: ipython (/usr/local/bin/ipython)
Emacs.............: 24.3.1
Elpy..............: 1.6.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/tk12098/.emacs.d/elpa/elpy-20141031.945/elpy/ropebackend.py", line 96, in call_rope
    **kwargs)
  File "/home/tk12098/.local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 101, in get_calltip
    return PyDocExtractor().get_calltip(pyobject, ignore_unknown, remove_self)
  File "/home/tk12098/.local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 569, in get_calltip
    result = self._get_function_signature(pyobject, add_module=True)
  File "/home/tk12098/.local/lib/python2.7/site-packages/rope/contrib/codeassist.py", line 619, in _get_function_signature
    return '%s(%s)' % (location + pyfunction.get_name(),
TypeError: cannot concatenate 'str' and 'NoneType' objects

Rope Debug Information

```

Reproduction:

```Python

source = '''
import pandas as pd
import xgboost as xgb
import csv
import boruta_py
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import gplearn

# XGBoost params:
xgboost_params = {
   "objective": "binary:logistic",
   "booster": "gbtree",
   "eval_metric": "auc",
   "eta": 0.01, # 0.06, #0.01,
   #"min_child_weight": 240,
   "subsample": 0.75,
   "colsample_bytree": 0.68,
   "max_depth": 7
}

print('Load data...')
train = pd.read_csv("bnp_train.csv")
target = train['target']
#feature selection
feature_df =  train.ix[np.random.random_integers(0, len(train), 0.01*train.shape[0])]
feature_targets = feature_df['target']
train = train.drop(['ID','target'],axis=1)
feature_df = feature_df.drop(['ID', 'target'])
test = pd.read_csv("bnp_test.csv")
ids = test['ID'].values
test = test.drop(['ID'],axis=1)
#
print('Clearing...')
for (train_name, train_series), (test_name, test_series) in zip(train.iteritems(),test.iteritems()):
    if train_series.dtype == 'O':
        #for objects: factorize
        train[train_name], tmp_indexer = pd.factorize(train[train_name])
        test[test_name] = tmp_indexer.get_indexer(test[test_name])
        #but now we have -1 values (NaN)
    else:
        #for int or float: fill NaN
        tmp_len = len(train[train_series.isnull()])
        if tmp_len>0:
            train.loc[train_series.isnull(), train_name] = train_series.mean()
        #and Test
        tmp_len = len(test[test_series.isnull()])
        if tmp_len>0:
            test.loc[test_series.isnull(), test_name] = train_series.mean()  #TODO

print('Feature Selection...')
rf = RandomForestClassifier(n_jobs=-1, class_weight='auto')
feat_selector = boruta_py.BorutaPy(rf, n_estimators='auto', verbose=2)
feat_selector.fit(feature_df, feature_targets)

xgtrain = xgb.DMatrix(train.values, target.values)
xgtest = xgb.DMatrix(test.values)

#Now let's fit the model
print('Fit the model...')
boost_round = 10 #1800 #  CHANGE THIS BEFORE START
clf = xgb.train(xgboost_params, xgtrain, num_boost_round=boost_round, verbose_eval=True, maximize=False)

#Make predict
print('Predict...')
test_preds = clf.predict(xgtest, ntree_limit=clf.best_iteration)
# Save results
#
predictions_file = open("simple_xgboost_result.csv", "w")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["ID", "PredictedProb"])
open_file_object.writerows(zip(ids, test_preds))
predictions_file.close()
#
print('Done.')
'''

project = rope.base.project.Project(
    "/home/tk12098/Documents/bnpparibas/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "/home/tk12098/Documents/bnpparibas/simple_xgb.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 2406, resource, maxfixes=5, remove_self=True
)
```

**Comment by ChillarAnand** [comment]
Hi, Thanks for the report.

> Elpy..............: 1.6.0

You are using an old version of elpy. Can you upgrade to latest version and try again?

**Comment by jorgenschaefer** [comment]
Lacking further updates, I assume this problem is resolved. Please do not hesitate to open a new issue if you have further issues.
