### ISSUE TITLE
Elpy error report

### ISSUE THREAD

**Issue by Schroedingberg** [jorgenschaefer/elpy#869]
# Error Message

\<Name: deprecate@244,11\>

# Configuration

Virtualenv........: None
RPC Python........: 2.7.9 (/usr/bin/python)
Interactive Python: ipython (/usr/local/bin/ipython)
Emacs.............: 24.4.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.2
Yapf..............: 0.6.3 (0.7.1 available)
Syntax checker....: flake8 (/usr/local/bin/flake8)

# Traceback

Traceback (most recent call last):
  File "/home/aaron/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/aaron/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 95, in rpc_get_completions
    get_source(source), offset)
  File "/home/aaron/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/aaron/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/local/lib/python2.7/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/usr/local/lib/python2.7/dist-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/usr/local/lib/python2.7/dist-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/usr/local/lib/python2.7/dist-packages/jedi/evaluate/helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: Name: deprecate@244,11

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a bug in Jedi, which we reported upstream in August last year. Sadly, there has not been a release to fix this problem. We're tracking this in #597 – I'll close this issue to keep the discussion in one place. Sorry for the inconvenience, and I hope you can still enjoy Elpy.
