### ISSUE TITLE
'ValueError' object has no attribute 'message'

### ISSUE THREAD

**Issue by WChurchill** [jorgenschaefer/elpy#873]
Configuration

Virtualenv........: None
RPC Python........: 3.5.1 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.2.2 available)
Yapf..............: Not found (0.7.1 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/jedi/_compatibility.py", line 24, in find_module_py33
    loader = importlib.find_loader(string)
  File "/usr/lib/python3.5/importlib/__init__.py", line 87, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: google.__loader__ is None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/winston/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/winston/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 95, in rpc_get_completions
    get_source(source), offset)
  File "/home/winston/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/winston/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/home/winston/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 281, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/imports.py", line 327, in _do_import
    find_module(import_parts[-1])
  File "/usr/lib/python3.5/site-packages/jedi/_compatibility.py", line 28, in find_module_py33
    raise ImportError("Originally ValueError: " + e.message)
AttributeError: 'ValueError' object has no attribute 'message'

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report. This looks like another problem of Jedi with Python 3.5. :-(
