### ISSUE TITLE
issue with tabs

### ISSUE THREAD

**Issue by cnsgsz** [jorgenschaefer/elpy#890]
I seem to run into a similar issue even I have the fix from #499 .

with test1.py as:
```
def test1():
    print("a")
```
highlighting the two lines and c-c c-c works.

but with test2.py as:
```
def test2():
    if True:
        print("a")
```

I got error similar to those in #499 :
> Python 3.3.5 |Anaconda 2.3.0 (64-bit)| (default, Jun  4 2015, 15:22:11) 
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/.../test2.py", line 3
>     print("a")
>              ^
> TabError: inconsistent use of tabs and spaces in indentation

indent-tab-mode is nil in test2.py buffer, but t in the \*Python\* buffer.

> test2.py buffer:
> indent-tabs-mode is a variable defined in `C source code'.
> Its value is nil
> Original value was t
> Local in buffer test.py; global value is t
> 
> *Python* buffer:
> indent-tabs-mode is a variable defined in `C source code'.
> Its value is t

`(setq-default indent-tabs-mode nil)`
fixed the problem just as suggested in #499 .

I checked the elpy code under emacs.d and it has the above commit that closed #499 .

should the \*Python\* buffer also have indent-tabs-mode as nil?

**Comment by jorgenschaefer** [comment]
Hrm. Yes, it probably should. Thanks for the report! :-)
