### ISSUE TITLE
'MergedNamesDict' object has no attribute 'get'

### ISSUE THREAD

**Issue by paula-em-lafon** [jorgenschaefer/elpy#897]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'MergedNamesDict' object has no attribute 'get'

Configuration

Virtualenv........: None
RPC Python........: 2.7.11 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: Not found (1.2.4 available)
Yapf..............: Not found (0.9.0 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/emi/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python2.7/site-packages/jedi/api/__init__.py", line 521, in call_signatures
    self.source, self._pos)
  File "/usr/lib/python2.7/site-packages/jedi/cache.py", line 93, in wrapper
    value = next(generator)
  File "/usr/lib/python2.7/site-packages/jedi/cache.py", line 115, in cache_call_signatures
    yield evaluator.eval_element(call)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/usr/lib/python2.7/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/usr/lib/python2.7/site-packages/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/usr/lib/python2.7/site-packages/jedi/parser/fast.py", line 78, in __getitem__
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
  File "/usr/lib/python2.7/site-packages/jedi/parser/fast.py", line 78, in <genexpr>
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
AttributeError: 'MergedNamesDict' object has no attribute 'get'

Jedi Debug Information

[N] dbg: While parsing u'/home/emi/proyectos/tandlr-api/src/tandlr/registration/api.py', line 23 slowed down the fast parser.
[N] dbg: Parsed /home/emi/proyectos/tandlr-api/src/tandlr/registration/api.py, with 6 parsers in 7 splits.
[N] dbg: eval_element <Name: super@27,15>@(27, 15)

```

Reproduction:

``` Python
import jedi

source = '''\
# -*- coding: utf-8 -*-
import os
from datetime import timedelta

from django.contrib.gis.geos import Polygon
from django.db.models import Q
from django.utils import timezone

from rest_framework import status
from rest_framework.decorators import detail_route
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from tandlr.api.v2. routers import router
from tandlr.core.api import mixins, viewsets
from tandlr.core.api.routers.single import SingleObjectRouter

class RegistrationViewSet(
        mixins.RetrieveModelMixin,
        viewsets.GenericViewSet

        serializer_class=RegistrationProfileV2Serializer
):
    def create(self, request):
        # import v2 serializer
        serializer = serializer_class(data=request.data)
        return super(RegistrationViewSet, self).create(request)
class NewPassViewSet():
    def create(self, request)

class ChangepassViewSet()'''

script = jedi.Script(column=31, source=source, line=27, encoding='utf-8', path=u'/home/emi/proyectos/tandlr-api/src/tandlr/registration/api.py')
script.call_signatures()
```

**Comment by jorgenschaefer** [comment]
Hello and thank you for the report! This is a bug in the Jedi library (see #563), which is sadly not fixed upstream. If you upgrade to Elpy 1.12.0, you won't see this report anymore.
