### ISSUE TITLE
yapf support is fragile in the face of a file with a syntax error

### ISSUE THREAD

**Issue by ViktorHaag** [jorgenschaefer/elpy#901]
When using `C-c C-r f` to format a file, with yapf installed (0.9.0 w/ Python3), and a simple python file containing a syntax error, yapf throws an exception:

```
~/tmp/test : [master x] yapf --style pep8 --no-local-style functional_tests.py
Traceback (most recent call last):
  File "/usr/local/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 248, in run_main
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 166, in main
    verify=args.verify)
  File "/usr/local/lib/python2.7/site-packages/yapf/__init__.py", line 210, in FormatFiles
    logger=logging.warning)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 89, in FormatFile
    verify=verify)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 122, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python2.7/site-packages/yapf/yapflib/pytree_utils.py", line 113, in ParseCodeToTree
    raise e
  File "functional_tests.py", line 20
    msg='Browser title was {0}'.format(browser.title))
      ^
SyntaxError: invalid syntax
```

This then causes Elpy's yapf support to halt unpleasantly, with a "wrong-type-argument char-or-string-p nil" error that's not really explanatory:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  insert(nil)
  (save-excursion (goto-char end) (insert rep) (delete-region beg end))
  (if (string-equal (buffer-substring beg end) rep) nil (save-excursion (goto-char end) (insert rep) (delete-region beg end)))
  elpy-buffer--replace-region(1 1285 nil)
  (let ((new-block (elpy-rpc method (vector (elpy-rpc--buffer-contents)))) (beg (point-min)) (end (point-max))) (elpy-buffer--replace-region beg end new-block))
  (if (use-region-p) (let ((new-block (elpy-rpc method (list (elpy-rpc--region-contents)))) (beg (region-beginning)) (end (region-end))) (elpy-buffer--replace-region beg end new-block)) (let ((new-block (elpy-rpc method (vector (elpy-rpc--buffer-contents)))) (beg (point-min)) (end (point-max))) (elpy-buffer--replace-region beg end new-block)))
  (let ((line (line-number-at-pos)) (col (current-column))) (if (use-region-p) (let ((new-block (elpy-rpc method (list (elpy-rpc--region-contents)))) (beg (region-beginning)) (end (region-end))) (elpy-buffer--replace-region beg end new-block)) (let ((new-block (elpy-rpc method (vector (elpy-rpc--buffer-contents)))) (beg (point-min)) (end (point-max))) (elpy-buffer--replace-region beg end new-block))) (forward-line (1- line)) (forward-char col))
  elpy--fix-code-with-formatter("fix_code_with_yapf")
  elpy-yapf-fix-code()
  funcall-interactively(elpy-yapf-fix-code)
  call-interactively(elpy-yapf-fix-code record nil)
  command-execute(elpy-yapf-fix-code record)
  execute-extended-command(nil "elpy-yapf-fix-code" "elpy-yapf")
  funcall-interactively(execute-extended-command nil "elpy-yapf-fix-code" "elpy-yapf")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

It'd be useful if the yapf exception was gracefully handled so that the code skips over attempting to use it and continues on with autopep8 (if present). The autopep8 formatter was able to consume the same file and produce some output.

Took me a while to realize that it was the underlying yapf script that was throwing the exception and this was causing difficulties for Elpy.

**Comment by ChillarAnand** [comment]
Thanks for a detailed bug report.

Ideally yapf should format code(like autopep8) even if there is syntax error. However elpy should show a relevant message without bothering users about it.

**Comment by ChillarAnand** [comment]
For now, if you want to format buffers with syntax errors you can use `M-x elpy-autopep8-fix-code` to format it with autopep8.
