### ISSUE TITLE
Elpy Error The backend encountered an unexpected error.

### ISSUE THREAD

**Issue by MarkSmithlxviii** [jorgenschaefer/elpy#927]
I opened the file and the bug happened.  I don't think I did anything else sorry I can't provide any more information than that.  

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

'in <string>' requires string as left operand, not int

Configuration

Virtualenv........: None
RPC Python........: 3.4.4 (c:/Users/marka/Anaconda3/python.exe)
Interactive Python: ipython (c:/Users/marka/Anaconda3/Scripts/ipython.exe)
Emacs.............: 24.5.1
Elpy..............: 1.10.0
Jedi..............: 0.9.0
Rope..............: 0.10.3
Importmagic.......: 0.1.3 (0.1.7 available)
Autopep8..........: 0.1.3 (0.1.7 available)
Syntax checker....: flake8.exe (c:/Users/marka/Anaconda3/Scripts/flake8.exe)

Traceback

Traceback (most recent call last):
  File "c:\Users\marka\AppData\Roaming\.emacs.d\elpa\elpy-20151101.401\elpy\ropebackend.py", line 100, in call_rope
    **kwargs)
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\contrib\codeassist.py", line 97, in get_calltip
    pyname = fixer.pyname_at(offset)
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\contrib\fixsyntax.py", line 51, in pyname_at
    pymodule = self.get_pymodule()
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\base\utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\contrib\fixsyntax.py", line 27, in get_pymodule
    self.resource.read() == code:
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\base\resources.py", line 111, in read
    return fscommands.file_data_to_unicode(data)
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\base\fscommands.py", line 208, in file_data_to_unicode
    result = _decode_data(data, encoding)
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\base\fscommands.py", line 218, in _decode_data
    encoding = read_str_coding(data)
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\base\fscommands.py", line 260, in read_str_coding
    return _find_coding(source[:second])
  File "c:\Users\marka\Anaconda3\lib\site-packages\rope\base\fscommands.py", line 270, in _find_coding
    if text[start] not in '=:':
TypeError: 'in <string>' requires string as left operand, not int

Rope Debug Information

```

Reproduction:

```Python

source = '''
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 28 13:09:11 2014

@author: Mark
"""

# The first problem set from the MIT open courseware 
# introduction to computer science and programming
# the Goal of this program is laid out in the pset0
# 1. Ask the user to input their last name
# 2. Ask the user to input their first name
# 3. Print out the user's first and last name in that order


last = raw_input('Enter your last name --> ')
first = raw_input('Enter your first name --> ')

print first
print last
'''

project = rope.base.project.Project(
    "c:/Users/marka/Documents/Reference/Python/6-00sc-spring-2011/mit600/ProbSet0/",
    ropefolder=None
)
resource = rope.base.libutils.path_to_resource(
    project,
    "c:/Users/marka/Documents/Reference/Python/6-00sc-spring-2011/mit600/ProbSet0/pset0.py",
    'file'
)
rope.contrib.codeassist.get_calltip(
    project, source, 28, resource, maxfixes=5, remove_self=True
)
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This is a bug in Rope. I'll report it upstream when I get around to that.
