### ISSUE TITLE
Error Message: 'Operator' object has no attribute 'get_definition'

### ISSUE THREAD

**Issue by alakyadav** [jorgenschaefer/elpy#937]
```
Error Message

'Operator' object has no attribute 'get_definition'

Configuration

Virtualenv........: None
RPC Python........: 3.5.2 (/usr/bin/python)
Interactive Python: python (/usr/bin/python)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Autopep8..........: 1.2.4
Yapf..............: Not found (0.11.0 available)
Syntax checker....: flake8 (/usr/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/alakyadav/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 227, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alakyadav/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 341, in run_with_debug
    return getattr(script, name)()
  File "/usr/lib/python3.5/site-packages/jedi/api/__init__.py", line 197, in completions
    for p in call_sig.params:
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/usr/lib/python3.5/site-packages/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'

Jedi Debug Information

[N] dbg: Parsed /home/alakyadav/alak.py, with 0 parsers in 3 splits.
[N] dbg: execute: <CompiledObject: <class 'str'>> <Arguments: ()>
[N]  dbg: execute: <InstanceElement of <eFunction of <Function: __init__@238-242>>> <Arguments: ()>
[N]  dbg: execute result: [] in <InstanceElement of <eFunction of <Function: __init__@238-242>>>
[N] dbg: execute result: [<eInstance of <CompiledObject: <class 'str'>>(<Arguments: ()>)>] in <CompiledObject: <class 'str'>>
[N] dbg: eval_element Node(power, [<Name: threading@11,0>, Node(trailer, [<Operator: .>, <Name: Thread@11,10>])])@(11, 0)
[N] dbg: finder.filter_name "<Name: threading@11,0>" in (<ModuleWrapper: <fast.FastModule: alak@1-12>>): '[<Name: threading@2,7>]'@(11, 0)
[N] dbg: search_module 'threading' in '/home/alakyadav/alak.py'
[N] dbg: after import: [<ModuleWrapper: <fast.FastModule: threading@1-1353>>]
[N] dbg: finder._names_to_types: [<Name: threading@2,7>] -> [<ModuleWrapper: <fast.FastModule: threading@1-1353>>]
[N] dbg: eval_trailer: Node(trailer, [<Operator: .>, <Name: Thread@11,10>]) in scope <ModuleWrapper: <fast.FastModule: threading@1-1353>>
[N] dbg: finder.filter_name "<Name: Thread@11,10>" in (<ModuleWrapper: <fast.FastModule: threading@1-1353>>): '[<Name: Thread@736,6>]'@None
[N] dbg: finder._names_to_types: [<FakeName: Thread@736,6>] -> [<eClass of <Class: Thread@736-1156>>]

```

Reproduction:

```Python
import jedi

source = '''\
import resource
import threading


def print_this(i):
    print(i)
    i += 1

i = 0
t1 = threading.Thread(target=print_this, args=(i))
t2 = threading.Thread(target=print_this, args=(i))
'''

script = jedi.Script(column=45, encoding='utf-8', line=11, path='/home/alakyadav/alak.py', source=source)
script.completions()
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a bug in Jedi which hopefully will be fixed in the upcoming 0.10.0 release … The same has been reported as #810, so I will close this issue to keep the discussion in one spot. Please do not hesitate to open a new issue if you have further problems!
