### ISSUE TITLE
Elpy bug (as per request)

### ISSUE THREAD

**Issue by yrdeboer** [jorgenschaefer/elpy#941]
Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

<Name: deprecate@220,11>

Configuration

Virtualenv........: venv3 (/home/ytsboe/ana/venv3)
RPC Python........: 3.4.3 (/home/ytsboe/ana/venv3/bin/python)
Interactive Python: python (/home/ytsboe/ana/venv3/bin/python)
Emacs.............: 24.3.1
Elpy..............: 1.7.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: Not found (0.1.7 available)
Syntax checker....: flake8 (/home/ytsboe/ana/venv3/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ytsboe/.emacs.d/elpa/elpy-20150206.1012/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/ytsboe/.emacs.d/elpa/elpy-20150206.1012/elpy/server.py", line 93, in rpc_get_completions
    get_source(source), offset)
  File "/home/ytsboe/.emacs.d/elpa/elpy-20150206.1012/elpy/server.py", line 48, in _call_backend
    return meth(*args, **kwargs)
  File "/home/ytsboe/.emacs.d/elpa/elpy-20150206.1012/elpy/jedibackend.py", line 45, in rpc_get_completions
    for proposal in proposals]
  File "/home/ytsboe/.emacs.d/elpa/elpy-20150206.1012/elpy/jedibackend.py", line 45, in <listcomp>
    for proposal in proposals]
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
  File "/home/ytsboe/ana/venv3/lib/python3.4/site-packages/jedi/evaluate/helpers.py", line 55, in <listcomp>
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@220,11>
```

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! This is a bug in Jedi, which was reported here as #597, and which we reported upstream – the author of Jedi thinks this is fixed in the latest development version of Jedi. If you feel comfortable with that, you can try the latest development version and tell them that it worked. Otherwise, I'ma fraid you'll have to wait for the next Jedi release. :-(

I hope this answer helps. I'll close this report so we can track the bug in one place only, but please do not hesitate to open a new issue if you have further problems!

**Comment by yrdeboer** [comment]
Understood, thank you!
