### ISSUE TITLE
Jedi: ValueError: Node(simple_stmt, [<ExprStmt: counter = 0@15,0>, <Whitespace:  >]) is not in list

### ISSUE THREAD

**Issue by ddovod** [jorgenschaefer/elpy#962]
Hi. I got some error today, so posting in here. Thank you a lot!

Elpy Error

The backend encountered an unexpected error. This indicates a bug in
Elpy. Please open a bug report with the data below in the Elpy bug
tracker:

https://github.com/jorgenschaefer/elpy/issues/new

```
Error Message

Node(simple_stmt, [<ExprStmt: counter = 0@15,0>, <Whitespace: 
>]) is not in list

Configuration

Virtualenv........: emacs_python2 (/home/ddovod/.virtualenvs/emacs_python2)
RPC Python........: 2.7.12 (/usr/bin/python)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 24.5.1
Elpy..............: 1.11.0
Jedi..............: 0.9.0
Rope..............: Not found (0.10.3 available)
Importmagic.......: 0.1.7
Autopep8..........: 1.2.4
Yapf..............: 0.11.1
Syntax checker....: flake8 (/usr/local/bin/flake8)

Traceback

Traceback (most recent call last):
  File "/home/ddovod/.emacs.d/elpa/elpy-20160131.118/elpy/rpc.py", line 100, in handle_request
    result = method(*params)
  File "/home/ddovod/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 107, in rpc_get_completion_docstring
    None, completion)
  File "/home/ddovod/.emacs.d/elpa/elpy-20160131.118/elpy/server.py", line 50, in _call_backend
    return meth(*args, **kwargs)
  File "/home/ddovod/.emacs.d/elpa/elpy-20160131.118/elpy/jedibackend.py", line 52, in rpc_get_completion_docstring
    return proposal.docstring(fast=False)
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 457, in docstring
    return _Help(definition).full()
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 724, in full
    return self.raw()
  File "/usr/local/lib/python2.7/dist-packages/jedi/api/classes.py", line 733, in raw
    return self._name.raw_doc
  File "/usr/local/lib/python2.7/dist-packages/jedi/parser/tree.py", line 75, in raw_doc
    index = c.index(simple_stmt)
ValueError: Node(simple_stmt, [<ExprStmt: counter = 0@15,0>, <Whitespace: 
>]) is not in list
```

**Comment by ddovod** [comment]
Some other info: here is the buffer content when error is appeared
```python

import re
import numpy as np


data = []
with open('sentences.txt') as f:
    data = f.readlines()

data = map(lambda x: x.lower(), data)
data = map(lambda x: re.split('[^a-z]', x), data)
data = map(lambda x: filter(lambda w: len(w), x), data)

wordDict = {}
counter = 0
for s in data:
    for w in s:
        if w not in wordDict:
            wordDict[w] = counter
            counter += 1

mat = np.ndarray(shape=(len(data), count|)) <- | is cursor position
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! This is a bug in Jedi. I'll report this upstream eventually (if you don't beat me to it :-)), as it can only be fixed there. Hopefully there will be a new release soon that fixes this then.
