### ISSUE TITLE
The interpreter shows wrong line number

### ISSUE THREAD

**Issue by amirteymuri** [jorgenschaefer/elpy#983]
When i run the interpreter with `C-c C-z`, each time an error occurs inside my `file.py`, the error message shows always the actual line number + 1. Here is an example:

    # file.py
    1 from tst import * 

    # the interpreter error message:
    >>> Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/home/amir/programming/python/c_m/lern.py", line 2, in <module>
    
    AttributeError: 'module' object has no attribute 'foo'

How can i fix this problem?

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Does this problem exist without Elpy and plain python-mode as well? If so, could you report this with Emacs directly?

**Comment by amirteymuri** [comment]
Hello,

yes this happens without elpy. I have send the question to an emacs forum. Thanks for your hint.

**Comment by jorgenschaefer** [comment]
Thank you for reporting this upstream! :-)
