### ISSUE TITLE
Indentation Problems

### ISSUE THREAD

**Issue by amirteymuri** [jorgenschaefer/elpy#988]
I have 2 difficulties with indentation matters in elpy:

1. In the example below when i choose one of the function definitions with `M-h` as a block and try to evaluate **only** that function with `C-c C-c` i get the TabError:

    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/tmp/py2585eSP", line 5
        if x % 2 == 0:
                     ^
    TabError: inconsistent use of tabs and spaces in indentation

2. In the code below when i am on the `if __name__ == "__main__:"` line and hit the Enter to go to the next line, the `if __name__ == "__main__:"` line gets also indented as seen below:

def genFn():
    x = 0
    while True:
        if x % 2 == 0:
            print("in IF")
            yield x
            print("after yield")
        if x > 10:
            return x    
        print("outside IF : %d" % x)
        x += 1
        print("outside IF : %d" % x)

def infinitFibs():
    a, b = 0, 1
    while True:
        a, b = b, a + b
        yield a

        if __name__ == "__main__":

Is there a way stopping these behaviors?

Greetings, Amir

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Do these problems exist with Elpy disabled (and using `M-x python-shell-send-region` instead of `C-c C-c`)? If so, could you file a report with Emacs directly?

**Comment by EmperorDali** [comment]
I am also having the TabError bug. It does *not* occur with `python-shell-send-region`.

**Comment by amirteymuri** [comment]
With elpy disabled and using `python-shell-send-region` the Error does not happen. Besides i get a strange `IndentationError` in this another example when i try to evaluate the `def` using `C-M-x`:

    def foo(*args, **kwargs):
        print args, kwargs

This has raised this error **with elpy disabled**:

    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/amir/programming/python/tst.py", line 2
        if True:
               ^
    IndentationError: expected an indented block

and **with elpy enabled**:

    >>> Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/amir/programming/python/tst.py", line 2
        if True:
               ^
    SyntaxError: unexpected EOF while parsing

**Comment by jorgenschaefer** [comment]
I have no idea why this behavior would change with Elpy enabled, sorry.

**Comment by muahah** [comment]
I also have the `TabError`.
I traced wild tabulations back to `elpy--shell-region-without-indentation` where `indent-rigidly` add them to the code.
It can be fixed by using `(untabify (point-min) (point-max))` just after `indent-rigidly` but I think the override of `indent-tabs-mode` with `nil` was already supposed to handle this.
I use emacs 25.1, so... emacs bug ?

I still have made a pull request (#1039), for those who want to try this workaround.
